import { describe, expect, it } from 'vitest'
import { ReferenceEditor, ReferenceServer } from '../../tests/kernel/reference-model.js'

describe('independent business specification', () => {
  it('keeps a conflicted deletion through an unrelated successful save', () => {
    const server = new ReferenceServer({ a: { x: 0 }, b: { x: 0 } })
    const editor = new ReferenceEditor(server.rows)
    const deletion = editor.delete('a')
    server.external({ a: { x: 1 }, b: { x: 0 } })
    editor.observe(server.rows, server.version)
    const edit = editor.write('b', { x: 2 })
    const request = editor.freeze('save-b')
    expect(request.coverage).toEqual([edit])
    expect(request.items).toEqual([{ entity: 'b', value: { x: 2 } }])
    editor.receive(server.apply(request))
    editor.observe(server.rows, server.version)
    expect(editor.requirements.find(item => item.id === deletion)).toMatchObject({ kind: 'delete', state: 'pending', base: { x: 0 } })
    expect(editor.blockedEntities()).toEqual(['a'])
    expect(server.rows).toEqual({ a: { x: 1 }, b: { x: 2 } })
  })

  it('settles a pending deletion only on complete proof of absence', () => {
    const editor = new ReferenceEditor({ a: { x: 0 } })
    editor.delete('a')
    editor.observe({ a: { x: 1 } }, 1)
    expect(editor.blockedEntities()).toEqual(['a'])
    editor.observe({}, 2)
    expect(editor.preview()).toEqual({})
    expect(editor.requirements).toMatchObject([{ kind: 'delete', state: 'satisfied' }])
    expect(() => editor.freeze('no-create')).toThrow('Nothing can be saved')
  })

  it('retains submitted display contribution until a covering complete authority arrives', () => {
    const server = new ReferenceServer({ a: { x: 0 } })
    const editor = new ReferenceEditor(server.rows)
    editor.write('a', { x: 1 })
    const request = editor.freeze('save')
    editor.receive(server.apply(request, () => ({ x: 1.5 })))
    expect(editor.outcome).toBe('awaiting-authority')
    expect(editor.preview()).toEqual({ a: { x: 1 } })
    editor.observe({ a: { x: 0 } }, 0)
    expect(editor.outcome).toBe('awaiting-authority')
    expect(() => editor.freeze('duplicate')).toThrow('unresolved')
    editor.observe(server.rows, server.version)
    expect(editor.outcome).toBe('idle')
    expect(editor.preview()).toEqual({ a: { x: 1.5 } })
  })

  it('resolves a successor base to the exact receipt while retaining newer remote data', () => {
    const server = new ReferenceServer({ a: { x: 0, hidden: 0 } })
    const editor = new ReferenceEditor(server.rows)
    editor.write('a', { x: 1 })
    const request = editor.freeze('save')
    const successor = editor.write('a', { x: 2 })
    const receipt = server.apply(request, () => ({ x: 1.5, hidden: 1 }))
    server.external({ a: { x: 3, hidden: 2 } })
    editor.observe(server.rows, server.version)
    editor.receive(receipt)
    expect(editor.authority).toEqual({ a: { x: 3, hidden: 2 } })
    expect(editor.preview()).toEqual({ a: { x: 2, hidden: 2 } })
    expect(editor.requirements.find(item => item.id === successor)?.base).toEqual({ x: 1.5, hidden: 1 })
    expect(editor.blockedEntities()).toEqual(['a'])
  })

  it('does not rewrite a business calculation dependency using canonical output', () => {
    const server = new ReferenceServer({ a: { qty: 1, total: 10 } })
    const editor = new ReferenceEditor(server.rows)
    editor.write('a', { qty: 2 })
    const request = editor.freeze('quantity')
    editor.write('a', { total: 20 }, { qty: 2 })
    editor.receive(server.apply(request, row => row === 'a' ? { qty: 3, total: 10 } : {}))
    editor.observe(server.rows, server.version)
    expect(editor.preview()).toEqual({ a: { qty: 3, total: 20 } })
    expect(editor.blockedEntities()).toEqual(['a'])
    expect(() => editor.freeze('incorrect-calculation')).toThrow('Nothing can be saved')
  })

  it('suppresses an unknown write on undo plus definitive non-application', () => {
    const editor = new ReferenceEditor({ a: { x: 0 } })
    const action = editor.write('a', { x: 1 })
    const request = editor.freeze('save')
    editor.unknown()
    editor.undo(action)
    expect(editor.retry()).toEqual(request)
    expect(editor.preview()).toEqual({ a: { x: 0 } })
    editor.observe({ a: { x: 3 } }, 1)
    editor.notApplied()
    expect(editor.preview()).toEqual({ a: { x: 3 } })
    expect(() => editor.freeze('must-not-write-zero')).toThrow('Nothing can be saved')
  })

  it('compensates an unknown write on undo plus exact applied evidence', () => {
    const server = new ReferenceServer({ a: { x: 0 } })
    const editor = new ReferenceEditor(server.rows)
    const action = editor.write('a', { x: 1 })
    const request = editor.freeze('save')
    editor.unknown(); editor.undo(action)
    const receipt = server.apply(editor.retry(), () => ({ x: 1.5 }))
    expect(server.apply(request)).toEqual(receipt)
    expect(server.writes).toBe(1)
    editor.receive(receipt); editor.observe(server.rows, server.version)
    const compensation = editor.freeze('compensate')
    expect(compensation.items).toEqual([{ entity: 'a', value: { x: 0 } }])
    expect(editor.requirements.at(-1)?.base).toEqual({ x: 1.5 })
    editor.receive(server.apply(compensation)); editor.observe(server.rows, server.version)
    expect(server.rows).toEqual({ a: { x: 0 } })
    expect(server.writes).toBe(2)
  })

  it('cannot attach an old edit to a different incarnation of the same business key', () => {
    const editor = new ReferenceEditor({ 'key:g1': { x: 0 } })
    editor.write('key:g1', { x: 2 })
    editor.observe({ 'key:g2': { x: 1 } }, 1)
    expect(editor.blockedEntities()).toEqual(['key:g1'])
    expect(editor.preview()['key:g2']).toEqual({ x: 1 })
    expect(() => editor.freeze('wrong-incarnation')).toThrow('Nothing can be saved')
  })

  it('preserves a whole request when business normalization fails on its second item', () => {
    const server = new ReferenceServer({ a: { x: 0 }, b: { x: 0 } })
    const editor = new ReferenceEditor(server.rows)
    editor.write('a', { x: 1 }); editor.write('b', { x: 2 })
    const request = editor.freeze('atomic')
    expect(() => server.apply(request, (entity, row) => {
      if (entity === 'b') throw new Error('Rejected b')
      return row
    })).toThrow('Rejected b')
    expect(server.rows).toEqual({ a: { x: 0 }, b: { x: 0 } })
    expect(server.writes).toBe(0)
    expect(editor.preview()).toEqual({ a: { x: 1 }, b: { x: 2 } })
  })

  it('fences rejected request identities and rejects retries with a changed payload', () => {
    const server = new ReferenceServer({ a: { x: 0 } })
    const editor = new ReferenceEditor(server.rows)
    editor.write('a', { x: 1 })
    const request = editor.freeze('save')
    const receipt = server.apply(request)
    expect(server.apply(request)).toEqual(receipt)
    expect(() => server.apply({ ...request, items: [{ entity: 'a', value: { x: 2 } }] })).toThrow('Id reused')
    expect(() => server.apply({ ...request, id: 'stale' })).toThrow('Definitely not applied')
    expect(() => server.apply({ ...request, id: 'stale', version: server.version })).toThrow('Definitely not applied')
    expect(server.writes).toBe(1)
  })

  it('records only the final canonical item for coalesced edits and undoes actions in sequence', () => {
    const server = new ReferenceServer({ a: { x: 0, hidden: 0 } })
    const editor = new ReferenceEditor(server.rows)
    const first = editor.write('a', { x: 1 })
    const second = editor.write('a', { x: 2 })
    const request = editor.freeze('coalesced')
    expect(request.coverage).toEqual([first, second])
    expect(request.items).toEqual([{ entity: 'a', value: { x: 2, hidden: 0 } }])
    editor.receive(server.apply(request, () => ({ x: 2.2, hidden: 1 })))
    editor.observe(server.rows, server.version)
    expect([...editor.applied.values()]).toEqual([{ x: 2.2, hidden: 1 }, { x: 2.2, hidden: 1 }])
    editor.undo(second)
    expect(editor.preview()).toEqual({ a: { x: 1, hidden: 1 } })
    editor.undo(first)
    expect(editor.preview()).toEqual({ a: { x: 0, hidden: 1 } })
    expect(editor.blockedEntities()).toEqual([])
    expect(editor.freeze('two-undos').items).toEqual([{ entity: 'a', value: { x: 0, hidden: 1 } }])
  })

  it('settles a coalesced pending chain when the remote reaches its final target', () => {
    const editor = new ReferenceEditor({ a: { x: 0, hidden: 0 } })
    editor.write('a', { x: 1 }); editor.write('a', { x: 2 })
    editor.observe({ a: { x: 2, hidden: 5 } }, 1)
    expect(editor.blockedEntities()).toEqual([])
    expect(editor.requirements.map(item => item.state)).toEqual(['satisfied', 'satisfied'])
    editor.undo(2)
    expect(editor.preview()).toEqual({ a: { x: 2, hidden: 5 } })
    expect(() => editor.freeze('no-contribution')).toThrow('Nothing can be saved')
  })

  it('does not satisfy a calculation just because a later local edit covers its changed dependency', () => {
    const editor = new ReferenceEditor({ a: { qty: 1, total: 10 } })
    editor.write('a', { total: 20 }, { qty: 1 })
    editor.write('a', { qty: 2 })
    editor.observe({ a: { qty: 2, total: 20 } }, 1)
    expect(editor.blockedEntities()).toEqual(['a'])
    expect(editor.requirements.map(item => item.state)).toEqual(['pending', 'pending'])
  })

  it('does not treat an intermediate local value as acknowledgement of a coalesced chain', () => {
    const editor = new ReferenceEditor({ a: { x: 0 } })
    editor.write('a', { x: 1 }); editor.write('a', { x: 2 })
    editor.observe({ a: { x: 1 } }, 1)
    // The normalized requirement is still expected 0, desired 2. Nobody has
    // proved our intermediate action was committed or separately satisfied.
    expect(editor.blockedEntities()).toEqual(['a'])
    expect(editor.requirements.map(item => item.state)).toEqual(['pending', 'pending'])
    expect(() => editor.freeze('intermediate-is-not-a-receipt')).toThrow('Nothing can be saved')
  })
})
