import { expect, test } from './test.js'

test('bulk tag addition retains mixed originals and parameters through reload, save and saved undo', async ({ page }) => {
  await page.goto('/#/playground')
  await page.getByRole('switch', { name: 'Auto-save', exact: true }).click()
  await expect(page.getByRole('switch', { name: 'Auto-save', exact: true })).not.toBeChecked()
  const grid = page.getByRole('grid', { name: 'Inventory items' }), tags = grid.locator('[data-column-key="tags"]')
  const before = await tags.getByRole('group').evaluateAll(elements => elements.map(element => element.getAttribute('aria-label')!))
  await tags.nth(0).click()
  await tags.nth(1).click({ modifiers: ['Shift'] })
  await page.getByRole('button', { name: 'Edit selection…', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Edit 2 selected cells' })
  await expect(dialog.getByRole('heading', { name: 'Edit 2 selected cells' })).toBeVisible()
  await expect(dialog.getByRole('combobox', { name: 'Operation' })).toHaveValue('keep')
  await expect(dialog.getByRole('button', { name: 'Apply to 2 cells' })).toBeDisabled()
  await dialog.getByRole('combobox', { name: 'Operation' }).selectOption('add')
  await dialog.getByRole('checkbox', { name: 'Featured', exact: true }).check()
  await expect(dialog.getByRole('checkbox', { name: 'Legacy', exact: true })).toBeDisabled()
  await expect(dialog.getByRole('button', { name: 'Apply to 2 cells' })).toBeEnabled()
  await page.reload()
  await page.getByRole('button', { name: 'Resume editing', exact: true }).click()
  await expect(dialog.getByRole('combobox', { name: 'Operation' })).toHaveValue('add')
  await expect(dialog.getByRole('checkbox', { name: 'Featured', exact: true })).toBeChecked()
  await dialog.getByRole('button', { name: 'Apply to 2 cells' }).click()
  await expect(dialog).toHaveCount(0)
  await expect(tags.nth(0)).toHaveAccessibleName(before[0]!)
  await expect(tags.nth(1)).toHaveAccessibleName('Featured, Wholesale')
  await expect(tags.nth(2)).toHaveAccessibleName(before[2]!)
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(page.getByText('1 saves', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Save changes', exact: true })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Refresh rows', exact: true })).toBeEnabled()
  await page.reload()
  await expect(tags.nth(1)).toHaveAccessibleName('Featured, Wholesale')
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  for (const [index, label] of before.entries()) await expect(tags.nth(index)).toHaveAccessibleName(label)
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(page.getByText('2 saves', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Save changes', exact: true })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Refresh rows', exact: true })).toBeEnabled()
  await page.reload()
  for (const [index, label] of before.entries()) await expect(tags.nth(index)).toHaveAccessibleName(label)
  await tags.nth(0).click()
  await tags.nth(1).click({ modifiers: ['Shift'] })
  await page.getByRole('button', { name: 'Edit selection…', exact: true }).click()
  await dialog.getByRole('combobox', { name: 'Operation' }).selectOption('replace')
  await dialog.getByRole('checkbox', { name: 'Seasonal', exact: true }).check()
  await dialog.getByRole('button', { name: 'Apply to 2 cells' }).click()
  await expect(dialog).toHaveCount(0)
  await expect(tags.nth(0)).toHaveAccessibleName('Seasonal')
  await expect(tags.nth(1)).toHaveAccessibleName('Seasonal')
  await expect(tags.nth(2)).toHaveAccessibleName(before[2]!)
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(page.getByText('3 saves', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Refresh rows', exact: true })).toBeEnabled()
  await page.reload()
  await expect(tags.nth(0)).toHaveAccessibleName('Seasonal')
  await expect(tags.nth(1)).toHaveAccessibleName('Seasonal')
})

test('the context-menu bulk editor can remove disabled legacy tags without changing other selected tags', async ({ page }) => {
  await page.goto('/#/playground')
  await page.getByRole('switch', { name: 'Auto-save', exact: true }).click()
  await expect(page.getByRole('switch', { name: 'Auto-save', exact: true })).not.toBeChecked()
  const grid = page.getByRole('grid', { name: 'Inventory items' }), tags = grid.locator('[data-column-key="tags"]')
  await expect(tags.nth(2)).toHaveAccessibleName('Legacy')
  await tags.nth(1).click()
  await tags.nth(2).click({ modifiers: ['Shift'] })
  await tags.nth(2).click({ button: 'right' })
  await page.getByRole('menuitem', { name: 'Edit value', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Edit 2 selected cells' })
  await dialog.getByRole('combobox', { name: 'Operation' }).selectOption('remove')
  await dialog.getByRole('checkbox', { name: 'Legacy', exact: true }).check()
  await dialog.getByRole('combobox', { name: 'Operation' }).selectOption('add')
  await dialog.getByRole('button', { name: 'Apply to 2 cells' }).click()
  await expect(dialog.getByRole('alert')).toHaveText('An unavailable tag cannot be added to this cell.')
  await expect(tags.nth(1)).toHaveAccessibleName('Wholesale')
  await expect(tags.nth(2)).toHaveAccessibleName('Legacy')
  await expect(dialog.getByRole('checkbox', { name: 'Legacy', exact: true })).toBeChecked()
  await dialog.getByRole('combobox', { name: 'Operation' }).selectOption('remove')
  await dialog.getByRole('button', { name: 'Apply to 2 cells' }).click()
  await expect(dialog).toHaveCount(0)
  await expect(tags.nth(1)).toHaveAccessibleName('Wholesale')
  await expect(tags.nth(2)).toHaveAccessibleName('No tags')
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(page.getByText('1 saves', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Save changes', exact: true })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Refresh rows', exact: true })).toBeEnabled()
  await page.reload()
  await expect(tags.nth(2)).toHaveAccessibleName('No tags')
})

test('tag overflow tracks column space without hiding the full value from editing', async ({ page }) => {
  await page.goto('/#/playground')
  const grid = page.getByRole('grid', { name: 'Inventory items' })
  const tags = grid.getByRole('gridcell', { name: 'Featured, Seasonal, Wholesale', exact: true }).first()
  for (const width of [1440, 1920, 2560, 3840]) {
    await page.setViewportSize({ width, height: 1000 })
    await expect(tags).toHaveAccessibleName('Featured, Seasonal, Wholesale')
    const list = tags.getByRole('group', { name: 'Featured, Seasonal, Wholesale', exact: true })
    await expect.poll(() => list.evaluate(element => {
      const shown = [...element.children].filter(child => child.classList.contains('data-grid-tag'))
      return shown.reduce((count, child) => count + (child.classList.contains('data-grid-tag--overflow') ? Number(child.textContent!.slice(1)) : 1), 0)
    })).toBe(3)
    if (width === 1440) await expect(list.locator(':scope > .data-grid-tag--overflow')).toHaveText(/^\+[12]$/)
    if (width === 3840) await expect(list.locator(':scope > .data-grid-tag--overflow')).toHaveCount(0)
    await page.screenshot({ path: `/tmp/tag-parity-${test.info().project.name}-${width}.png` })
  }
  await tags.dblclick()
  const choices = page.getByRole('group', { name: 'Choose values', exact: true })
  for (const label of ['Featured', 'Seasonal', 'Wholesale']) await expect(choices.getByRole('checkbox', { name: label, exact: true })).toBeChecked()
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(tags).toHaveAccessibleName('Featured, Seasonal, Wholesale')
})

test('unchanged tags keep their measurements while another cell is edited', async ({ page }) => {
  await page.addInitScript(() => {
    const observe = ResizeObserver.prototype.observe
    ResizeObserver.prototype.observe = function (target, options) {
      if (target.classList.contains('data-grid-tag-list') || target.classList.contains('data-grid-tag-measurements')) {
        document.documentElement.dataset.tagObservations = String(Number(document.documentElement.dataset.tagObservations ?? 0) + 1)
      }
      return observe.call(this, target, options)
    }
  })
  await page.goto('/#/playground')
  const grid = page.getByRole('grid', { name: 'Inventory items' })
  await expect(grid.getByRole('row')).toHaveCount(37)
  const name = grid.getByRole('gridcell', { name: 'Amber poster', exact: true })
  await name.click()
  await expect(name).toHaveAttribute('aria-selected', 'true')
  const before = await page.locator('html').getAttribute('data-tag-observations')
  await name.dblclick()
  const input = page.getByRole('textbox', { name: 'Name', exact: true })
  await input.fill('Stable tag measurements')
  await expect(page.getByRole('button', { name: 'Apply value', exact: true })).toBeEnabled()
  await expect(page.locator('html')).toHaveAttribute('data-tag-observations', before!)
})
