import { expect, test } from './test.js'

test('dragging cells selects a rectangle that can be bulk edited, saved, reopened and undone', async ({ page }) => {
  await page.goto('/')
  const grid = page.getByRole('grid', { name: 'Quick-start products' })
  const first = grid.getByRole('gridcell', { name: '12', exact: true })
  const last = grid.getByRole('gridcell', { name: '36', exact: true })
  const start = (await first.boundingBox())!, end = (await last.boundingBox())!
  await page.mouse.move(start.x + start.width / 2, start.y + start.height / 2)
  await page.mouse.down()
  await page.mouse.move(end.x + end.width / 2, end.y + end.height / 2, { steps: 8 })
  await page.mouse.up()
  await expect(grid.getByRole('gridcell', { selected: true })).toHaveText(['12', '24', '36'])
  await page.getByRole('button', { name: 'Edit value', exact: true }).click()
  await page.getByRole('textbox').fill('50')
  await page.getByRole('button', { name: 'Apply value', exact: true }).click()
  await expect(grid.getByRole('gridcell', { name: '50', exact: true })).toHaveCount(3)
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Refresh rows', exact: true })).toBeEnabled()
  await expect(page.getByRole('button', { name: 'Save changes', exact: true })).toBeDisabled()
  await page.reload()
  await expect(grid.getByRole('gridcell', { name: '50', exact: true })).toHaveCount(3)
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(grid.getByRole('gridcell', { name: '12', exact: true })).toBeVisible()
  await expect(grid.getByRole('gridcell', { name: '24', exact: true })).toBeVisible()
  await expect(grid.getByRole('gridcell', { name: '36', exact: true })).toBeVisible()
})

test('double-click edits the clicked cell and preserves invalid input across another edit gesture and reload', async ({ page }) => {
  await page.goto('/')
  const grid = page.getByRole('grid', { name: 'Quick-start products' })
  await grid.getByRole('gridcell', { name: '24', exact: true }).dblclick()
  const input = page.getByRole('textbox', { name: 'Quantity', exact: true })
  await expect(input).toBeFocused()
  await expect(input).toHaveValue('24')
  await input.fill('-1')
  await page.getByRole('button', { name: 'Apply value', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Enter a non-negative whole number.')
  await grid.getByRole('gridcell', { name: '36', exact: true }).dblclick()
  await expect(input).toHaveValue('-1')
  await page.reload()
  await page.getByRole('button', { name: 'Resume editing', exact: true }).click()
  await expect(input).toHaveValue('-1')
  await input.fill('42')
  await page.getByRole('button', { name: 'Apply value', exact: true }).click()
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Refresh rows', exact: true })).toBeEnabled()
  await expect(page.getByRole('button', { name: 'Save changes', exact: true })).toBeDisabled()
  await page.reload()
  await expect(grid.getByRole('row').filter({ hasText: 'Blue card' }).getByRole('gridcell', { name: '42', exact: true })).toBeVisible()
  await expect(grid.getByRole('gridcell', { name: '36', exact: true })).toBeVisible()
})

for (const key of ['Enter', 'F2']) test(`${key} opens the focused cell editor`, async ({ page }) => {
  await page.goto('/')
  await page.getByRole('gridcell', { name: 'Blue card', exact: true }).press(key)
  await expect(page.getByRole('textbox', { name: 'Name', exact: true })).toBeFocused()
  await expect(page.getByRole('textbox', { name: 'Name', exact: true })).toHaveValue('Blue card')
})

test('a long grid keeps the edited row, input and save controls visible; edge dragging reaches the final row and releases', async ({ page }) => {
  await page.goto('/#/playground')
  const grid = page.getByRole('grid', { name: 'Inventory items' })
  const first = grid.getByRole('gridcell', { name: 'Amber poster', exact: true })
  await first.dblclick()
  await expect(page.getByRole('textbox', { name: 'Name', exact: true })).toBeFocused()
  await expect(first).toBeInViewport()
  await expect(page.getByRole('textbox', { name: 'Name', exact: true })).toBeInViewport()
  await expect(page.getByRole('button', { name: 'Save changes', exact: true })).toBeInViewport()
  await page.getByRole('button', { name: 'Discard input', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Discard input', exact: true })).toHaveCount(0)
  const start = (await first.boundingBox())!
  const viewport = page.locator('.business-grid__workspace-viewport')
  const bounds = (await viewport.boundingBox())!
  await page.mouse.move(start.x + start.width / 2, start.y + start.height / 2)
  await page.mouse.down()
  await expect(grid.getByRole('gridcell', { selected: true })).toHaveText(['Amber poster'])
  await page.mouse.move(start.x + start.width / 2, bounds.y + bounds.height - 5, { steps: 10 })
  await expect(grid.getByRole('gridcell', { name: 'Jade booklet', exact: true })).toHaveAttribute('aria-selected', 'true')
  await page.mouse.up()
  await expect(grid.getByRole('gridcell', { selected: true })).toHaveCount(36)
  await page.mouse.move(start.x + start.width / 2, bounds.y + 40)
  await expect(grid.getByRole('gridcell', { selected: true })).toHaveCount(36)
  await grid.getByRole('gridcell', { name: 'Jade booklet', exact: true }).dblclick()
  await expect(page.getByRole('textbox', { name: 'Name', exact: true })).toHaveValue('Jade booklet')
  await expect(page.getByRole('textbox', { name: 'Name', exact: true })).toBeInViewport()
  await expect(grid.getByRole('gridcell', { name: 'Jade booklet', exact: true })).toBeInViewport()
})

test('pointer rectangles and Shift extension include both axes, and Cmd+A selects the complete grid', async ({ page }) => {
  await page.goto('/')
  const grid = page.getByRole('grid', { name: 'Quick-start products' })
  const start = (await grid.getByRole('gridcell', { name: 'Amber poster', exact: true }).boundingBox())!
  const end = (await grid.getByRole('gridcell', { name: '24', exact: true }).boundingBox())!
  await page.mouse.move(start.x + start.width / 2, start.y + start.height / 2)
  await page.mouse.down()
  await page.mouse.move(end.x + end.width / 2, end.y + end.height / 2)
  await page.mouse.up()
  const selected = grid.getByRole('gridcell', { selected: true })
  await expect(selected).toHaveText(['Amber poster', '12', 'Blue card', '24'])
  await grid.getByRole('gridcell', { name: '36', exact: true }).click({ modifiers: ['Shift'] })
  await expect(selected).toHaveText(['Amber poster', '12', 'Blue card', '24', 'Cedar label', '36'])
  await page.keyboard.press('Shift+ArrowLeft')
  await expect(selected).toHaveText(['Amber poster', 'Blue card', 'Cedar label'])
  await page.keyboard.press('Meta+a')
  await expect(selected).toHaveCount(12)
})
