import { expect, test } from './test.js'

test('dirty marker shows typed original value and restores through undo, save and reopening', async ({ page }) => {
  await page.goto('/')
  const grid = page.getByRole('grid', { name: 'Quick-start products' })
  await grid.getByRole('gridcell', { name: '12', exact: true }).dblclick()
  const input = page.getByRole('textbox', { name: 'Quantity', exact: true })
  await input.fill('45')
  await input.press('Enter')
  const changed = grid.getByRole('gridcell', { name: '45', exact: true })
  const marker = changed.getByRole('button', { name: 'Changed. Original value: 12', exact: true })
  await marker.hover()
  const details = page.getByRole('dialog', { name: 'Original value', exact: true })
  await expect(details.getByText('12', { exact: true })).toBeVisible()
  await marker.click()
  await marker.press('Enter')
  await expect(details.getByRole('button', { name: 'Restore original value', exact: true })).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(details).toHaveCount(0)
  await expect(marker).toBeFocused()
  await marker.press('Enter')
  await details.getByRole('button', { name: 'Restore original value', exact: true }).click()
  await expect(grid.getByRole('gridcell', { name: '12', exact: true })).toBeVisible()
  await expect(grid.getByRole('button', { name: /^Changed\. Original value:/ })).toHaveCount(0)
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(changed).toBeVisible()
  await expect(marker).toBeVisible()
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Refresh rows', exact: true })).toBeEnabled()
  await expect(marker).toHaveCount(0)
  await page.reload()
  await expect(changed).toBeVisible()
  await expect(grid.getByRole('button', { name: /^Changed\. Original value:/ })).toHaveCount(0)
})

test('restoring retains missing, null and numeric originals and recovers an unconfirmed write', async ({ page, context }) => {
  const { SourceFixture } = await import('../kernel/source-fixture.js')
  const { kernelId } = await import('../../src/kernel/model.js')
  const name = `dirty-values-${crypto.randomUUID()}`
  const source = new SourceFixture({ sourceId: name, id: kernelId<'scope'>('scope'), epoch: kernelId<'scope-epoch'>('epoch') }, {
    a: { value: 1, hidden: 'numeric' }, b: { hidden: 'missing' }, c: { value: null, hidden: 'null' }, d: { value: 'keep' },
  })
  await context.route('**/__kernel-source/*', async route => {
    const path = new URL(route.request().url()).pathname, body = route.request().postDataJSON()
    const result = path.endsWith('/read') ? await source.readAtLeast() : path.endsWith('/lookup') ? await source.lookupOperation(body) : await source.submit(body)
    await route.fulfill({ contentType: 'application/json', body: JSON.stringify(result) })
  })
  const mount = async (restore: boolean) => page.evaluate(async ({ name, restore }) => {
    await (await import('/src/test-fixtures/durable-workspace.ts')).startDurableWorkspace(name, restore)
    const container = document.createElement('div'); document.body.append(container)
    ;(await import('/src/test-fixtures/workspace-grid.tsx')).mountEditableWorkspaceGrid(container)
  }, { name, restore })
  await page.goto('/'); await mount(false)
  const grid = page.getByRole('grid', { name: 'Workspace rows' })
  const edit = async (value: string) => {
    await grid.getByRole('gridcell', { name: value, exact: true }).dblclick()
    const input = page.getByRole('textbox', { name: 'Edit value', exact: true })
    await input.fill('changed'); await input.press('Enter'); await expect(input).toHaveCount(0)
  }
  await edit('1')
  await grid.getByRole('button', { name: 'Changed. Original value: 1', exact: true }).click()
  await page.evaluate(async () => (await import('/src/test-fixtures/durable-workspace.ts')).loseNextWorkspaceAcknowledgement())
  await page.getByRole('button', { name: 'Restore original value', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Check pending results', exact: true })).toBeVisible()
  await expect(grid.getByRole('gridcell', { name: 'changed', exact: true })).toBeVisible()
  await page.reload(); await mount(true)
  // The durable root already contains this accepted local write. Reopening
  // resolves it from storage; there is no external operation left to query.
  await expect(grid.getByRole('gridcell', { name: '1', exact: true })).toBeVisible()
  for (const value of ['(missing)', 'null']) {
    await edit(value)
    await grid.getByRole('button', { name: /^Changed\. Original value:/ }).click()
    await page.getByRole('button', { name: 'Restore original value', exact: true }).click()
    await expect(grid.getByRole('gridcell', { name: value, exact: true })).toBeVisible()
  }
  await edit('keep')
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect.poll(() => source.writes).toBe(1)
  await expect(page.getByRole('button', { name: 'Refresh rows', exact: true })).toBeEnabled()
  expect(source.snapshot().rows.map(row => row.document)).toEqual([
    { value: 1, hidden: 'numeric' }, { hidden: 'missing' }, { value: null, hidden: 'null' }, { value: 'changed' },
  ])
  await page.reload(); await mount(true)
  await expect(grid.getByRole('gridcell')).toHaveText(['1', '(missing)', 'null', 'changed'])
  await expect(grid.getByRole('button', { name: /^Changed\. Original value:/ })).toHaveCount(0)
})

test('context-menu restore respects disjoint selection and undo restores the whole action', async ({ page }) => {
  await page.goto('/')
  const grid = page.getByRole('grid', { name: 'Quick-start products' })
  for (const [before, after] of [['Amber poster', 'Local amber'], ['Blue card', 'Local blue'], ['Cedar label', 'Local cedar']]) {
    await grid.getByRole('gridcell', { name: before, exact: true }).dblclick()
    const input = page.getByRole('textbox', { name: 'Name', exact: true })
    await input.fill(after!); await input.press('Enter'); await expect(input).toHaveCount(0)
  }
  await grid.getByRole('gridcell', { name: 'Local amber', exact: true }).click()
  await grid.getByRole('gridcell', { name: 'Local cedar', exact: true }).click({ modifiers: ['Control'] })
  await expect(grid.getByRole('gridcell', { selected: true })).toHaveCount(2)
  await grid.getByRole('gridcell', { name: 'Local amber', exact: true }).click({ button: 'right' })
  await page.getByRole('menuitem', { name: 'Restore selected cells', exact: true }).click()
  await expect(grid.getByRole('gridcell', { name: 'Amber poster', exact: true })).toBeVisible()
  await expect(grid.getByRole('gridcell', { name: 'Cedar label', exact: true })).toBeVisible()
  await expect(grid.getByRole('gridcell', { name: 'Local blue', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(grid.getByRole('gridcell', { name: 'Local amber', exact: true })).toBeVisible()
  await expect(grid.getByRole('gridcell', { name: 'Local cedar', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Redo', exact: true }).click()
  await expect(grid.getByRole('gridcell', { name: 'Amber poster', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Refresh rows', exact: true })).toBeEnabled()
  await expect(page.getByRole('button', { name: 'Save changes', exact: true })).toBeDisabled()
  await page.reload()
  await expect(grid.getByRole('gridcell', { name: 'Amber poster', exact: true })).toBeVisible()
  await expect(grid.getByRole('gridcell', { name: 'Cedar label', exact: true })).toBeVisible()
  await expect(grid.getByRole('gridcell', { name: 'Local blue', exact: true })).toBeVisible()
})

test('row restore includes all fields and original position; restoring a new row is undoable removal', async ({ page }) => {
  await page.goto('/#/playground')
  const grid = page.getByRole('grid', { name: 'Inventory items' })
  const automatic = page.getByRole('switch', { name: 'Auto-save', exact: true })
  await automatic.click(); await expect(automatic).not.toBeChecked()
  await grid.getByRole('gridcell', { name: 'Amber poster', exact: true }).dblclick()
  await page.getByRole('textbox', { name: 'Name', exact: true }).fill('Local amber')
  await page.keyboard.press('Enter')
  const row = grid.getByRole('row').filter({ has: page.getByRole('gridcell', { name: 'Local amber', exact: true }) })
  await row.getByRole('gridcell', { name: '12', exact: true }).dblclick()
  await page.getByRole('textbox', { name: 'Quantity', exact: true }).fill('45')
  await page.keyboard.press('Enter')
  await expect(page.getByRole('textbox', { name: 'Quantity', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Move row down', exact: true }).click()
  await expect(grid.getByRole('row').nth(2)).toContainText('Local amber')
  await grid.getByRole('gridcell', { name: 'Local amber', exact: true }).click({ button: 'right' })
  await page.getByRole('menuitem', { name: 'Restore original row', exact: true }).click()
  await expect(grid.getByRole('row').nth(1)).toContainText('Amber poster')
  await expect(grid.getByRole('row').nth(1).getByRole('gridcell', { name: '12', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(grid.getByRole('row').nth(2)).toContainText('Local amber')
  await expect(row.getByRole('gridcell', { name: '45', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Redo', exact: true }).click()
  await expect(grid.getByRole('row').nth(1)).toContainText('Amber poster')
  await page.getByRole('button', { name: 'Duplicate row', exact: true }).click()
  const copy = grid.getByRole('gridcell', { name: 'Amber poster copy', exact: true })
  await copy.click({ button: 'right' })
  await page.getByRole('menuitem', { name: 'Restore original row', exact: true }).click()
  await expect(copy).toHaveCount(0)
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(copy).toBeVisible()
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(page.getByText('1 saves', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Refresh rows', exact: true })).toBeEnabled()
  await page.reload()
  await expect(copy).toBeVisible()
  await expect(grid.getByRole('row').nth(1)).toContainText('Amber poster')
  await expect(grid.getByRole('row').nth(1).getByRole('gridcell', { name: '12', exact: true })).toBeVisible()
})
