import { SourceFixture } from '../kernel/source-fixture.js'
import { kernelId, type ViewId } from '../../src/kernel/model.js'
import { expect, test } from './test.js'

test('text conditions match the old case-insensitive all/any flow and survive reopening', async ({ page }) => {
  await page.goto('/')
  const grid = page.getByRole('grid', { name: 'Quick-start products' })
  await grid.getByRole('button', { name: 'Filter Name', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Filter Name', exact: true })
  await dialog.getByRole('textbox', { name: 'Name filter', exact: true }).fill('AMBER')
  await dialog.getByRole('button', { name: 'Add condition', exact: true }).click()
  await dialog.getByRole('combobox', { name: 'Condition 2', exact: true }).selectOption('equals')
  await dialog.getByRole('textbox', { name: 'Name filter 2', exact: true }).fill('blue card')
  await dialog.getByRole('combobox', { name: 'Match', exact: true }).selectOption('any')
  await dialog.getByRole('button', { name: 'Apply filter', exact: true }).click()
  await expect(grid.getByRole('gridcell', { name: 'Amber poster', exact: true })).toBeVisible()
  await expect(grid.getByRole('gridcell', { name: 'Blue card', exact: true })).toBeVisible()
  await expect(grid.getByRole('gridcell', { name: 'Cedar label', exact: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Save changes', exact: true })).toBeDisabled()
  await page.reload()
  await expect(grid.getByRole('gridcell')).toHaveCount(8)
  await grid.getByRole('button', { name: 'Filter Name', exact: true }).click()
  await expect(dialog.getByRole('combobox', { name: 'Match', exact: true })).toHaveValue('any')
  await expect(dialog.getByRole('textbox', { name: 'Name filter', exact: true })).toHaveValue('AMBER')
  await expect(dialog.getByRole('textbox', { name: 'Name filter 2', exact: true })).toHaveValue('blue card')
  await dialog.getByRole('combobox', { name: 'Match', exact: true }).selectOption('all')
  await dialog.getByRole('button', { name: 'Apply filter', exact: true }).click()
  await expect(grid.getByRole('gridcell')).toHaveCount(0)
  await grid.getByRole('button', { name: 'Filter Name', exact: true }).click()
  await dialog.getByRole('button', { name: 'Clear filter', exact: true }).click()
  await expect(grid.getByRole('gridcell')).toHaveCount(12)
})

test('numeric validation preserves the prior query, and clearing one column keeps the others', async ({ page }) => {
  await page.goto('/')
  const grid = page.getByRole('grid', { name: 'Quick-start products' })
  await grid.getByRole('button', { name: 'Filter Quantity', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Filter Quantity', exact: true })
  await dialog.getByRole('combobox', { name: 'Condition 1', exact: true }).selectOption('greater-than-or-equal')
  await dialog.getByRole('textbox', { name: 'Quantity filter', exact: true }).fill('24')
  await dialog.getByRole('button', { name: 'Add condition', exact: true }).click()
  await dialog.getByRole('combobox', { name: 'Condition 2', exact: true }).selectOption('less-than')
  await dialog.getByRole('textbox', { name: 'Quantity filter 2', exact: true }).fill('invalid')
  await dialog.getByRole('button', { name: 'Apply filter', exact: true }).click()
  await expect(dialog.getByRole('alert')).toHaveText('Enter a valid number.')
  await expect(grid.getByRole('gridcell')).toHaveCount(12)
  await dialog.getByRole('textbox', { name: 'Quantity filter 2', exact: true }).fill('40')
  await dialog.getByRole('button', { name: 'Apply filter', exact: true }).click()
  await expect(grid.getByRole('gridcell')).toHaveCount(8)
  await grid.getByRole('button', { name: 'Filter Active', exact: true }).click()
  await page.getByRole('combobox', { name: 'Active filter', exact: true }).selectOption('false')
  await page.getByRole('button', { name: 'Apply filter', exact: true }).click()
  await expect(grid.getByRole('gridcell')).toHaveCount(4)
  await expect(grid.getByRole('gridcell', { name: 'Blue card', exact: true })).toBeVisible()
  await grid.getByRole('button', { name: 'Filter Active', exact: true }).click()
  await page.getByRole('button', { name: 'Clear filter', exact: true }).click()
  await expect(grid.getByRole('gridcell')).toHaveCount(8)
  await grid.getByRole('button', { name: 'Filter Quantity', exact: true }).click()
  await expect(dialog.getByRole('combobox', { name: 'Condition 1', exact: true })).toHaveValue('greater-than-or-equal')
  await dialog.getByRole('button', { name: 'Clear filter', exact: true }).click()
  await expect(grid.getByRole('gridcell')).toHaveCount(12)
})

test('tag membership and date conditions use their field catalogs and calendar values', async ({ page }) => {
  await page.goto('/#/playground')
  const grid = page.getByRole('grid', { name: 'Inventory items' })
  await grid.getByRole('button', { name: 'Filter Tags', exact: true }).click()
  await page.getByRole('combobox', { name: 'Tags filter', exact: true }).selectOption({ label: 'Featured' })
  await page.getByRole('button', { name: 'Apply filter', exact: true }).click()
  await expect(grid.getByRole('gridcell', { name: 'Amber poster', exact: true })).toBeVisible()
  await expect(grid.getByRole('gridcell', { name: 'Blue card', exact: true })).toHaveCount(0)
  await grid.getByRole('button', { name: 'Filter Tags', exact: true }).click()
  await page.getByRole('button', { name: 'Add condition', exact: true }).click()
  await page.getByRole('combobox', { name: 'Condition 2', exact: true }).selectOption('not-contains')
  await page.getByRole('combobox', { name: 'Tags filter 2', exact: true }).selectOption({ label: 'Wholesale' })
  await page.getByRole('button', { name: 'Apply filter', exact: true }).click()
  await expect(grid.getByRole('gridcell', { name: 'Amber poster', exact: true })).toHaveCount(0)
  await expect(grid.getByRole('gridcell', { name: 'Dune notebook', exact: true })).toBeVisible()
  await grid.getByRole('button', { name: 'Filter Tags', exact: true }).click()
  await page.getByRole('button', { name: 'Clear filter', exact: true }).click()
  await grid.getByRole('button', { name: 'Filter Delivery date', exact: true }).click()
  await page.getByRole('combobox', { name: 'Condition 1', exact: true }).selectOption('before')
  await page.getByLabel('Delivery date filter', { exact: true }).and(page.locator('input')).fill('2026-09-10')
  await page.getByRole('button', { name: 'Apply filter', exact: true }).click()
  await expect(grid.locator('[data-column-key="name"]')).toHaveText(['Amber poster', 'Blue card', 'Cedar label'])
  await expect(grid.getByRole('gridcell', { name: 'Cedar label', exact: true })).toBeVisible()
  await expect(grid.getByRole('gridcell', { name: 'Dune notebook', exact: true })).toHaveCount(0)
})

test('uncertain condition input survives reload and applies only after the editor resumes', async ({ page, context }) => {
  const name = `standard-filter-input-${crypto.randomUUID()}`
  const source = new SourceFixture({ sourceId: name, id: kernelId<'scope'>('scope'), epoch: kernelId<'scope-epoch'>('epoch') }, { a: { value: 1 }, b: { value: 5 }, c: { value: 10 } })
  await context.route('**/__kernel-source/*', async route => {
    const path = new URL(route.request().url()).pathname, body = route.request().postDataJSON()
    const result = path.endsWith('/read') ? await source.readAtLeast() : path.endsWith('/lookup') ? await source.lookupOperation(body) : await source.submit(body)
    await route.fulfill({ contentType: 'application/json', body: JSON.stringify(result) })
  })
  const mount = async (restore: boolean) => page.evaluate(async ({ name, restore }) => {
    await (await import('/src/test-fixtures/durable-workspace.ts')).startDurableWorkspace(name, restore)
    const container = document.createElement('div'); document.body.append(container)
    ;(await import('/src/test-fixtures/workspace-grid.tsx')).mountStandardFilterWorkspaceGrid(container)
  }, { name, restore })
  await page.goto('/')
  await mount(false)
  const grid = page.getByRole('grid', { name: 'Workspace rows' })
  await grid.getByRole('button', { name: 'Filter Value', exact: true }).click()
  await page.getByRole('combobox', { name: 'Condition 1', exact: true }).selectOption('greater-than-or-equal')
  await page.getByRole('textbox', { name: 'Value filter', exact: true }).fill('5')
  await page.getByRole('button', { name: 'Add condition', exact: true }).click()
  await page.getByRole('combobox', { name: 'Condition 2', exact: true }).selectOption('less-than')
  await expect(page.getByRole('button', { name: 'Apply filter', exact: true })).toBeEnabled()
  await page.evaluate(async () => {
    const fixture = await import('/src/test-fixtures/durable-workspace.ts')
    const input = fixture.workspaceForReactFixture().getState().session!.rawInput
    if (input.kind !== 'encoded' || typeof input.value !== 'string') throw new Error('Expected retained filter conditions')
    const draft = JSON.parse(input.value)
    draft.conditions[1].value = '10'
    // Firefox may emit an earlier composition-start input. Inject the loss at
    // the final full draft, whose acknowledgement/recovery this test checks.
    fixture.loseNextWorkspaceAcknowledgement(JSON.stringify(draft))
  })
  await page.getByRole('textbox', { name: 'Value filter 2', exact: true }).fill('10')
  await expect(page.getByRole('button', { name: 'Apply filter', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: 'Review grid', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Check pending results', exact: true })).toBeVisible()
  await page.reload()
  await mount(true)
  await page.getByRole('button', { name: 'Resume filter editing', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Value filter', exact: true })).toHaveValue('5')
  await expect(page.getByRole('textbox', { name: 'Value filter 2', exact: true })).toHaveValue('10')
  await expect(page.getByRole('combobox', { name: 'Condition 2', exact: true })).toHaveValue('less-than')
  await expect(grid.getByRole('gridcell')).toHaveText(['1', '5', '10'])
  await page.getByRole('button', { name: 'Apply filter', exact: true }).click()
  await expect(grid.getByRole('gridcell')).toHaveText(['5'])
  expect(source.writes).toBe(0)
  await page.reload()
  await mount(true)
  await expect(grid.getByRole('gridcell')).toHaveText(['5'])
  await page.evaluate(async () => {
    const workspace = (await import('/src/test-fixtures/durable-workspace.ts')).workspaceForReactFixture()
    await workspace.dispatch({ kind: 'view-query-set', viewId: 'grid-editor' as ViewId, expectedVersion: workspace.getView('grid-editor' as ViewId).query.version,
      filters: [{ columnId: 'value-column', predicate: { kind: 'any', predicates: [] } }], sort: [] })
  })
  await expect(grid.getByRole('gridcell')).toHaveCount(0)
  await grid.getByRole('button', { name: 'Filter Value', exact: true }).click()
  await expect(page.getByRole('alert')).toHaveText('This filter input needs a different editor.')
  await expect(page.getByRole('button', { name: 'Apply filter', exact: true })).toBeDisabled()
  await expect(grid.getByRole('gridcell')).toHaveCount(0)
  await page.getByRole('button', { name: 'Clear filter', exact: true }).click()
  await expect(grid.getByRole('gridcell')).toHaveText(['1', '5', '10'])
  expect(source.writes).toBe(0)
})

test('each cross-grid view keeps its own filter and sort through reload', async ({ page }) => {
  await page.goto('/#/cross-grid-drag')
  const left = page.getByRole('grid', { name: 'Left inventory' }), right = page.getByRole('grid', { name: 'Right inventory' })
  const leftNames = left.locator('[data-column-key="name"]'), rightNames = right.locator('[data-column-key="name"]')
  await expect(leftNames).not.toHaveCount(0)
  await expect(rightNames).not.toHaveCount(0)
  const originalRight = await rightNames.allTextContents(), originalLeft = await leftNames.allTextContents()
  await left.getByRole('button', { name: 'Filter Name', exact: true }).click()
  await page.getByRole('textbox', { name: 'Name filter', exact: true }).fill(originalLeft[0]!)
  // Leave the draft retained while another view changes its query.
  await page.getByRole('button', { name: 'Review grid', exact: true }).click()
  await right.getByRole('button', { name: 'Sort Quantity', exact: true }).click()
  await right.getByRole('button', { name: 'Sort Quantity', exact: true }).click()
  await expect(right.getByRole('columnheader', { name: 'Quantity', exact: true })).toHaveAttribute('aria-sort', 'descending')
  await expect(left.getByRole('columnheader', { name: 'Quantity', exact: true })).not.toHaveAttribute('aria-sort')
  await page.getByRole('button', { name: 'Apply filter', exact: true }).click()
  await expect(leftNames).toHaveText([originalLeft[0]!])
  await expect(rightNames).toHaveCount(originalRight.length)
  const sortedRight = await rightNames.allTextContents()
  await page.reload()
  await expect(leftNames).toHaveText([originalLeft[0]!])
  await expect(rightNames).toHaveText(sortedRight)
  await expect(right.getByRole('columnheader', { name: 'Quantity', exact: true })).toHaveAttribute('aria-sort', 'descending')
  await left.getByRole('button', { name: 'Filter Name', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Name filter', exact: true })).toHaveValue(originalLeft[0]!)
  await page.getByRole('button', { name: 'Clear filter', exact: true }).click()
  await expect(leftNames).toHaveText(originalLeft)
  await expect(rightNames).toHaveText(sortedRight)
})
