import { expect, test } from './test.js'

test('Ctrl/Cmd additional ranges preserve holes through bulk authoring, save and reload', async ({ page }) => {
  await page.goto('/')
  const grid = page.getByRole('grid', { name: 'Quick-start products' })
  await grid.getByRole('gridcell', { name: 'Amber poster', exact: true }).click()
  await grid.getByRole('gridcell', { name: 'Cedar label', exact: true }).click({ modifiers: ['Control'] })
  await expect(grid.getByRole('gridcell', { selected: true })).toHaveText(['Amber poster', 'Cedar label'])
  await grid.getByRole('gridcell', { name: '36', exact: true }).click({ modifiers: ['Meta'] })
  await expect(grid.getByRole('gridcell', { selected: true })).toHaveText(['Amber poster', 'Cedar label', '36'])
  await page.getByRole('button', { name: 'Edit selection…', exact: true }).click()
  await page.getByRole('textbox').fill('7')
  await page.getByRole('button', { name: 'Apply to 3 cells', exact: true }).click()
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Refresh rows', exact: true })).toBeEnabled()
  await expect(page.getByRole('button', { name: 'Save changes', exact: true })).toBeDisabled()
  await page.reload()
  await expect(grid.getByRole('gridcell', { name: '7', exact: true })).toHaveCount(3)
  await expect(grid.getByRole('gridcell', { name: 'Blue card', exact: true })).toBeVisible()
  await expect(grid.getByRole('gridcell', { name: '24', exact: true })).toBeVisible()
  await expect(grid.getByRole('gridcell', { name: '12', exact: true })).toBeVisible()
})

test('row/column/corner selection and history shortcuts address the same workspace', async ({ page }) => {
  await page.goto('/')
  const grid = page.getByRole('grid', { name: 'Quick-start products' })
  await grid.getByRole('button', { name: 'Select row 1', exact: true }).click()
  await grid.getByRole('button', { name: 'Select row 3', exact: true }).click({ modifiers: ['Control'] })
  await expect(grid.getByRole('gridcell', { selected: true })).toHaveCount(8)
  await grid.getByRole('button', { name: 'Select column Quantity', exact: true }).click()
  await expect(grid.getByRole('gridcell', { selected: true })).toHaveText(['12', '24', '36'])
  await grid.getByRole('button', { name: 'Select all cells', exact: true }).click()
  await expect(grid.getByRole('gridcell', { selected: true })).toHaveCount(12)
  const cell = grid.getByRole('gridcell', { name: 'Amber poster', exact: true })
  await cell.dblclick()
  await page.getByRole('textbox', { name: 'Name', exact: true }).fill('Changed')
  await page.getByRole('button', { name: 'Apply value', exact: true }).click()
  await grid.getByRole('gridcell', { name: 'Changed', exact: true }).press('Control+z')
  await expect(cell).toBeVisible()
  await cell.press('Control+Shift+z')
  await expect(grid.getByRole('gridcell', { name: 'Changed', exact: true })).toBeVisible()
  await grid.getByRole('gridcell', { name: 'Changed', exact: true }).press('Meta+z')
  await expect(cell).toBeVisible()
  await cell.press('Control+y')
  await expect(grid.getByRole('gridcell', { name: 'Changed', exact: true })).toBeVisible()
})

test('in-cell keyboard editing validates, commits with Tab, cancels with Escape, and retains rapid typing', async ({ page }) => {
  await page.goto('/')
  const grid = page.getByRole('grid', { name: 'Quick-start products' })
  const quantity = grid.getByRole('gridcell', { name: '12', exact: true })
  await quantity.dblclick()
  const input = page.getByRole('textbox', { name: 'Quantity', exact: true })
  await expect(input).toBeFocused()
  await expect(page.getByRole('button', { name: 'Apply value', exact: true })).toBeEnabled()
  const cellBox = await quantity.boundingBox(), editorBox = await input.boundingBox()
  expect(Math.abs(cellBox!.x - editorBox!.x)).toBeLessThan(3)
  expect(Math.abs(cellBox!.y - editorBox!.y)).toBeLessThan(3)
  await input.fill('invalid')
  await input.press('Enter')
  await expect(input).toHaveAttribute('aria-invalid', 'true')
  await expect(input).toHaveValue('invalid')
  await input.fill('45')
  await input.press('Tab')
  await expect(input).toHaveCount(0)
  await expect(grid.getByRole('gridcell', { name: '45', exact: true })).toBeVisible()
  await expect(grid.getByRole('gridcell', { name: 'Ready', exact: true }).first()).toBeFocused()
  const name = grid.getByRole('gridcell', { name: 'Amber poster', exact: true })
  await name.click()
  await page.keyboard.type('Rapid replacement')
  await page.keyboard.press('Enter')
  await expect(grid.getByRole('gridcell', { name: 'Rapid replacement', exact: true })).toBeVisible()
  await grid.getByRole('gridcell', { name: 'Rapid replacement', exact: true }).press('F2')
  await page.getByRole('textbox', { name: 'Name', exact: true }).fill('Cancelled')
  await page.keyboard.press('Escape')
  await expect(page.getByRole('textbox', { name: 'Name', exact: true })).toHaveCount(0)
  await expect(grid.getByRole('gridcell', { name: 'Rapid replacement', exact: true })).toBeFocused()
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Save changes', exact: true })).toBeDisabled()
  await page.reload()
  await expect(grid.getByRole('gridcell', { name: 'Rapid replacement', exact: true })).toBeVisible()
  await expect(grid.getByRole('gridcell', { name: '45', exact: true })).toBeVisible()
})

test('commit navigation follows the newly sorted view and safely finishes when filtering removes its last row', async ({ page }) => {
  await page.goto('/')
  const grid = page.getByRole('grid', { name: 'Quick-start products' })
  await grid.getByRole('button', { name: 'Sort Name', exact: true }).click()
  await expect(grid.getByRole('columnheader', { name: 'Name', exact: true })).toHaveAttribute('aria-sort', 'ascending')
  await grid.getByRole('gridcell', { name: 'Blue card', exact: true }).dblclick()
  const input = page.getByRole('textbox', { name: 'Name', exact: true })
  await input.fill('Aardvark')
  await input.press('Shift+Tab')
  await expect(input).toHaveCount(0)
  await expect(grid.getByRole('gridcell', { name: 'Aardvark', exact: true })).toBeFocused()
  await page.getByRole('searchbox', { name: 'Filter rows', exact: true }).fill('Aardvark')
  await expect(grid.getByRole('gridcell')).toHaveCount(4)
  await grid.getByRole('gridcell', { name: 'Aardvark', exact: true }).dblclick()
  await input.fill('Zebra')
  await input.press('Tab')
  await expect(input).toHaveCount(0)
  await expect(grid.getByRole('gridcell')).toHaveCount(0)
  await page.getByRole('searchbox', { name: 'Filter rows', exact: true }).fill('')
  await expect(grid.getByRole('gridcell', { name: 'Zebra', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Refresh rows', exact: true })).toBeEnabled()
  await expect(page.getByRole('button', { name: 'Save changes', exact: true })).toBeDisabled()
  await page.reload()
  await expect(grid.getByRole('gridcell', { name: 'Zebra', exact: true })).toBeVisible()
  await expect(grid.getByRole('gridcell', { name: 'Blue card', exact: true })).toHaveCount(0)
})

test('boolean cells toggle directly and choice popovers keep their own catalog and commit behavior', async ({ page }) => {
  await page.goto('/')
  const grid = page.getByRole('grid', { name: 'Quick-start products' })
  const active = grid.locator('[data-column-key="active"][data-grid-row-index="0"]')
  await active.getByRole('checkbox', { name: 'True' }).click()
  await expect(active.getByRole('checkbox', { name: 'False' })).not.toBeChecked()
  const status = grid.locator('[data-column-key="status"][data-grid-row-index="0"]')
  await status.dblclick()
  await page.getByRole('listbox', { name: 'Choose value' }).getByRole('option', { name: 'Draft', exact: true }).click()
  await expect(status).toHaveText('Draft')
  await expect(page.getByRole('listbox', { name: 'Choose value' })).toHaveCount(0)
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Save changes', exact: true })).toBeDisabled()
  await page.reload()
  await expect(active.getByRole('checkbox', { name: 'False' })).not.toBeChecked()
  await expect(status).toHaveText('Draft')
  await page.goto('/#/playground')
  const tags = page.getByRole('grid', { name: 'Inventory items' }).locator('[data-column-key="tags"][data-grid-row-index="0"]')
  await tags.dblclick()
  const choices = page.getByRole('group', { name: 'Choose values' })
  await expect(choices.getByLabel('Featured')).toBeChecked()
  await expect(choices.getByLabel('Draft')).toHaveCount(0)
  await choices.getByLabel('Featured').uncheck()
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(tags).toContainText('Featured')
  await tags.dblclick()
  await choices.getByLabel('Featured').uncheck()
  await page.getByRole('button', { name: 'Apply', exact: true }).click()
  await expect(tags).not.toContainText('Featured')
})

test('column filters and bulk dialogs restore focus, and retained replace parameters survive reload', async ({ page }) => {
  await page.goto('/#/playground')
  const grid = page.getByRole('grid', { name: 'Inventory items' })
  const filter = grid.getByRole('button', { name: 'Filter Name', exact: true })
  await filter.click()
  const dialog = page.getByRole('dialog', { name: 'Filter Name', exact: true })
  await expect(dialog).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(dialog).toHaveCount(0)
  await expect(filter).toBeFocused()
  await filter.click()
  await page.getByRole('textbox', { name: 'Name filter', exact: true }).fill('Amber')
  await page.getByRole('button', { name: 'Apply filter', exact: true }).click()
  await expect(grid.getByRole('gridcell', { name: 'Amber poster', exact: true })).toBeVisible()
  await expect(grid.getByRole('row')).toHaveCount(2)
  await page.goto('/')
  const products = page.getByRole('grid', { name: 'Quick-start products' })
  await products.getByRole('button', { name: 'Select column Name', exact: true }).click()
  await page.getByRole('button', { name: 'Edit selection…', exact: true }).click()
  const bulk = page.getByRole('dialog', { name: 'Edit 3 selected cells' })
  await bulk.getByLabel('Operation').selectOption('replace')
  await bulk.getByLabel('Find', { exact: true }).fill('[')
  await bulk.getByLabel('Regular expression').check()
  await bulk.getByRole('button', { name: 'Apply to 3 cells' }).click()
  await expect(bulk.getByRole('alert')).toHaveText('Enter a valid regular expression.')
  await bulk.getByLabel('Find', { exact: true }).fill('^(.*)$')
  await bulk.getByLabel('Replace with').fill('New $1')
  await expect(bulk.getByRole('button', { name: 'Apply to 3 cells' })).toBeEnabled()
  await page.reload()
  await page.getByRole('button', { name: 'Resume editing', exact: true }).click()
  await expect(bulk.getByLabel('Find', { exact: true })).toHaveValue('^(.*)$')
  await expect(bulk.getByLabel('Replace with')).toHaveValue('New $1')
  await bulk.getByRole('button', { name: 'Apply to 3 cells' }).click()
  await expect(products.getByRole('gridcell', { name: 'New Amber poster', exact: true })).toBeVisible()
  await expect(products.getByRole('gridcell', { name: 'New Blue card', exact: true })).toBeVisible()
  await expect(products.getByRole('gridcell', { name: 'New Cedar label', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Save changes', exact: true })).toBeDisabled()
  await page.reload()
  await expect(products.getByRole('gridcell', { name: 'New Blue card', exact: true })).toBeVisible()
})

test('dragging headers selects full rows and columns, and resizing leaves editing anchored', async ({ page }) => {
  await page.goto('/')
  const grid = page.getByRole('grid', { name: 'Quick-start products' })
  async function drag(from: import('@playwright/test').Locator, to: import('@playwright/test').Locator) {
    const start = (await from.boundingBox())!, end = (await to.boundingBox())!
    await page.mouse.move(start.x + start.width / 2, start.y + start.height / 2)
    await page.mouse.down()
    await page.mouse.move(end.x + end.width / 2, end.y + end.height / 2, { steps: 6 })
    await page.mouse.up()
  }
  await drag(grid.getByRole('button', { name: 'Select column Name', exact: true }), grid.getByRole('button', { name: 'Select column Quantity', exact: true }))
  await expect(grid.getByRole('gridcell', { selected: true })).toHaveCount(6)
  await drag(grid.getByRole('button', { name: 'Select row 1', exact: true }), grid.getByRole('button', { name: 'Select row 3', exact: true }))
  await expect(grid.getByRole('gridcell', { selected: true })).toHaveCount(12)
  const resize = grid.getByRole('separator', { name: 'Resize Name', exact: true })
  const before = (await grid.getByRole('columnheader', { name: 'Name', exact: true }).boundingBox())!
  const handle = (await resize.boundingBox())!
  await page.mouse.move(handle.x + handle.width / 2, handle.y + handle.height / 2)
  await page.mouse.down(); await page.mouse.move(handle.x + handle.width / 2 + 80, handle.y + handle.height / 2); await page.mouse.up()
  await expect(resize).toHaveAttribute('aria-valuenow', '240')
  expect((await grid.getByRole('columnheader', { name: 'Name', exact: true }).boundingBox())!.width).toBeCloseTo(before.width + 80, 0)
  await grid.getByRole('gridcell', { name: '24', exact: true }).press('Shift+Tab')
  await expect(grid.getByRole('gridcell', { name: 'Blue card', exact: true })).toBeFocused()
  await expect(grid.getByRole('gridcell', { selected: true })).toHaveText(['Blue card'])
  const handleAfter = (await resize.boundingBox())!
  await page.mouse.move(handleAfter.x + handleAfter.width / 2, handleAfter.y + handleAfter.height / 2)
  await page.mouse.down()
  await page.evaluate(() => window.dispatchEvent(new Event('blur')))
  await page.mouse.move(handleAfter.x + 100, handleAfter.y + handleAfter.height / 2)
  await page.mouse.up()
  await expect(resize).toHaveAttribute('aria-valuenow', '240')
  await grid.getByRole('gridcell', { name: 'Amber poster', exact: true }).dblclick()
  await expect(page.getByRole('button', { name: 'Apply value', exact: true })).toBeEnabled()
  const cell = (await grid.getByRole('gridcell', { name: 'Amber poster', exact: true }).boundingBox())!
  const editor = (await page.getByRole('textbox', { name: 'Name', exact: true }).boundingBox())!
  expect(Math.abs(editor.width - cell.width)).toBeLessThan(3)
  expect(Math.abs(editor.y - cell.y)).toBeLessThan(3)
})

test('pasting expands from the active cell and commits the complete matrix; invalid input remains recoverable', async ({ page }) => {
  await page.goto('/')
  const grid = page.getByRole('grid', { name: 'Quick-start products' })
  const origin = grid.getByRole('gridcell', { name: 'Amber poster', exact: true })
  await origin.click()
  await page.evaluate(() => { const source = document.createElement('textarea'); source.setAttribute('aria-label', 'Clipboard source'); document.body.append(source) })
  const clipboard = page.getByRole('textbox', { name: 'Clipboard source', exact: true })
  await clipboard.fill('Pasted one\t41\nPasted two\t42')
  await clipboard.press('Control+a'); await clipboard.press('Control+c')
  await origin.focus(); await origin.press('Control+v')
  await clipboard.evaluate(element => element.remove())
  await expect(grid.getByRole('gridcell', { name: 'Pasted one', exact: true })).toBeVisible()
  await expect(grid.getByRole('gridcell', { name: '41', exact: true })).toBeVisible()
  await expect(grid.getByRole('gridcell', { name: 'Pasted two', exact: true })).toBeVisible()
  await expect(grid.getByRole('gridcell', { name: '42', exact: true })).toBeVisible()
  await expect(grid.getByRole('gridcell', { name: 'Cedar label', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Save changes', exact: true })).toBeDisabled()
  await page.reload()
  const pasted = grid.getByRole('gridcell', { name: 'Pasted one', exact: true })
  await expect(pasted).toBeVisible()
  await pasted.evaluate(element => {
    const event = new ClipboardEvent('paste', { bubbles: true, cancelable: true, clipboardData: new DataTransfer() })
    event.clipboardData!.setData('text/plain', 'Must not partially apply\tinvalid')
    element.dispatchEvent(event)
    if (!event.defaultPrevented) throw new Error('The paste event was not handled.')
  })
  await expect(page.getByRole('alert')).toContainText('Enter a non-negative whole number.')
  await expect(pasted).toBeVisible()
  await expect(page.getByRole('textbox')).toHaveValue('Must not partially apply\tinvalid')
  await page.reload()
  await page.getByRole('button', { name: 'Resume editing', exact: true }).click()
  await expect(page.getByRole('textbox')).toHaveValue('Must not partially apply\tinvalid')
  await expect(pasted).toBeVisible()
})

test('changing cells commits valid scalar input and keeps invalid input at its original target', async ({ page }) => {
  await page.goto('/')
  const grid = page.getByRole('grid', { name: 'Quick-start products' })
  const quantity = grid.getByRole('gridcell', { name: '12', exact: true })
  const next = grid.getByRole('gridcell', { name: 'Blue card', exact: true })
  await quantity.dblclick()
  const input = page.getByRole('textbox', { name: 'Quantity', exact: true })
  await input.fill('invalid')
  await next.click()
  await expect(input).toHaveValue('invalid')
  await expect(input).toHaveAttribute('aria-invalid', 'true')
  await expect(input).toBeFocused()
  await expect(quantity).toHaveAttribute('aria-selected', 'true')
  await expect(next).toHaveAttribute('aria-selected', 'false')
  for (const name of ['Select column Name', 'Select row 2', 'Select all cells']) {
    await grid.getByRole('button', { name, exact: true }).click()
    await expect(input).toBeFocused()
    await expect(grid.getByRole('gridcell', { selected: true })).toHaveCount(1)
    await expect(quantity).toHaveAttribute('aria-selected', 'true')
  }
  await input.fill('43')
  await next.click()
  await expect(input).toHaveCount(0)
  await expect(grid.getByRole('gridcell', { name: '43', exact: true })).toBeVisible()
  await expect(next).toBeFocused()
  await expect(next).toHaveAttribute('aria-selected', 'true')
  await next.press('F2')
  await page.getByRole('textbox', { name: 'Name', exact: true }).fill('Next product')
  await grid.getByRole('gridcell', { name: 'Cedar label', exact: true }).click()
  await expect(grid.getByRole('gridcell', { name: 'Next product', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Save changes', exact: true })).toBeDisabled()
  await page.reload()
  await expect(grid.getByRole('gridcell', { name: '43', exact: true })).toBeVisible()
  await expect(grid.getByRole('gridcell', { name: 'Next product', exact: true })).toBeVisible()
})
