import { readFile } from 'node:fs/promises'
import { expect, test } from './test.js'
const files = ['one', 'two', 'three', 'four'].map(name => ({ name: `${name}.svg`, mimeType: 'image/svg+xml', buffer: Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="2" height="2"><rect width="2" height="2" fill="blue"/></svg>') }))

test('image imports retain previews across reload, atomically append overflow, retry save and undo saved import', async ({ page }) => {
  await page.goto('/#/multi-image-import')
  const grid = page.getByRole('grid', { name: 'Image import rows' })
  await expect(grid.getByRole('row')).toHaveCount(4)
  await page.getByLabel('Choose images to import').setInputFiles(files)
  await expect(page.getByRole('region', { name: 'Review image import' })).toBeVisible()
  await page.getByRole('checkbox', { name: 'Confirm these replacements and new rows' }).press('Escape')
  await expect(page.getByRole('button', { name: 'Cancel task', exact: true })).toBeVisible()
  await expect(grid.getByRole('img')).toHaveCount(0)
  await page.reload()
  await expect(page.getByRole('region', { name: 'Review image import' }).getByRole('img')).toHaveCount(4)
  await page.getByRole('checkbox', { name: 'Confirm these replacements and new rows' }).check()
  await page.getByRole('button', { name: 'Apply image import', exact: true }).click()
  await expect(grid.getByRole('row')).toHaveCount(5)
  await expect(grid.getByRole('img')).toHaveCount(4)
  await page.getByRole('button', { name: 'Fail next save', exact: true }).click()
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Changes were not saved.')
  await expect(page.getByRole('button', { name: 'Refresh rows', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Refresh rows', exact: true })).toBeEnabled()
  await expect(page.getByRole('button', { name: 'Save changes', exact: true })).toBeDisabled()
  await page.reload()
  await expect(grid.getByRole('img')).toHaveCount(4)
  await expect(grid.getByRole('img', { name: 'four', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(grid.getByRole('row')).toHaveCount(4)
  await expect(grid.getByRole('img')).toHaveCount(0)
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Refresh rows', exact: true })).toBeEnabled()
  await expect(page.getByRole('button', { name: 'Save changes', exact: true })).toBeDisabled()
  await page.reload()
  await expect(grid.getByRole('row')).toHaveCount(4)
  await expect(grid.getByRole('img')).toHaveCount(0)
})

test('changed import targets require explicit new target review without discarding converted files', async ({ page }) => {
  await page.goto('/#/multi-image-import')
  const grid = page.getByRole('grid', { name: 'Image import rows' })
  await expect(grid.getByRole('row')).toHaveCount(4)
  await page.getByLabel('Choose images to import').setInputFiles(files)
  const review = page.getByRole('region', { name: 'Review image import' })
  await expect(review.getByRole('img')).toHaveCount(4)
  await grid.getByRole('row').nth(1).getByRole('gridcell').nth(1).click()
  await page.getByRole('button', { name: 'Edit value', exact: true }).click()
  await page.getByRole('textbox', { name: 'Name', exact: true }).fill('Keep my edit')
  await page.getByRole('button', { name: 'Apply value', exact: true }).click()
  await expect(review.getByRole('alert')).toContainText('An original target changed')
  await expect(page.getByRole('button', { name: 'Apply image import', exact: true })).toBeDisabled()
  await page.getByLabel('Import starting row').selectOption({ label: 'Row 2' })
  await page.getByRole('button', { name: 'Review new targets', exact: true }).click()
  await page.getByRole('checkbox', { name: 'Confirm these replacements and new rows' }).check()
  await page.getByRole('button', { name: 'Apply image import', exact: true }).click()
  await expect(grid.getByRole('row')).toHaveCount(6)
  await expect(grid.getByRole('gridcell', { name: 'Keep my edit', exact: true })).toBeVisible()
  await expect(grid.getByRole('img')).toHaveCount(4)
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Refresh rows', exact: true })).toBeEnabled()
  await expect(page.getByRole('button', { name: 'Save changes', exact: true })).toBeDisabled()
  await page.reload()
  await expect(grid.getByRole('gridcell', { name: 'Keep my edit', exact: true })).toBeVisible()
  await expect(grid.getByRole('img')).toHaveCount(4)
})

test('dropped files survive route detachment and cancelled results remain downloadable', async ({ page }) => {
  await page.goto('/#/multi-image-import')
  await expect(page.getByRole('grid', { name: 'Image import rows' }).getByRole('row')).toHaveCount(4)
  const body = '<svg xmlns="http://www.w3.org/2000/svg" width="2" height="2"/>'
  await page.locator('main').evaluate((main, body) => {
    const dataTransfer = new DataTransfer(); dataTransfer.items.add(new File([body], 'retained.svg', { type: 'image/svg+xml' }))
    main.dispatchEvent(new DragEvent('drop', { dataTransfer, bubbles: true, cancelable: true }))
    location.hash = '/'
  }, body)
  await expect(page.getByRole('heading', { name: 'Products workspace', exact: true })).toBeVisible()
  await page.evaluate(() => { location.hash = '/multi-image-import' })
  await expect(page.getByRole('region', { name: 'Review image import' }).getByRole('img', { name: 'retained', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Cancel task', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Cancel task', exact: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Apply image import', exact: true })).toBeDisabled()
  await page.reload()
  const link = page.getByRole('link', { name: 'Download retained.svg', exact: true })
  await expect(link).toHaveAttribute('href', `data:image/svg+xml;base64,${Buffer.from(body).toString('base64')}`)
  await expect(link).toHaveAttribute('download', 'retained.svg')
  const [download] = await Promise.all([page.waitForEvent('download'), link.click()])
  expect(download.suggestedFilename()).toBe('retained.svg')
  expect(await readFile((await download.path())!, 'utf8')).toBe(body)
  await expect(page.getByRole('grid', { name: 'Image import rows' }).getByRole('img')).toHaveCount(0)
  for (const width of [1440, 1920, 2560, 3840]) {
    await page.setViewportSize({ width, height: 1000 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  }
})

for (const cancellation of ['button', 'escape']) test(`cancelling an accepted conversion retains its late candidate without changing rows (${cancellation})`, async ({ page }) => {
  await page.goto('/#/multi-image-import')
  const grid = page.getByRole('grid', { name: 'Image import rows' })
  await expect(grid.getByRole('row')).toHaveCount(4)
  await page.evaluate(() => {
    const original = FileReader.prototype.readAsDataURL, pending: Array<{ reader: FileReader; blob: Blob }> = []
    FileReader.prototype.readAsDataURL = function (blob) {
      pending.push({ reader: this, blob }); document.documentElement.setAttribute('data-pending-conversion', 'yes')
    }
    document.addEventListener('release-conversion', () => {
      FileReader.prototype.readAsDataURL = original
      for (const item of pending) original.call(item.reader, item.blob)
    }, { once: true })
  })
  await page.getByLabel('Choose images to import').setInputFiles(files.slice(0, 1))
  await expect(page.locator('html')).toHaveAttribute('data-pending-conversion', 'yes')
  await expect(page.getByRole('button', { name: 'Cancel task', exact: true })).toBeEnabled()
  if (cancellation === 'button') await page.getByRole('button', { name: 'Cancel task', exact: true }).click()
  else await page.getByRole('button', { name: 'Cancel task', exact: true }).press('Escape')
  await expect(page.getByRole('status')).toContainText('Task will not update your edit.')
  await page.evaluate(() => { document.dispatchEvent(new Event('release-conversion')) })
  await expect(page.getByRole('link', { name: 'Download one.svg', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Apply image import', exact: true })).toBeDisabled()
  await expect(grid.getByRole('img')).toHaveCount(0)
  await page.reload()
  await expect(page.getByRole('link', { name: 'Download one.svg', exact: true })).toBeVisible()
  await expect(grid.getByRole('img')).toHaveCount(0)
})
