import { expect, test, type Page } from './test.js'
async function authority(page: Page) {
  return page.evaluate(async () => {
    const { openDemoSource } = await import('/src/demo-source.ts')
    const scope = { sourceId: 'partitioned-inventory-v1', id: 'lists', epoch: 'v1' }
    const source = await openDemoSource(scope, [], () => {}, true)
    return source.readAtLeast(scope, [])
  })
}
const pane = (page: Page, side: string) => page.getByRole('region', { name: `${side} list`, exact: true })
async function save(page: Page) {
  const left = pane(page, 'Left')
  await left.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(left.getByRole('button', { name: 'Refresh rows', exact: true })).toBeEnabled()
  await expect(left.getByRole('button', { name: 'Save changes', exact: true })).toBeDisabled()
}
test('shared list move survives failed save, reload, retry and saved undo', async ({ page }) => {
  await page.goto('/#/cross-grid-drag')
  const left = pane(page, 'Left'), right = pane(page, 'Right')
  await expect(left.getByRole('checkbox')).toHaveCount(4)
  const original = await authority(page)
  await left.getByRole('checkbox', { name: 'Select Amber poster', exact: true }).check()
  await page.getByRole('button', { name: 'Move', exact: true }).click()
  await page.getByLabel('Insert before').selectOption({ label: 'Granite folio' })
  await page.getByRole('button', { name: 'Transfer selected rows', exact: true }).click()
  await expect(left.getByRole('checkbox')).toHaveCount(3)
  await expect(right.getByRole('checkbox')).toHaveCount(4)
  await expect(right.getByRole('gridcell').filter({ hasText: /^(Fern calendar|Amber poster|Granite folio|Harbor postcard)$/ })).toHaveText(['Fern calendar', 'Amber poster', 'Granite folio', 'Harbor postcard'])
  await page.getByRole('button', { name: 'Fail next save', exact: true }).click()
  await left.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(left.getByRole('alert')).toContainText('Changes were not saved.')
  await expect(left.getByRole('button', { name: 'Refresh rows', exact: true })).toBeEnabled()
  const rejected = await authority(page)
  expect(rejected.rows).toEqual(original.rows)
  expect(rejected.order).toEqual(original.order)
  expect(rejected.version).toEqual(original.version)
  await page.reload()
  await expect(left.getByRole('checkbox')).toHaveCount(3)
  await expect(right.getByRole('checkbox', { name: 'Select Amber poster', exact: true })).toBeVisible()
  await save(page)
  const committed = await authority(page)
  const amber = original.rows.find(row => row.document.name === 'Amber poster')!
  expect(committed.rows.find(row => row.document.name === 'Amber poster')).toEqual({ ...amber, document: { ...amber.document, side: 'right' } })
  expect(committed.rows).toHaveLength(original.rows.length)
  await page.reload()
  await expect(left.getByRole('checkbox')).toHaveCount(3)
  await expect(right.getByRole('checkbox')).toHaveCount(4)
  await left.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(left.getByRole('checkbox')).toHaveCount(4)
  await expect(right.getByRole('checkbox')).toHaveCount(3)
  await save(page)
  await page.reload()
  await expect(left.getByRole('checkbox', { name: 'Select Amber poster', exact: true })).toBeVisible()
  await expect(right.getByRole('checkbox', { name: 'Select Amber poster', exact: true })).toHaveCount(0)
  const undone = await authority(page)
  expect(undone.rows).toEqual(original.rows)
  expect(undone.order).toEqual(original.order)
})
test('protected rows copy safely and native drag moves ordinary rows', async ({ page }) => {
  await page.goto('/#/cross-grid-drag')
  const left = pane(page, 'Left'), right = pane(page, 'Right')
  await left.getByRole('checkbox', { name: 'Select Cedar label', exact: true }).check()
  await page.getByRole('button', { name: 'Move', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Transfer selected rows', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: 'Copy', exact: true }).click()
  await page.getByRole('button', { name: 'Transfer selected rows', exact: true }).click()
  await expect(right.getByRole('checkbox', { name: 'Select Cedar label', exact: true })).toBeVisible()
  await expect(left.getByRole('checkbox', { name: 'Select Cedar label', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Move', exact: true }).click()
  await left.getByRole('button', { name: 'Drag Blue card', exact: true }).dragTo(right.getByRole('heading', { name: 'Right list', exact: true }))
  await expect(right.getByRole('checkbox', { name: 'Select Blue card', exact: true })).toBeVisible()
  await expect(left.getByRole('checkbox', { name: 'Select Blue card', exact: true })).toHaveCount(0)
  await save(page)
  await page.reload()
  await expect(right.getByRole('checkbox')).toHaveCount(5)
  await expect(left.getByRole('checkbox')).toHaveCount(3)
  for (const width of [1440, 1920, 2560, 3840]) {
    await page.setViewportSize({ width, height: 1000 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  }
})

test('external move payload only copies and stale native drag cannot overwrite a newer edit', async ({ page }) => {
  await page.goto('/#/cross-grid-drag')
  const left = pane(page, 'Left'), right = pane(page, 'Right')
  await expect(left.getByRole('checkbox')).toHaveCount(4)
  const original = await authority(page), amber = original.rows.find(row => row.document.name === 'Amber poster')!
  await right.evaluate((element, document) => {
    const dataTransfer = new DataTransfer()
    dataTransfer.setData('application/x-data-editor-partition-rows', JSON.stringify({ format: 'partition-rows:1', workspaceId: 'partitioned-inventory', token: 'external', source: 'left', mode: 'move', rows: [{ entityId: 'untrusted', document }] }))
    element.dispatchEvent(new DragEvent('drop', { dataTransfer, bubbles: true, cancelable: true }))
  }, amber.document)
  await expect(right.getByRole('checkbox', { name: 'Select Amber poster', exact: true })).toBeVisible()
  await expect(left.getByRole('checkbox', { name: 'Select Amber poster', exact: true })).toBeVisible()
  await save(page)
  const copied = await authority(page), copy = copied.rows.find(row => row.document.name === 'Amber poster' && row.document.side === 'right')!
  expect(copy.identity).not.toEqual(amber.identity)
  expect(copy.document.id).not.toEqual(amber.document.id)
  expect(copy.document).toEqual({ ...amber.document, id: copy.document.id, side: 'right', homeSide: 'right', deleteProtected: false })
  expect(copied.rows.find(row => row.document.id === amber.document.id)).toEqual(amber)
  await page.getByRole('button', { name: 'Move', exact: true }).click()
  await left.getByRole('button', { name: 'Drag Blue card', exact: true }).evaluate(button => {
    const dataTransfer = new DataTransfer()
    button.dispatchEvent(new DragEvent('dragstart', { dataTransfer, bubbles: true, cancelable: true }))
    document.addEventListener('drop-retained-rows', () => {
      document.querySelector('[aria-label="Right list"]')!.dispatchEvent(new DragEvent('drop', { dataTransfer, bubbles: true, cancelable: true }))
    }, { once: true })
  })
  await left.getByRole('gridcell', { name: 'Blue card', exact: true }).click()
  await left.getByRole('button', { name: 'Edit value', exact: true }).click()
  await left.getByRole('textbox', { name: 'Name', exact: true }).fill('Blue updated')
  await left.getByRole('button', { name: 'Apply value', exact: true }).click()
  await expect(left.getByRole('checkbox', { name: 'Select Blue updated', exact: true })).toBeVisible()
  await page.evaluate(() => document.dispatchEvent(new Event('drop-retained-rows')))
  await expect(page.getByRole('region', { name: 'Transfer controls' }).getByRole('alert')).toContainText('A dragged row changed')
  await expect(right.getByRole('checkbox')).toHaveCount(4)
  await save(page)
  await page.reload()
  await expect(left.getByRole('checkbox', { name: 'Select Blue updated', exact: true })).toBeVisible()
  await expect(right.getByRole('checkbox')).toHaveCount(4)
})
