import { expect, test } from './test.js'

for (const overflow of [false, true]) test(`ragged paste preserves omitted fields through validation, reload and saved rows (overflow=${overflow})`, async ({ page }) => {
  await page.goto('/#/playground')
  const grid = page.getByRole('grid', { name: 'Inventory items' })
  await expect(grid.getByRole('row')).toHaveCount(37)
  await page.getByRole('switch', { name: 'Auto-save', exact: true }).click()
  const rowIndex = overflow ? 35 : 1
  const first = grid.getByRole('row').nth(rowIndex)
  const quantity = await first.getByRole('gridcell').nth(2).textContent()
  const thirdQuantity = overflow ? '0' : await grid.getByRole('row').nth(3).getByRole('gridcell').nth(2).textContent()
  const origin = first.getByRole('gridcell').nth(1)
  await origin.click()
  const original = await origin.textContent()
  const text = 'First short\nSecond long\tinvalid\nThird short'
  await origin.evaluate((cell, text) => {
    const event = new ClipboardEvent('paste', { bubbles: true, cancelable: true, clipboardData: new DataTransfer() })
    event.clipboardData!.setData('text/plain', text); cell.dispatchEvent(event)
  }, text)
  await expect(page.getByRole('alert')).toBeVisible()
  await expect(grid.getByRole('row')).toHaveCount(37)
  await page.reload()
  await page.getByRole('button', { name: 'Resume editing', exact: true }).click()
  const input = page.getByRole('textbox', { name: /^Edit \d+ selected fields$/ })
  await expect(input).toHaveValue(text)
  // Adding a cell changes the captured target, so it cannot silently expand
  // this recovered operation or clear the omitted quantity fields.
  await input.fill('First short\t99\nSecond long\t41\nThird short')
  await page.getByRole('button', { name: 'Apply value', exact: true }).click()
  await expect(input).toBeVisible()
  await expect(grid.getByRole('row')).toHaveCount(37)
  await input.fill('First short\nSecond long\t41\nThird short')
  await page.getByRole('button', { name: 'Apply value', exact: true }).click()
  await expect(grid.getByRole('row')).toHaveCount(overflow ? 38 : 37)
  await expect(first.getByRole('gridcell').nth(2)).toHaveText(quantity!)
  const third = grid.getByRole('row').filter({ has: page.getByRole('gridcell', { name: 'Third short', exact: true }) })
  await expect(third.getByRole('gridcell').nth(2)).toHaveText(thirdQuantity!)
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(grid.getByRole('row')).toHaveCount(37)
  await expect(origin).toHaveText(original!)
  await page.getByRole('button', { name: 'Redo', exact: true }).click()
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(page.getByText('1 saves', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Refresh rows', exact: true })).toBeEnabled()
  await page.reload()
  await expect(grid.getByRole('row')).toHaveCount(overflow ? 38 : 37)
  await expect(first.getByRole('gridcell').nth(2)).toHaveText(quantity!)
  await expect(third.getByRole('gridcell').nth(2)).toHaveText(thirdQuantity!)
  await expect(grid.getByRole('row').filter({ has: page.getByRole('gridcell', { name: 'Second long', exact: true }) }).getByRole('gridcell').nth(2)).toHaveText('41')
})

test('native paste extends the last row, undoes the complete edit, saves and reopens new rows', async ({ page }) => {
  await page.goto('/#/playground')
  const grid = page.getByRole('grid', { name: 'Inventory items' })
  await expect(grid.getByRole('row')).toHaveCount(37)
  await page.getByRole('switch', { name: 'Auto-save', exact: true }).click()
  await expect(page.getByRole('switch', { name: 'Auto-save', exact: true })).not.toBeChecked()
  const origin = grid.getByRole('row').last().getByRole('gridcell').nth(1)
  const original = await origin.textContent()
  await origin.click()
  await page.evaluate(() => { const source = document.createElement('textarea'); source.setAttribute('aria-label', 'Clipboard source'); document.body.append(source) })
  const clipboard = page.getByRole('textbox', { name: 'Clipboard source', exact: true })
  await clipboard.fill('Changed last\t41\nCreated first\t42\nCreated second\t43')
  await clipboard.press('Control+a'); await clipboard.press('Control+c')
  await origin.focus(); await origin.press('Control+v')
  await clipboard.evaluate(element => element.remove())
  await expect(grid.getByRole('row')).toHaveCount(39)
  await expect(grid.getByRole('gridcell', { name: 'Created second', exact: true })).toBeVisible()
  await expect(grid.getByRole('row').last()).toContainText('43')
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(grid.getByRole('row')).toHaveCount(37)
  await expect(grid.getByRole('row').last().getByRole('gridcell').nth(1)).toHaveText(original!)
  await page.getByRole('button', { name: 'Redo', exact: true }).click()
  await expect(grid.getByRole('row')).toHaveCount(39)
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(page.getByText('1 saves', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Refresh rows', exact: true })).toBeEnabled()
  await page.reload()
  await expect(grid.getByRole('row')).toHaveCount(39)
  for (const [name, quantity] of [['Changed last', '41'], ['Created first', '42'], ['Created second', '43']]) {
    const row = grid.getByRole('row').filter({ has: page.getByRole('gridcell', { name, exact: true }) })
    await expect(row.getByRole('gridcell', { name: quantity, exact: true })).toBeVisible()
  }
})

for (const failure of ['opening-write-delayed', 'invalid-value', 'opening-acknowledgement', 'target-acknowledgement', 'apply-acknowledgement', 'duplicate-key'] as const) test(`overflow paste retains the entire input through ${failure} without publishing partial rows`, async ({ page, context }) => {
  const { SourceFixture } = await import('../kernel/source-fixture.js')
  const { kernelId } = await import('../../src/kernel/model.js')
  const name = `paste-creation-${crypto.randomUUID()}`
  const source = new SourceFixture({ sourceId: name, id: kernelId<'scope'>('scope'), epoch: kernelId<'scope-epoch'>('epoch') }, { a: { value: 12, hidden: 'original' } })
  await context.route('**/__kernel-source/*', async route => {
    const path = new URL(route.request().url()).pathname, body = route.request().postDataJSON()
    const result = path.endsWith('/read') ? await source.readAtLeast() : path.endsWith('/lookup') ? await source.lookupOperation(body) : await source.submit(body)
    await route.fulfill({ contentType: 'application/json', body: JSON.stringify(result) })
  })
  const mount = async (restore: boolean) => page.evaluate(async ({ name, restore, duplicate, loseTarget }) => {
    await (await import('/src/test-fixtures/durable-workspace.ts')).startDurableWorkspace(name, restore)
    const container = document.createElement('div'); document.body.append(container)
    ;(await import('/src/test-fixtures/workspace-grid.tsx')).mountCreatingWorkspaceGrid(container, duplicate, loseTarget)
  }, { name, restore, duplicate: failure === 'duplicate-key', loseTarget: failure === 'target-acknowledgement' && !restore })
  await page.goto('/'); await mount(false)
  const grid = page.getByRole('grid', { name: 'Workspace rows' }), origin = grid.getByRole('gridcell', { name: '12', exact: true })
  await origin.click()
  if (failure === 'opening-acknowledgement') await page.evaluate(async () => (await import('/src/test-fixtures/durable-workspace.ts')).loseNextWorkspaceAcknowledgement())
  if (failure === 'opening-write-delayed') await page.evaluate(async () => (await import('/src/test-fixtures/durable-workspace.ts')).holdNextWorkspaceWrite())
  const text = failure === 'opening-write-delayed' || failure === 'invalid-value' || failure === 'apply-acknowledgement' ? '41\ninvalid\n43' : failure === 'duplicate-key' ? '41\n42' : '41\n42\n43'
  await origin.evaluate((cell, text) => {
    const event = new ClipboardEvent('paste', { bubbles: true, cancelable: true, clipboardData: new DataTransfer() })
    event.clipboardData!.setData('text/plain', text); cell.dispatchEvent(event)
  }, text)
  if (failure === 'opening-write-delayed') {
    await expect.poll(() => page.evaluate(async () => (await import('/src/test-fixtures/durable-workspace.ts')).workspaceWriteIsHeld())).toBe(true)
    const dialog = page.waitForEvent('dialog')
    await page.evaluate(() => { setTimeout(() => location.reload(), 0) })
    const warning = await dialog
    expect(warning.type()).toBe('beforeunload')
    await warning.dismiss()
    await expect(grid.getByRole('gridcell')).toHaveCount(1)
    await page.evaluate(async () => (await import('/src/test-fixtures/durable-workspace.ts')).releaseWorkspaceWrite())
    await expect(page.getByRole('alert')).toBeVisible()
  } else if (failure === 'opening-acknowledgement') {
    await expect.poll(() => page.evaluate(async () => (await import('/src/test-fixtures/durable-workspace.ts')).workspaceForReactFixture().getSnapshot().storage?.kind)).toBe('unknown')
  } else await expect(page.getByRole('alert')).toBeVisible()
  await expect(grid.getByRole('gridcell')).toHaveCount(1)
  expect(source.writes).toBe(0)
  await page.reload(); await mount(true)
  await page.getByRole('button', { name: 'Resume editing', exact: true }).click()
  const input = page.getByRole('textbox', { name: /^(Edit value|Edit \d+ selected fields)$/ })
  await expect(input).toHaveValue(text)
  await expect(grid.getByRole('gridcell')).toHaveCount(1)
  if (failure === 'duplicate-key') {
    await page.getByRole('button', { name: 'Apply value', exact: true }).click()
    await expect(page.getByRole('alert')).toBeVisible()
    await expect(input).toHaveValue(text)
    expect(source.writes).toBe(0)
    await page.getByRole('button', { name: 'Discard input', exact: true }).click()
    await expect(grid.getByRole('gridcell')).toHaveCount(1)
    return
  }
  if (failure === 'opening-acknowledgement') await page.getByRole('button', { name: 'Prepare new rows for paste', exact: true }).click()
  else await input.fill('41\n42\n43')
  if (failure === 'apply-acknowledgement') {
    await expect.poll(() => page.evaluate(async () => {
      const snapshot = (await import('/src/test-fixtures/durable-workspace.ts')).workspaceForReactFixture().getSnapshot()
      return { status: snapshot.editorInput?.status, pending: snapshot.ingress.pending.length }
    })).toEqual({ status: 'published', pending: 0 })
    await page.evaluate(async () => (await import('/src/test-fixtures/durable-workspace.ts')).loseNextWorkspaceAcknowledgement())
  }
  await page.getByRole('button', { name: 'Apply value', exact: true }).click()
  if (failure === 'apply-acknowledgement') {
    await expect.poll(() => page.evaluate(async () => (await import('/src/test-fixtures/durable-workspace.ts')).workspaceForReactFixture().getSnapshot().storage?.kind)).toBe('unknown')
    await page.reload(); await mount(true)
  }
  await expect(grid.getByRole('gridcell')).toHaveCount(3)
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect.poll(() => source.writes).toBe(1)
  await expect(page.getByRole('button', { name: 'Refresh rows', exact: true })).toBeEnabled()
  expect(await page.evaluate(async () => (await import('/src/test-fixtures/workspace-grid.tsx')).workspaceRowFactoryCalls())).toBe(failure === 'opening-acknowledgement' ? 2 : 0)
  const rows = source.snapshot().rows.map(row => row.document)
  expect(rows.map(row => row.value)).toEqual([41, 42, 43])
  expect(rows.map(row => row.hidden)).toEqual(['original', 'created', 'created'])
  expect(new Set(rows.slice(1).map(row => row.factoryToken)).size).toBe(2)
})

for (const route of ['cross-grid-drag', 'multi-image-import']) test(`paste row creation uses the original defaults on ${route}`, async ({ page }) => {
  await page.goto(`/#/${route}`)
  const cross = route === 'cross-grid-drag'
  const grid = page.getByRole('grid', { name: cross ? 'Left inventory' : 'Image import rows' })
  const other = page.getByRole('grid', { name: 'Right inventory' })
  await expect(grid.getByRole('row')).toHaveCount(cross ? 5 : 4)
  const count = await grid.getByRole('row').count()
  const origin = grid.getByRole('row').last().getByRole('gridcell').nth(1)
  await origin.click()
  await origin.evaluate(cell => {
    const event = new ClipboardEvent('paste', { bubbles: true, cancelable: true, clipboardData: new DataTransfer() })
    event.clipboardData!.setData('text/plain', 'Updated tail\nNew pasted row'); cell.dispatchEvent(event)
  })
  await expect(grid.getByRole('row')).toHaveCount(count + 1)
  const created = grid.getByRole('row').filter({ has: page.getByRole('gridcell', { name: 'New pasted row', exact: true }) })
  await expect(created).toBeVisible()
  if (cross) {
    await expect(other.getByRole('row')).toHaveCount(4)
    await expect(created.getByRole('gridcell').nth(2)).toHaveText('0')
    await expect(created.getByRole('gridcell').nth(3)).toHaveText('')
  } else await expect(created.getByRole('gridcell').first()).toHaveText('No image')
  const actions = cross ? page.getByRole('region', { name: 'Left list', exact: true }) : page.getByRole('main')
  await actions.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(actions.getByRole('button', { name: 'Refresh rows', exact: true })).toBeEnabled()
  await expect(actions.getByRole('button', { name: 'Save changes', exact: true })).toBeDisabled()
  await page.reload()
  await expect(grid.getByRole('row')).toHaveCount(count + 1)
  await expect(created).toBeVisible()
  if (cross) await expect(other.getByRole('row')).toHaveCount(4)
})
