import { expect, test } from './test.js'

test('Playground row actions, rejected save and image input use the durable Workspace across reload', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message))
  await page.goto('/#/playground')
  const grid = page.getByRole('grid', { name: 'Inventory items' })
  await expect(grid.getByRole('row')).toHaveCount(37)
  await page.getByRole('switch', { name: 'Auto-save', exact: true }).click()
  await expect(page.getByRole('switch', { name: 'Auto-save', exact: true })).not.toBeChecked()
  await page.getByRole('button', { name: 'Duplicate row', exact: true }).click()
  await expect(grid.getByRole('gridcell', { name: 'Amber poster copy', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Fail next save', exact: true }).click()
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Changes were not saved.')
  await expect(page.getByRole('button', { name: 'Refresh rows', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(page.getByText('1 saves', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Refresh rows', exact: true })).toBeEnabled()
  await page.reload()
  await expect(grid.getByRole('gridcell', { name: 'Amber poster copy', exact: true })).toBeVisible()
  await expect(page.getByRole('switch', { name: 'Auto-save', exact: true })).not.toBeChecked()
  await page.getByRole('combobox', { name: 'Row action target', exact: true }).selectOption({ label: 'Amber poster copy' })
  await page.getByRole('checkbox', { name: 'Delete the selected row: Amber poster copy', exact: true }).check()
  await page.getByRole('button', { name: 'Delete row', exact: true }).click()
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(page.getByText('2 saves', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Refresh rows', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(grid.getByRole('gridcell', { name: 'Amber poster copy', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(page.getByText('3 saves', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Refresh rows', exact: true })).toBeEnabled()
  const row = grid.getByRole('row').filter({ has: page.getByRole('gridcell', { name: 'Amber poster', exact: true }) })
  await row.getByRole('gridcell', { name: 'No image', exact: true }).click()
  await page.getByRole('button', { name: 'Edit value', exact: true }).click()
  await expect(page.getByLabel('Choose a file', { exact: true })).toBeEnabled()
  await page.getByLabel('Choose a file', { exact: true }).setInputFiles({ name: 'photo.svg', mimeType: 'image/svg+xml', buffer: Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="2" height="2"><rect width="2" height="2" fill="blue"/></svg>') })
  await expect(page.getByRole('textbox', { name: 'Image', exact: true })).toHaveValue(/^data:image\/svg\+xml;base64,/)
  await page.getByRole('button', { name: 'Apply value', exact: true }).click()
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(page.getByText('4 saves', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Refresh rows', exact: true })).toBeEnabled()
  await page.reload()
  await expect(grid.getByRole('img', { name: 'Amber poster', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Simulate remote change', exact: true }).click()
  await expect(grid.getByText(/^Remote amber/)).toBeVisible()
  await expect(grid.getByRole('img', { name: /^Remote amber/ })).toBeVisible()
  const task = await page.evaluate(async () => (await import('/src/test-fixtures/image-task.ts')).resumeAcceptedImage('playground-image-tasks-v1'))
  expect(task.recovered).toMatchObject({ kind: 'succeeded', result: { kind: 'session-candidate', input: { kind: 'encoded', value: `data:image/svg+xml;base64,${Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="2" height="2"><rect width="2" height="2" fill="blue"/></svg>').toString('base64')}` } } })
  expect(task.repeat).toEqual(task.recovered)
  expect(task.missing.kind).toBe('unknown')
  expect(task.mismatchRejected).toBe(true)
  expect(errors).toEqual([])
})

test('Playground persists complete row order, created rows and immediate save mode', async ({ page }) => {
  await page.goto('/#/playground')
  const grid = page.getByRole('grid', { name: 'Inventory items' })
  await expect(grid.getByRole('row')).toHaveCount(37)
  const automatic = page.getByRole('switch', { name: 'Auto-save', exact: true })
  await automatic.click()
  await expect(automatic).not.toBeChecked()
  await page.getByRole('button', { name: 'Move row down', exact: true }).click()
  await expect(grid.getByRole('row').nth(2)).toContainText('Amber poster')
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(page.getByText('1 saves', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Refresh rows', exact: true })).toBeEnabled()
  await page.reload()
  await expect(grid.getByRole('row').nth(2)).toContainText('Amber poster')
  await page.getByRole('button', { name: 'Add row', exact: true }).click()
  await expect(grid.getByRole('gridcell', { name: 'Untitled item', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(page.getByText('2 saves', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Refresh rows', exact: true })).toBeEnabled()
  await automatic.click()
  await expect(automatic).toBeChecked()
  await page.getByRole('combobox', { name: 'Auto-save timing', exact: true }).selectOption('immediate')
  await expect(page.getByRole('combobox', { name: 'Auto-save timing', exact: true })).toHaveValue('immediate')
  await page.getByRole('combobox', { name: 'Row action target', exact: true }).selectOption({ label: 'Untitled item' })
  await page.getByRole('button', { name: 'Duplicate row', exact: true }).click()
  await expect(page.getByText('3 saves', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Refresh rows', exact: true })).toBeEnabled()
  await page.reload()
  await expect(grid.getByRole('row')).toHaveCount(39)
  await expect(grid.getByRole('gridcell', { name: 'Untitled item copy', exact: true })).toBeVisible()
  await expect(automatic).toBeChecked()
  await expect(page.getByRole('combobox', { name: 'Auto-save timing', exact: true })).toHaveValue('immediate')
  for (const width of [1440, 1920, 2560, 3840]) {
    await page.setViewportSize({ width, height: 1000 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  }
})
