import { expect, test } from './test.js'

test('product authority serializes writers, persists exact receipts and fences a missing operation before its late arrival', async ({ page }) => {
  const name = `product-authority-${crypto.randomUUID()}`
  await page.goto('/')
  const result = await page.evaluate(async name => (await import('/src/test-fixtures/product-source.ts')).exerciseProductSource(name), name)
  expect(result.baseline.rows[0]!.document.name).toBe('Original')
  expect(result.outcomes.map(value => value.kind).sort()).toEqual(['applied', 'not-applied'])
  expect(result.repeat).toEqual(result.lookup)
  expect(result.negative.kind).toBe('not-applied')
  expect(result.fenced).toEqual(result.negative)
  expect(result.mismatch).toBe(true)
  expect(result.latest.version).toMatchObject({ position: '2' })
  expect(result.latest.rows[0]!.document.hidden).toEqual({ retained: 7 })
  await page.reload()
  const reopened = await page.evaluate(async ({ name, operation }) => (await import('/src/test-fixtures/product-source.ts')).reopenDemoSource(name, operation), { name, operation: result.applied })
  expect(reopened.authority.rows).toEqual(result.latest.rows)
  expect(reopened.authority.version).toEqual(result.latest.version)
  expect(reopened.outcome).toEqual(result.lookup)
})

test('demo authority atomically creates and orders, restores a new incarnation, and rejects a mixed invalid batch without partial writes', async ({ page }) => {
  await page.goto('/')
  const result = await page.evaluate(async name => (await import('/src/test-fixtures/product-source.ts')).exerciseDemoStructure(name), `demo-structure-${crypto.randomUUID()}`)
  expect(result.created.kind).toBe('applied')
  expect(result.ordered.rows.map(row => row.document.name)).toEqual(['New', 'Original'])
  expect(result.deletion.kind).toBe('applied')
  expect(result.restored.kind).toBe('applied')
  expect(result.afterRestore.rows[1]!.document).toEqual({ name: 'New', hidden: 8 })
  expect(result.afterRestore.rows[1]!.identity.key).toBe(result.ordered.rows[0]!.identity.key)
  expect(result.afterRestore.rows[1]!.identity.incarnation).not.toBe(result.ordered.rows[0]!.identity.incarnation)
  expect(result.invalid.kind).toBe('not-applied')
  expect(result.afterRejected.rows).toEqual(result.afterRestore.rows)
  expect(result.afterRejected.version).toEqual(result.afterRestore.version)
  expect(result.failed.kind).toBe('not-applied')
  expect(result.failureLookup).toEqual(result.failed)
  expect(result.staleChangeRejected).toBe(true)
  expect(result.external.rows[0]!.document).toEqual({ name: 'External', hidden: 7 })
})
