import { expect, test } from './test.js'
import { SourceFixture } from '../kernel/source-fixture.js'
import { kernelId } from '../../src/kernel/model.js'

test('live search composes with column filters, preserves sorting, and restores its exact text', async ({ page }) => {
  await page.goto('/')
  const grid = page.getByRole('grid', { name: 'Quick-start products' }), search = page.getByRole('searchbox', { name: 'Filter rows' })
  await search.fill('  BLUE  ')
  await expect(grid.getByRole('gridcell', { name: 'Blue card', exact: true })).toBeVisible()
  await expect(grid.getByRole('gridcell')).toHaveCount(4)
  await search.fill('')
  await grid.getByRole('button', { name: 'Filter Quantity', exact: true }).click()
  await page.getByRole('combobox', { name: 'Condition 1', exact: true }).selectOption('greater-than-or-equal')
  await page.getByRole('textbox', { name: 'Quantity filter', exact: true }).fill('24')
  await page.getByRole('button', { name: 'Apply filter', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Filter Quantity', exact: true })).toHaveCount(0)
  await search.pressSequentially('CEDAR')
  await expect(grid.getByRole('gridcell')).toHaveCount(4)
  await expect(grid.getByRole('gridcell', { name: 'Cedar label', exact: true })).toBeVisible()
  await grid.getByRole('button', { name: 'Sort Name', exact: true }).click()
  await expect(grid.getByRole('columnheader', { name: 'Name', exact: true })).toHaveAttribute('aria-sort', 'ascending')
  await page.reload()
  await expect(search).toHaveValue('CEDAR')
  await expect(grid.getByRole('gridcell')).toHaveCount(4)
  await expect(grid.getByRole('columnheader', { name: 'Name', exact: true })).toHaveAttribute('aria-sort', 'ascending')
  await search.fill('Amber')
  await expect(grid.getByRole('gridcell')).toHaveCount(0)
  await grid.getByRole('button', { name: 'Filter Quantity', exact: true }).click()
  await page.getByRole('button', { name: 'Clear filter', exact: true }).click()
  await expect(search).toHaveValue('Amber')
  await expect(grid.getByRole('gridcell', { name: 'Amber poster', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Save changes', exact: true })).toBeDisabled()
})

test('search is independent between the two transfer lists', async ({ page }) => {
  await page.goto('/#/cross-grid-drag')
  const left = page.getByRole('region', { name: 'Left list', exact: true }), right = page.getByRole('region', { name: 'Right list', exact: true })
  await expect(right.getByRole('gridcell', { name: 'Fern calendar', exact: true })).toBeVisible()
  const original = await right.getByRole('gridcell').allTextContents()
  await left.getByRole('searchbox').fill('Amber')
  await expect(left.getByRole('gridcell')).toHaveCount(4)
  await expect(right.getByRole('gridcell')).toHaveText(original)
  await page.reload()
  await expect(left.getByRole('searchbox')).toHaveValue('Amber')
  await expect(left.getByRole('gridcell')).toHaveCount(4)
  await expect(right.getByRole('searchbox')).toHaveValue('')
  await expect(right.getByRole('gridcell')).toHaveText(original)
})

test('lost search acknowledgement retains text and refresh matches new source rows without writing them', async ({ page, context }) => {
  const name = `search-${crypto.randomUUID()}`
  const source = new SourceFixture({ sourceId: name, id: kernelId<'scope'>('scope'), epoch: kernelId<'scope-epoch'>('epoch') }, { a: { value: 'Alpha' }, b: { value: 'Beta' } })
  await context.route('**/__kernel-source/*', async route => {
    const path = new URL(route.request().url()).pathname, body = route.request().postDataJSON()
    const result = path.endsWith('/read') ? await source.readAtLeast() : path.endsWith('/lookup') ? await source.lookupOperation(body) : await source.submit(body)
    await route.fulfill({ contentType: 'application/json', body: JSON.stringify(result) })
  })
  async function mount(restore: boolean) {
    await page.goto('/')
    await page.evaluate(async ({ name, restore }) => {
      await (await import('/src/test-fixtures/durable-workspace.ts')).startDurableWorkspace(name, restore)
      const container = document.createElement('div'); document.body.append(container)
      ;(await import('/src/test-fixtures/workspace-grid.tsx')).mountEditableWorkspaceGrid(container)
    }, { name, restore })
  }
  await mount(false)
  const search = page.getByRole('searchbox', { name: 'Filter rows' }), grid = page.getByRole('grid', { name: 'Workspace rows' })
  await expect(grid.getByRole('gridcell')).toHaveText(['Alpha', 'Beta'])
  await page.evaluate(async () => (await import('/src/test-fixtures/durable-workspace.ts')).loseNextWorkspaceAcknowledgement())
  await search.fill('Alpha')
  await expect(page.getByRole('button', { name: 'Check pending results', exact: true })).toBeVisible()
  await expect(search).toHaveValue('Alpha')
  await mount(true)
  await expect(search).toHaveValue('Alpha')
  await expect(grid.getByRole('gridcell')).toHaveText(['Alpha'])
  await search.fill('Beta')
  await expect(grid.getByRole('gridcell')).toHaveText(['Beta'])
  source.external({ a: { value: 'Alpha' }, b: { value: 'Beta' }, c: { value: 'Beta new' } })
  await page.getByRole('button', { name: 'Refresh rows', exact: true }).click()
  await expect(grid.getByRole('gridcell')).toHaveText(['Beta', 'Beta new'])
  expect(source.writes).toBe(0)
})
