import { expect, test } from './test.js'

test('Escape clears the full selection and outside clicks leave grid actions without a target', async ({ page }) => {
  await page.goto('/')
  const grid = page.getByRole('grid', { name: 'Quick-start products' })
  await grid.getByRole('gridcell', { name: 'Amber poster', exact: true }).click()
  await grid.getByRole('gridcell', { name: 'Cedar label', exact: true }).click({ modifiers: ['Control'] })
  await page.keyboard.press('Escape')
  await expect(grid.getByRole('gridcell', { selected: true })).toHaveCount(0)
  await expect(grid).toBeFocused()
  await expect(page.getByRole('button', { name: 'Edit value', exact: true })).toBeDisabled()
  await grid.press('Control+a')
  await expect(grid.getByRole('gridcell', { selected: true })).toHaveCount(12)
  await page.getByRole('heading', { name: 'Products workspace', exact: true }).click()
  await expect(grid.getByRole('gridcell', { selected: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Paste into selection', exact: true })).toBeDisabled()
  await grid.getByRole('gridcell', { name: 'Amber poster', exact: true }).click()
  const fill = page.getByRole('button', { name: 'Fill selection', exact: true })
  await fill.click()
  await page.getByRole('heading', { name: 'Products workspace', exact: true }).click()
  await expect(fill).toHaveAttribute('aria-pressed', 'false')
  await grid.getByRole('gridcell', { name: 'Blue card', exact: true }).click()
  await expect(grid.getByRole('gridcell', { name: 'Blue card', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Save changes', exact: true })).toBeDisabled()
  const search = page.getByRole('searchbox', { name: 'Filter rows', exact: true })
  await search.fill('no matching product')
  await expect(grid.getByRole('gridcell')).toHaveCount(0)
  await grid.focus(); await grid.press('Escape')
  await search.fill('')
  await expect(grid.getByRole('gridcell')).toHaveCount(12)
  await expect(grid.getByRole('gridcell', { selected: true })).toHaveCount(0)
})

test('outside selection exit commits valid scalar input and preserves invalid input for correction', async ({ page }) => {
  await page.goto('/')
  const grid = page.getByRole('grid', { name: 'Quick-start products' })
  const outside = page.getByRole('heading', { name: 'Products workspace', exact: true })
  await grid.getByRole('gridcell', { name: 'Amber poster', exact: true }).dblclick()
  const name = page.getByRole('textbox', { name: 'Name', exact: true })
  await name.fill('Outside committed')
  await outside.click()
  await expect(name).toHaveCount(0)
  await expect(grid.getByRole('gridcell', { name: 'Outside committed', exact: true })).toBeVisible()
  await expect(grid.getByRole('gridcell', { selected: true })).toHaveCount(0)
  await grid.getByRole('gridcell', { name: '12', exact: true }).dblclick()
  const quantity = page.getByRole('textbox', { name: 'Quantity', exact: true })
  await quantity.fill('invalid quantity')
  await outside.click()
  await expect(quantity).toHaveValue('invalid quantity')
  await expect(page.getByRole('alert')).toBeVisible()
  await expect(grid.getByRole('gridcell', { name: '12', exact: true })).toHaveAttribute('aria-selected', 'true')
  await quantity.fill('27'); await outside.click()
  await expect(quantity).toHaveCount(0)
  await expect(grid.getByRole('gridcell', { selected: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Refresh rows', exact: true })).toBeEnabled()
  await page.reload()
  await expect(grid.getByRole('gridcell', { name: 'Outside committed', exact: true })).toBeVisible()
  await expect(grid.getByRole('gridcell', { name: '27', exact: true })).toBeVisible()
})
