import { expect, test } from './test.js'

test('summary counts disjoint visible cells and filtered rows without an envelope', async ({ page }) => {
  await page.goto('/')
  const grid = page.getByRole('grid', { name: 'Quick-start products' })
  const summary = page.getByRole('group', { name: 'Grid summary', exact: true })
  await expect(summary.getByText('3 rows', { exact: true })).toBeVisible()
  await grid.getByRole('gridcell', { name: 'Amber poster', exact: true }).click()
  await grid.getByRole('gridcell', { name: 'Cedar label', exact: true }).click({ modifiers: ['Control'] })
  await grid.getByRole('gridcell', { name: '36', exact: true }).click({ modifiers: ['Meta'] })
  await expect(summary.getByText('2 rows × 2 columns · 3 cells', { exact: true })).toBeVisible()
  const search = page.getByRole('searchbox', { name: 'Filter rows', exact: true })
  await search.fill('Cedar')
  await expect(summary.getByText('1 of 3 rows', { exact: true })).toBeVisible()
  await expect(summary.getByText('1 rows × 2 columns · 2 cells', { exact: true })).toBeVisible()
  await search.fill('no matching item')
  await expect(summary.getByText('0 of 3 rows', { exact: true })).toBeVisible()
  await expect(summary.locator('[data-grid-selection-summary]')).toHaveCount(0)
  await search.fill('')
  await expect(summary.getByText('2 rows × 2 columns · 3 cells', { exact: true })).toBeVisible()
  await page.reload()
  await expect(summary.getByText('3 rows', { exact: true })).toBeVisible()
})

test('partition summaries use each partition total even when its query is empty', async ({ page }) => {
  await page.goto('/#/cross-grid-drag')
  const left = page.locator('.business-grid__workspace').filter({ has: page.getByRole('grid', { name: 'Left inventory', exact: true }) })
  const right = page.locator('.business-grid__workspace').filter({ has: page.getByRole('grid', { name: 'Right inventory', exact: true }) })
  const leftSummary = left.getByRole('group', { name: 'Grid summary', exact: true })
  const rightSummary = right.getByRole('group', { name: 'Grid summary', exact: true })
  await expect(leftSummary.getByText('4 rows', { exact: true })).toBeVisible()
  await expect(rightSummary.getByText('3 rows', { exact: true })).toBeVisible()
  await left.getByRole('searchbox', { name: 'Filter rows', exact: true }).fill('Amber')
  await expect(leftSummary.getByText('1 of 4 rows', { exact: true })).toBeVisible()
  await expect(rightSummary.getByText('3 rows', { exact: true })).toBeVisible()
  await left.getByRole('searchbox', { name: 'Filter rows', exact: true }).fill('Missing')
  await expect(leftSummary.getByText('0 of 4 rows', { exact: true })).toBeVisible()
  await page.reload()
  await expect(leftSummary.getByText('0 of 4 rows', { exact: true })).toBeVisible()
  await expect(rightSummary.getByText('3 rows', { exact: true })).toBeVisible()
})

test('changed summary includes new fields, survives filtering and clears after authoritative save', async ({ page }) => {
  await page.goto('/#/playground')
  const grid = page.getByRole('grid', { name: 'Inventory items' })
  const summary = page.getByRole('group', { name: 'Grid summary', exact: true })
  const automatic = page.getByRole('switch', { name: 'Auto-save', exact: true })
  await automatic.click(); await expect(automatic).not.toBeChecked()
  await page.getByRole('button', { name: 'Add row', exact: true }).click()
  await expect(summary.getByText('8 changed', { exact: true })).toBeVisible()
  await page.getByRole('searchbox', { name: 'Filter rows', exact: true }).fill('Amber')
  await expect(summary.getByText('1 of 37 rows', { exact: true })).toBeVisible()
  await expect(summary.getByText('8 changed', { exact: true })).toBeVisible()
  await grid.getByRole('gridcell', { name: 'Amber poster', exact: true }).dblclick()
  const input = page.getByRole('textbox', { name: 'Name', exact: true })
  await input.fill('Amber revised'); await input.press('Enter')
  await expect(summary.getByText('9 changed', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(summary.getByText('8 changed', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(page.getByText('1 saves', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Refresh rows', exact: true })).toBeEnabled()
  await expect(summary.getByText(/changed$/)).toHaveCount(0)
  await page.reload()
  await expect(summary.getByText('1 of 37 rows', { exact: true })).toBeVisible()
  await expect(summary.getByText(/changed$/)).toHaveCount(0)
  await page.getByRole('searchbox', { name: 'Filter rows', exact: true }).fill('')
  await page.getByRole('button', { name: 'Move row down', exact: true }).click()
  await expect(summary.getByText('1 changed', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(summary.getByText(/changed$/)).toHaveCount(0)
  await page.getByRole('checkbox', { name: 'Delete the selected row: Amber poster', exact: true }).check()
  await page.getByRole('button', { name: 'Delete row', exact: true }).click()
  await expect(summary.getByText('1 changed', { exact: true })).toBeVisible()
  await expect(summary.getByText('36 rows', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(summary.getByText('37 rows', { exact: true })).toBeVisible()
  await expect(summary.getByText(/changed$/)).toHaveCount(0)

})

test('opening a grid has no implicit edit target and selecting all remains keyboard accessible', async ({ page }) => {
  await page.goto('/')
  const grid = page.getByRole('grid', { name: 'Quick-start products' })
  const summary = page.getByRole('group', { name: 'Grid summary', exact: true })
  await expect(summary.getByText('3 rows', { exact: true })).toBeVisible()
  await expect(grid.locator('[aria-selected="true"]')).toHaveCount(0)
  await expect(summary.locator('[data-grid-selection-summary]')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Edit value', exact: true })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Paste into selection', exact: true })).toBeDisabled()
  await grid.focus()
  await grid.press('Delete'); await grid.press('Enter'); await grid.press('ArrowDown')
  await expect(grid.locator('[aria-selected="true"]')).toHaveCount(0)
  await expect(page.getByRole('textbox', { name: 'Name', exact: true })).toHaveCount(0)
  await grid.press('Control+a')
  await expect(summary.getByText('3 rows × 4 columns · 12 cells', { exact: true })).toBeVisible()
  const name = grid.getByRole('gridcell', { name: 'Amber poster', exact: true })
  await name.click()
  await expect(page.getByRole('button', { name: 'Edit value', exact: true })).toBeEnabled()
  await name.press('Enter')
  const input = page.getByRole('textbox', { name: 'Name', exact: true })
  await input.fill('Explicitly selected'); await input.press('Enter')
  await expect(grid.getByRole('gridcell', { name: 'Explicitly selected', exact: true })).toBeVisible()
})
