import { expect, test } from './test.js'

test('menu copy, clear, save and saved undo share the retained selection workflow', async ({ page, context, browserName }) => {
  if (browserName === 'chromium') await context.grantPermissions(['clipboard-write'])
  await page.goto('/#/playground')
  const grid = page.getByRole('grid', { name: 'Inventory items' })
  await expect(grid.getByRole('row')).toHaveCount(37)
  await page.getByRole('switch', { name: 'Auto-save', exact: true }).click()
  const amber = grid.getByRole('gridcell', { name: 'Amber poster', exact: true })
  const blue = grid.getByRole('gridcell', { name: 'Blue card', exact: true })
  await amber.click(); await blue.click({ modifiers: ['Shift'] })
  await blue.press('Shift+F10')
  const menu = page.getByRole('menu', { name: 'Cell actions' })
  await expect(menu.getByRole('menuitem', { name: 'Edit value', exact: true })).toBeFocused()
  await page.keyboard.press('ArrowDown')
  await expect(menu.getByRole('menuitem', { name: 'Copy selection', exact: true })).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(menu).toHaveCount(0)
  await expect(page.getByText('Selection copied.', { exact: true })).toBeVisible()
  await page.evaluate(() => { const input = document.createElement('textarea'); input.setAttribute('aria-label', 'Clipboard destination'); document.body.append(input) })
  const destination = page.getByRole('textbox', { name: 'Clipboard destination', exact: true })
  await destination.focus(); await destination.press('Control+v')
  await expect(destination).toHaveValue('Amber poster\nBlue card')
  await destination.evaluate(element => element.remove())
  await blue.click({ button: 'right' })
  await menu.getByRole('menuitem', { name: 'Clear selection…', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Edit 2 selected fields', exact: true })).toHaveValue('""\n""')
  await expect(amber).toBeVisible(); await expect(blue).toBeVisible()
  await page.getByRole('button', { name: 'Apply value', exact: true }).click()
  const first = grid.getByRole('row').nth(1).getByRole('gridcell').nth(1)
  await expect(first).toHaveText('')
  await first.press('Shift+F10')
  await menu.getByRole('menuitem', { name: 'Save changes', exact: true }).click()
  await expect(page.getByText('1 saves', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Refresh rows', exact: true })).toBeEnabled()
  await page.reload(); await expect(first).toHaveText('')
  await first.click({ button: 'right' })
  await menu.getByRole('menuitem', { name: 'Undo', exact: true }).click()
  await expect(amber).toBeVisible(); await expect(blue).toBeVisible()
  await amber.click({ button: 'right' })
  await menu.getByRole('menuitem', { name: 'Save changes', exact: true }).click()
  await expect(page.getByText('2 saves', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Refresh rows', exact: true })).toBeEnabled()
  await page.reload(); await expect(amber).toBeVisible(); await expect(blue).toBeVisible()
})

test('menu editing preserves focus identity, native input menus, retained input and shared save failure feedback', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message))
  await page.goto('/#/playground')
  const grid = page.getByRole('grid', { name: 'Inventory items' })
  await expect(grid.getByRole('row')).toHaveCount(37)
  await page.getByRole('switch', { name: 'Auto-save', exact: true }).click()
  const amber = grid.getByRole('gridcell', { name: 'Amber poster', exact: true })
  const blue = grid.getByRole('gridcell', { name: 'Blue card', exact: true })
  const menu = page.getByRole('menu', { name: 'Cell actions' })
  await amber.click(); await blue.click({ button: 'right' })
  await menu.getByRole('menuitem', { name: 'Edit value', exact: true }).click()
  const input = page.getByRole('textbox', { name: 'Name', exact: true })
  await expect(input).toHaveValue('Blue card')
  await input.fill('Retained menu input')
  await expect(page.getByRole('button', { name: 'Apply value', exact: true })).toBeEnabled()
  await input.dispatchEvent('contextmenu', { bubbles: true, cancelable: true })
  await expect(menu).toHaveCount(0)
  await amber.press('Shift+F10')
  await expect(menu.getByRole('menuitem', { name: 'Edit value', exact: true })).toBeDisabled()
  await expect(menu.getByRole('menuitem', { name: 'Clear selection…', exact: true })).toBeDisabled()
  await page.keyboard.press('Escape'); await expect(amber).toBeFocused()
  await expect(input).toHaveValue('Retained menu input')
  await page.reload(); await page.getByRole('button', { name: 'Resume editing', exact: true }).click()
  await expect(input).toHaveValue('Retained menu input')
  await page.getByRole('button', { name: 'Apply value', exact: true }).click()
  await expect(grid.getByRole('gridcell', { name: 'Retained menu input', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Fail next save', exact: true }).click()
  await amber.click({ button: 'right' }); await menu.getByRole('menuitem', { name: 'Save changes', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Changes were not saved.')
  await expect(page.getByRole('button', { name: 'Refresh rows', exact: true })).toBeEnabled()
  await amber.click({ button: 'right' }); await menu.getByRole('menuitem', { name: 'Save changes', exact: true }).click()
  await expect(page.getByText('1 saves', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Refresh rows', exact: true })).toBeEnabled()
  await page.reload(); await expect(amber).toBeVisible()
  await expect(grid.getByRole('gridcell', { name: 'Retained menu input', exact: true })).toBeVisible()
  expect(errors).toEqual([])
})

test('menu stays within desktop bounds, inherits theme and closes on changed authority', async ({ page }) => {
  await page.goto('/#/playground')
  const grid = page.getByRole('grid', { name: 'Inventory items' })
  await expect(grid.getByRole('row')).toHaveCount(37)
  const cell = grid.getByRole('gridcell', { name: 'Amber poster', exact: true })
  const menu = page.getByRole('menu', { name: 'Cell actions' })
  await grid.evaluate(element => { const parent = element.closest<HTMLElement>('.business-grid__workspace')!; parent.style.setProperty('--grid-surface', 'rgb(231, 242, 253)'); parent.style.transform = 'translateX(0)' })
  for (const width of [1440, 1920, 2560, 3840]) {
    await page.setViewportSize({ width, height: 1000 })
    await cell.evaluate((element, width) => element.dispatchEvent(new MouseEvent('contextmenu', { bubbles: true, cancelable: true, clientX: width - 2, clientY: 998 })), width)
    await expect(menu).toBeVisible()
    await expect(menu).toHaveCSS('background-color', 'rgb(231, 242, 253)')
    const box = await menu.boundingBox()
    expect(box!.x).toBeGreaterThanOrEqual(8); expect(box!.y).toBeGreaterThanOrEqual(8)
    expect(box!.x + box!.width).toBeLessThanOrEqual(width - 7); expect(box!.y + box!.height).toBeLessThanOrEqual(993)
    await page.keyboard.press('End'); await expect(menu.getByRole('menuitem', { name: 'Refresh rows', exact: true })).toBeFocused()
    await page.keyboard.press('Home'); await expect(menu.getByRole('menuitem', { name: 'Edit value', exact: true })).toBeFocused()
    await page.keyboard.press('Escape'); await expect(cell).toBeFocused()
  }
  await cell.press('Shift+F10')
  // Trigger the external update without an outside pointer dismissal.
  await page.getByRole('button', { name: 'Simulate remote change', exact: true }).evaluate(button => (button as HTMLButtonElement).click())
  await expect(grid.getByText(/^Remote amber/)).toBeVisible()
  await expect(menu).toHaveCount(0)
})
