import { abortExpectedRequest, fulfillExpectedFailure, interruptResourceWork, expect, test } from './test.js'
import { SourceFixture } from '../kernel/source-fixture.js'
import { kernelId } from '../../src/kernel/model.js'
import { readFile } from 'node:fs/promises'

test('Workspace rows distinguish loading and failure, preserve refresh data, and keep row identity through sorting', async ({ page, context }) => {
  const name = `workspace-grid-${crypto.randomUUID()}`
  const source = new SourceFixture({ sourceId: name, id: kernelId<'scope'>('scope'), epoch: kernelId<'scope-epoch'>('epoch') }, { b: { value: 'Beta', hidden: 7 }, a: { value: 'Alpha' } })
  let fail = false, release: (() => void) | null = null
  let hold: Promise<void> | null = null
  await context.route('**/__kernel-source/*', async route => {
    const path = new URL(route.request().url()).pathname, body = route.request().postDataJSON()
    if (path.endsWith('/read')) {
      if (hold) await hold
      if (fail) { await fulfillExpectedFailure(route, { status: 503, body: 'Unavailable' }); return }
    }
    const result = path.endsWith('/read') ? await source.readAtLeast() : path.endsWith('/lookup') ? await source.lookupOperation(body) : await source.submit(body)
    await route.fulfill({ contentType: 'application/json', body: JSON.stringify(result) })
  })
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await page.evaluate(async name => {
    const fixture = await import('/src/test-fixtures/durable-workspace.ts')
    await fixture.startDurableWorkspace(name, false, 'manual', false, { refresh: false })
    const container = document.createElement('div'); container.id = 'workspace-grid'; document.body.append(container)
    ;(await import('/src/test-fixtures/workspace-grid.tsx')).mountWorkspaceGrid(container)
  }, name)
  const table = page.getByRole('table', { name: 'Workspace rows' })
  await expect(page.getByRole('status')).toHaveText('Rows have not been loaded.')
  expect(source.reads).toBe(0)
  fail = true
  await page.evaluate(async () => (await import('/src/test-fixtures/workspace-grid.tsx')).refreshWorkspaceGrid())
  await expect(page.getByRole('alert')).toHaveText('Could not load rows.')
  await expect(page.getByText('No rows yet.', { exact: true })).toHaveCount(0)
  fail = false
  hold = new Promise<void>(resolve => { release = resolve })
  await page.evaluate(async () => { void (await import('/src/test-fixtures/workspace-grid.tsx')).refreshWorkspaceGrid() })
  await expect(page.getByRole('status')).toHaveText('Loading rows…')
  await expect(table).toHaveAttribute('aria-busy', 'true')
  release!(); hold = null
  await expect(table.getByRole('cell')).toHaveText(['Beta', 'Alpha'])
  await expect(table).toHaveAttribute('aria-busy', 'false')
  await table.getByRole('cell', { name: 'Beta', exact: true }).evaluate(cell => { cell.setAttribute('data-preserved', 'yes') })
  await page.evaluate(async () => (await import('/src/test-fixtures/workspace-grid.tsx')).filterWorkspaceGrid(null))
  await expect(table.getByRole('cell')).toHaveText(['Alpha', 'Beta'])
  await expect(table.getByRole('cell', { name: 'Beta', exact: true })).toHaveAttribute('data-preserved', 'yes')
  hold = new Promise<void>(resolve => { release = resolve })
  await page.evaluate(async () => { void (await import('/src/test-fixtures/workspace-grid.tsx')).refreshWorkspaceGrid() })
  await expect(page.getByRole('status')).toHaveText('Refreshing rows…')
  await expect(table.getByRole('cell')).toHaveText(['Alpha', 'Beta'])
  fail = true; release!(); hold = null
  await expect(page.getByRole('alert')).toHaveText('Could not refresh rows. Previous rows are still available.')
  await expect(table.getByRole('cell')).toHaveText(['Alpha', 'Beta'])
  fail = false
  await page.evaluate(async () => (await import('/src/test-fixtures/workspace-grid.tsx')).refreshWorkspaceGrid())
  await page.evaluate(async () => (await import('/src/test-fixtures/workspace-grid.tsx')).filterWorkspaceGrid('missing'))
  await expect(page.getByRole('status')).toHaveText('No matching rows.')
  await expect(table.getByRole('cell')).toHaveCount(0)
  expect(await page.evaluate(async () => (await import('/src/test-fixtures/durable-workspace.ts')).workspaceForReactFixture().getSnapshot().projection.rows.length)).toBe(2)
  source.external({})
  await page.evaluate(async () => (await import('/src/test-fixtures/workspace-grid.tsx')).refreshWorkspaceGrid())
  await expect(page.getByRole('status')).toHaveText('No rows yet.')
  await page.evaluate(async () => (await import('/src/test-fixtures/workspace-grid.tsx')).unmountWorkspaceGrid())
  expect(await page.evaluate(async () => (await import('/src/test-fixtures/durable-workspace.ts')).workspaceForReactFixture().requestClose().lifecycle)).toBe('open')
  expect(source.writes).toBe(0)
  expect(errors).toEqual([])
})

test('Workspace field editing retains invalid and uncertain input, then saves without rollback after reopening', async ({ page, context }) => {
  const name = `workspace-grid-save-${crypto.randomUUID()}`
  const source = new SourceFixture({ sourceId: name, id: kernelId<'scope'>('scope'), epoch: kernelId<'scope-epoch'>('epoch') }, { a: { value: 'Initial', hidden: 7 } })
  const stale = source.snapshot()
  source.normalize = document => ({ ...document, value: String(document.value).trim().toUpperCase() })
  await context.route('**/__kernel-source/*', async route => {
    const path = new URL(route.request().url()).pathname, body = route.request().postDataJSON()
    const result = path.endsWith('/read') ? await source.readAtLeast() : path.endsWith('/lookup') ? await source.lookupOperation(body) : await source.submit(body)
    await route.fulfill({ contentType: 'application/json', body: JSON.stringify(result) })
  })
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()) })
  await page.goto('/')
  await page.evaluate(async name => {
    await (await import('/src/test-fixtures/durable-workspace.ts')).startDurableWorkspace(name, false)
    const container = document.createElement('div'); container.id = 'workspace-grid'; document.body.append(container)
    ;(await import('/src/test-fixtures/workspace-grid.tsx')).mountEditableWorkspaceGrid(container)
  }, name)
  const cell = page.getByRole('grid', { name: 'Workspace rows' }).getByRole('gridcell')
  await expect(cell).toHaveText('Initial')
  await page.getByRole('button', { name: 'Edit value', exact: true }).click()
  const input = page.getByRole('textbox', { name: 'Edit value', exact: true })
  const apply = page.getByRole('button', { name: 'Apply value', exact: true })
  await expect(input).toHaveValue('Initial')
  await input.fill('   ')
  await apply.click()
  await expect(page.getByRole('alert')).toHaveText('Enter a value.')
  await input.press('Escape')
  await page.getByRole('grid', { name: 'Workspace rows' }).click()
  await expect(input).toHaveValue('   ')
  await page.evaluate(async () => (await import('/src/test-fixtures/durable-workspace.ts')).loseNextWorkspaceAcknowledgement())
  await input.fill(' saved ')
  await expect(page.getByRole('status')).toHaveText('Input is awaiting confirmation.')
  await expect(apply).toBeDisabled()
  await expect(input).toHaveValue(' saved ')
  await page.evaluate(async () => (await import('/src/test-fixtures/workspace-grid.tsx')).unmountWorkspaceGrid())
  await expect(input).toHaveCount(0)
  await page.evaluate(async () => (await import('/src/test-fixtures/workspace-grid.tsx')).mountEditableWorkspaceGrid(document.getElementById('workspace-grid')!))
  await expect(input).toHaveValue(' saved ')
  await expect(apply).toBeDisabled()
  await page.getByRole('button', { name: 'Check pending results', exact: true }).click()
  await expect(apply).toBeEnabled()
  expect(source.writes).toBe(0)
  await apply.click()
  await expect(input).toHaveCount(0)
  await expect(cell).toHaveText('saved')
  await page.getByRole('toolbar', { name: 'Workspace actions' }).getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(cell).toHaveText('Initial')
  await page.getByRole('toolbar', { name: 'Workspace actions' }).getByRole('button', { name: 'Redo', exact: true }).click()
  await expect(cell).toHaveText('saved')
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(cell).toHaveText('SAVED')
  await page.getByRole('button', { name: 'Edit value', exact: true }).click()
  await input.dispatchEvent('compositionstart', { data: '' })
  await expect(apply).toBeDisabled()
  await input.dispatchEvent('compositionend', { data: '' })
  await expect(apply).toBeEnabled()
  await input.fill('discard this input')
  await page.getByRole('button', { name: 'Discard input', exact: true }).click()
  await expect(input).toHaveCount(0)
  await expect(cell).toHaveText('SAVED')
  expect(await page.evaluate(async () => (await import('/src/test-fixtures/durable-workspace.ts')).workspaceForReactFixture().getState().inputs.at(-1)?.disposition.kind)).toBe('cancelled-session')
  source.readHook = async () => stale
  await page.evaluate(async () => (await import('/src/test-fixtures/workspace-grid.tsx')).refreshWorkspaceGrid())
  await expect(cell).toHaveText('SAVED')
  source.readHook = null
  await page.reload()
  await page.evaluate(async name => {
    await (await import('/src/test-fixtures/durable-workspace.ts')).startDurableWorkspace(name, true)
    const container = document.createElement('div'); document.body.append(container)
    ;(await import('/src/test-fixtures/workspace-grid.tsx')).mountEditableWorkspaceGrid(container)
  }, name)
  await expect(cell).toHaveText('SAVED')
  await page.evaluate(async () => (await import('/src/test-fixtures/workspace-grid.tsx')).refreshWorkspaceGrid())
  await expect(cell).toHaveText('SAVED')
  expect([...source.rows.values()].map(row => row.document)).toEqual([{ value: 'SAVED', hidden: 7 }])
  expect(source.writes).toBe(1)
  expect(errors).toEqual([])
})

test('Workspace toolbar resolves a lost save response after reopening using the original lookup only', async ({ page, context }) => {
  const name = `workspace-toolbar-${crypto.randomUUID()}`
  const source = new SourceFixture({ sourceId: name, id: kernelId<'scope'>('scope'), epoch: kernelId<'scope-epoch'>('epoch') }, { a: { value: 'Initial', hidden: 7 } })
  source.normalize = document => ({ ...document, value: String(document.value).toUpperCase() })
  let loseResponse = true
  await context.route('**/__kernel-source/*', async route => {
    const path = new URL(route.request().url()).pathname, body = route.request().postDataJSON()
    const result = path.endsWith('/read') ? await source.readAtLeast() : path.endsWith('/lookup') ? await source.lookupOperation(body) : await source.submit(body)
    if (path.endsWith('/submit') && loseResponse) { loseResponse = false; await abortExpectedRequest(route); return }
    await route.fulfill({ contentType: 'application/json', body: JSON.stringify(result) })
  })
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await page.evaluate(async name => {
    await (await import('/src/test-fixtures/durable-workspace.ts')).startDurableWorkspace(name, false)
    const container = document.createElement('div'); document.body.append(container)
    ;(await import('/src/test-fixtures/workspace-grid.tsx')).mountEditableWorkspaceGrid(container)
  }, name)
  await page.getByRole('button', { name: 'Edit value', exact: true }).click()
  await page.getByRole('textbox', { name: 'Edit value', exact: true }).fill('retained')
  await page.getByRole('button', { name: 'Apply value', exact: true }).click()
  const toolbar = page.getByRole('toolbar', { name: 'Workspace actions' })
  await toolbar.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(toolbar.getByRole('alert')).toHaveText('The save result is unknown. Check pending results.')
  await expect(toolbar.getByRole('button', { name: 'Save changes', exact: true })).toBeDisabled()
  await expect(toolbar.getByRole('button', { name: 'Refresh rows', exact: true })).toBeDisabled()
  expect(source.writes).toBe(1)
  const original = source.requests[0]!
  await page.reload()
  await page.evaluate(async name => {
    await (await import('/src/test-fixtures/durable-workspace.ts')).startDurableWorkspace(name, true)
    const container = document.createElement('div'); document.body.append(container)
    ;(await import('/src/test-fixtures/workspace-grid.tsx')).mountEditableWorkspaceGrid(container)
  }, name)
  await toolbar.getByRole('button', { name: 'Check pending results', exact: true }).click()
  await expect(page.getByRole('grid', { name: 'Workspace rows' }).getByRole('gridcell')).toHaveText('RETAINED')
  await expect(toolbar.getByRole('button', { name: 'Check pending results', exact: true })).toHaveCount(0)
  await expect(toolbar.getByRole('alert')).toHaveCount(0)
  expect(source.requests).toEqual([original])
  expect(source.lookups).toBe(1)
  expect(source.writes).toBe(1)
  expect([...source.rows.values()].map(row => row.document)).toEqual([{ value: 'RETAINED', hidden: 7 }])
  expect(errors).toEqual([])
})

test('Workspace selection follows identities while a hidden or deleted session target retains its input', async ({ page, context }) => {
  const name = `workspace-selection-${crypto.randomUUID()}`
  const source = new SourceFixture({ sourceId: name, id: kernelId<'scope'>('scope'), epoch: kernelId<'scope-epoch'>('epoch') },
    { gamma: { value: 'Gamma' }, beta: { value: 'Beta' }, alpha: { value: 'Alpha' } })
  await context.route('**/__kernel-source/*', async route => {
    const path = new URL(route.request().url()).pathname, body = route.request().postDataJSON()
    const result = path.endsWith('/read') ? await source.readAtLeast() : path.endsWith('/lookup') ? await source.lookupOperation(body) : await source.submit(body)
    await route.fulfill({ contentType: 'application/json', body: JSON.stringify(result) })
  })
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()) })
  await page.goto('/')
  await page.evaluate(async name => {
    await (await import('/src/test-fixtures/durable-workspace.ts')).startDurableWorkspace(name, false)
    const container = document.createElement('div'); document.body.append(container)
    ;(await import('/src/test-fixtures/workspace-grid.tsx')).mountEditableWorkspaceGrid(container)
  }, name)
  const grid = page.getByRole('grid', { name: 'Workspace rows' })
  const beta = grid.getByRole('gridcell', { name: 'Beta', exact: true }), alpha = grid.getByRole('gridcell', { name: 'Alpha', exact: true })
  await beta.click()
  await expect(beta).toHaveAttribute('aria-selected', 'true')
  await page.getByRole('button', { name: 'Edit value', exact: true }).click()
  const input = page.getByRole('textbox', { name: 'Edit value', exact: true })
  await expect(input).toHaveValue('Beta')
  await input.fill('Beta draft')
  await expect(page.getByRole('button', { name: 'Apply value', exact: true })).toBeEnabled()
  const original = await page.evaluate(async () => (await import('/src/test-fixtures/durable-workspace.ts')).workspaceForReactFixture().getState().session!)
  await alpha.click()
  await expect(input).toHaveValue('Beta draft')
  await alpha.press('ArrowUp')
  await expect(beta).toBeFocused()
  await expect(beta).toHaveAttribute('aria-selected', 'true')
  await beta.evaluate(cell => cell.setAttribute('data-preserved', 'yes'))
  await page.evaluate(async () => (await import('/src/test-fixtures/workspace-grid.tsx')).filterWorkspaceGrid(null))
  await expect(grid.getByRole('gridcell')).toHaveText(['Alpha', 'Beta', 'Gamma'])
  await expect(beta).toHaveAttribute('aria-selected', 'true')
  await expect(beta).toHaveAttribute('data-preserved', 'yes')
  await beta.press('Control+Home')
  await expect(alpha).toBeFocused()
  await alpha.press('Control+End')
  await expect(grid.getByRole('gridcell', { name: 'Gamma', exact: true })).toBeFocused()
  await beta.click()
  await page.evaluate(async () => (await import('/src/test-fixtures/workspace-grid.tsx')).filterWorkspaceGrid('Alpha'))
  await expect(grid.getByRole('gridcell')).toHaveText(['Alpha'])
  await expect(alpha).toHaveAttribute('aria-selected', 'false')
  await expect(alpha).toHaveAttribute('tabindex', '0')
  await expect(input).toHaveValue('Beta draft')
  await alpha.click()
  source.external({ gamma: { value: 'Gamma' }, alpha: { value: 'Alpha' } })
  const toolbar = page.getByRole('toolbar', { name: 'Workspace actions' })
  await toolbar.getByRole('button', { name: 'Refresh rows', exact: true }).click()
  await expect(input).toHaveValue('Beta draft')
  await expect(page.getByRole('button', { name: 'Apply value', exact: true })).toBeDisabled()
  await expect(page.getByRole('alert')).toHaveText('Review the changed field before applying.')
  source.external({ gamma: { value: 'Gamma' }, alpha: { value: 'Alpha' }, beta: { value: 'Replacement' } })
  await toolbar.getByRole('button', { name: 'Refresh rows', exact: true }).click()
  await expect(toolbar.getByRole('button', { name: 'Refresh rows', exact: true })).toBeEnabled()
  await page.evaluate(async () => (await import('/src/test-fixtures/workspace-grid.tsx')).filterWorkspaceGrid(null))
  await grid.getByRole('gridcell', { name: 'Replacement', exact: true }).click()
  await expect(input).toHaveValue('Beta draft')
  await expect(page.getByRole('button', { name: 'Apply value', exact: true })).toBeDisabled()
  const retained = await page.evaluate(async () => (await import('/src/test-fixtures/durable-workspace.ts')).workspaceForReactFixture().getState().session!)
  expect(retained.target).toEqual(original.target)
  expect(retained.input).toEqual(original.input)
  await page.getByRole('button', { name: 'Discard input', exact: true }).click()
  await page.getByRole('button', { name: 'Edit value', exact: true }).click()
  await expect(input).toHaveValue('Replacement')
  const replacement = await page.evaluate(async () => (await import('/src/test-fixtures/durable-workspace.ts')).workspaceForReactFixture().getState().session!)
  expect(replacement.target).not.toEqual(original.target)
  expect(source.writes).toBe(0)
  expect(errors).toEqual([])
})

test('Workspace editor explicitly reviews changed context and moves retained input to a selected target', async ({ page, context }) => {
  const name = `workspace-retarget-${crypto.randomUUID()}`
  const source = new SourceFixture({ sourceId: name, id: kernelId<'scope'>('scope'), epoch: kernelId<'scope-epoch'>('epoch') },
    { alpha: { value: 'Alpha', hidden: 11 }, beta: { value: 'Beta', hidden: 7 } })
  await context.route('**/__kernel-source/*', async route => {
    const path = new URL(route.request().url()).pathname, body = route.request().postDataJSON()
    const result = path.endsWith('/read') ? await source.readAtLeast() : path.endsWith('/lookup') ? await source.lookupOperation(body) : await source.submit(body)
    await route.fulfill({ contentType: 'application/json', body: JSON.stringify(result) })
  })
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()) })
  await page.goto('/')
  await page.evaluate(async name => {
    await (await import('/src/test-fixtures/durable-workspace.ts')).startDurableWorkspace(name, false)
    const container = document.createElement('div'); document.body.append(container)
    ;(await import('/src/test-fixtures/workspace-grid.tsx')).mountEditableWorkspaceGrid(container)
  }, name)
  const grid = page.getByRole('grid', { name: 'Workspace rows' }), toolbar = page.getByRole('toolbar', { name: 'Workspace actions' })
  await grid.getByRole('gridcell', { name: 'Beta', exact: true }).click()
  await page.getByRole('button', { name: 'Edit value', exact: true }).click()
  const input = page.getByRole('textbox', { name: 'Edit value', exact: true }), apply = page.getByRole('button', { name: 'Apply value', exact: true })
  await input.fill('Retained draft')
  await expect(apply).toBeEnabled()
  source.external({ alpha: { value: 'Alpha', hidden: 11 }, beta: { value: 'Beta remote', hidden: 7 } })
  await toolbar.getByRole('button', { name: 'Refresh rows', exact: true }).click()
  await expect(apply).toBeDisabled()
  await expect(page.getByLabel('Current field value')).toHaveText('Beta remote')
  await expect(input).toHaveValue('Retained draft')
  await page.evaluate(async () => (await import('/src/test-fixtures/durable-workspace.ts')).loseNextWorkspaceAcknowledgement())
  await page.getByRole('button', { name: 'Use the reviewed field context', exact: true }).click()
  await expect(apply).toBeDisabled()
  await toolbar.getByRole('button', { name: 'Check pending results', exact: true }).click()
  await expect(apply).toBeEnabled()
  await expect(input).toHaveValue('Retained draft')
  const reviewed = await page.evaluate(async () => (await import('/src/test-fixtures/durable-workspace.ts')).workspaceForReactFixture().getState().session!)
  source.external({ alpha: { value: 'Alpha', hidden: 11 } })
  await toolbar.getByRole('button', { name: 'Refresh rows', exact: true }).click()
  await expect(apply).toBeDisabled()
  await grid.getByRole('gridcell', { name: 'Alpha', exact: true }).click()
  await expect(page.getByLabel('Value, row 1', { exact: true })).toHaveText('Alpha')
  await expect(input).toHaveValue('Retained draft')
  expect(await page.evaluate(async () => (await import('/src/test-fixtures/durable-workspace.ts')).workspaceForReactFixture().getState().session!.target)).toEqual(reviewed.target)
  await page.getByRole('button', { name: 'Move input to Value, row 1', exact: true }).click()
  await expect(apply).toBeEnabled()
  const moved = await page.evaluate(async () => (await import('/src/test-fixtures/durable-workspace.ts')).workspaceForReactFixture().getState().session!)
  expect(moved.id).toBe(reviewed.id)
  expect(moved.rawInput).toEqual(reviewed.rawInput)
  expect(moved.input.version).toBe(reviewed.input.version + 1)
  expect(moved.editor!.generation).toBeGreaterThan(reviewed.editor!.generation)
  expect(moved.target).not.toEqual(reviewed.target)
  expect(source.writes).toBe(0)
  await apply.click()
  await toolbar.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(grid.getByRole('gridcell')).toHaveText('Retained draft')
  await expect(toolbar.getByRole('button', { name: 'Save changes', exact: true })).toBeDisabled()
  await expect(toolbar.getByRole('status')).toHaveCount(0)
  expect([...source.rows.values()].map(row => row.document)).toEqual([{ value: 'Retained draft', hidden: 11 }])
  expect(source.writes).toBe(1)
  expect(errors).toEqual([])
})

test('reviewing and discarding a rejected command unblocks the retained editor without cancelling its input', async ({ page, context }) => {
  const name = `workspace-ingress-review-${crypto.randomUUID()}`
  const source = new SourceFixture({ sourceId: name, id: kernelId<'scope'>('scope'), epoch: kernelId<'scope-epoch'>('epoch') }, { a: { value: 'Initial', hidden: 7 } })
  await context.route('**/__kernel-source/*', async route => {
    const path = new URL(route.request().url()).pathname, body = route.request().postDataJSON()
    const result = path.endsWith('/read') ? await source.readAtLeast() : path.endsWith('/lookup') ? await source.lookupOperation(body) : await source.submit(body)
    await route.fulfill({ contentType: 'application/json', body: JSON.stringify(result) })
  })
  await page.goto('/')
  await page.evaluate(async name => {
    await (await import('/src/test-fixtures/durable-workspace.ts')).startDurableWorkspace(name, false)
    const container = document.createElement('div'); document.body.append(container)
    ;(await import('/src/test-fixtures/workspace-grid.tsx')).mountEditableWorkspaceGrid(container)
  }, name)
  await page.getByRole('button', { name: 'Edit value', exact: true }).click()
  const input = page.getByRole('textbox', { name: 'Edit value', exact: true }), apply = page.getByRole('button', { name: 'Apply value', exact: true })
  await input.fill('Retained')
  await expect(apply).toBeEnabled()
  const original = await page.evaluate(async () => {
    const workspace = (await import('/src/test-fixtures/durable-workspace.ts')).workspaceForReactFixture(), state = workspace.getState(), session = state.session!
    const result = await workspace.dispatch({ kind: 'session-reconfirmed', lease: session.editor!, inputVersion: session.input.version, revision: state.revision - 1 })
    return { result, input: session.input }
  })
  expect(original.result.kind).toBe('rejected')
  const panel = page.getByRole('region', { name: 'Rejected requests', exact: true })
  await expect(panel).toContainText('This request contains no new input. The active edit remains retained.')
  await expect(apply).toBeDisabled()
  await expect(input).toHaveValue('Retained')
  await page.evaluate(async () => (await import('/src/test-fixtures/durable-workspace.ts')).loseNextWorkspaceAcknowledgement())
  await panel.getByRole('button', { name: 'Discard listed rejected requests', exact: true }).click()
  await expect(panel).toBeVisible()
  await expect(panel.getByRole('button', { name: 'Discard listed rejected requests', exact: true })).toBeDisabled()
  await page.getByRole('toolbar', { name: 'Workspace actions' }).getByRole('button', { name: 'Check pending results', exact: true }).click()
  await expect(panel).toHaveCount(0)
  await page.reload()
  await page.evaluate(async name => {
    await (await import('/src/test-fixtures/durable-workspace.ts')).startDurableWorkspace(name, true)
    const container = document.createElement('div'); document.body.append(container)
    ;(await import('/src/test-fixtures/workspace-grid.tsx')).mountEditableWorkspaceGrid(container)
  }, name)
  await expect(panel).toHaveCount(0)
  await page.getByRole('button', { name: 'Resume editing', exact: true }).click()
  await expect(input).toHaveValue('Retained')
  await expect(apply).toBeEnabled()
  expect(await page.evaluate(async () => (await import('/src/test-fixtures/durable-workspace.ts')).workspaceForReactFixture().getState().session!.input)).toEqual(original.input)
  await apply.click()
  const toolbar = page.getByRole('toolbar', { name: 'Workspace actions' })
  await toolbar.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(toolbar.getByRole('status')).toHaveCount(0)
  expect([...source.rows.values()].map(row => row.document)).toEqual([{ value: 'Retained', hidden: 7 }])
  expect(source.writes).toBe(1)
})

test('a rejected staged file remains downloadable before explicit request disposition', async ({ page, context }) => {
  const name = `workspace-ingress-file-${crypto.randomUUID()}`
  const source = new SourceFixture({ sourceId: name, id: kernelId<'scope'>('scope'), epoch: kernelId<'scope-epoch'>('epoch') }, { a: { value: 'Initial' } })
  await context.route('**/__kernel-source/*', async route => {
    await route.fulfill({ contentType: 'application/json', body: JSON.stringify(await source.readAtLeast()) })
  })
  await page.goto('/')
  await page.evaluate(async name => {
    const fixture = await import('/src/test-fixtures/durable-workspace.ts')
    await fixture.startDurableWorkspace(name, false)
    await fixture.retainRejectedWorkspaceFile()
    const container = document.createElement('div'); document.body.append(container)
    ;(await import('/src/test-fixtures/workspace-grid.tsx')).mountEditableWorkspaceGrid(container)
  }, name)
  const panel = page.getByRole('region', { name: 'Rejected requests', exact: true })
  const downloaded = page.waitForEvent('download')
  await panel.getByRole('link', { name: 'Download 保留.txt', exact: true }).click()
  const download = await downloaded
  expect(download.suggestedFilename()).toBe('保留.txt')
  expect(await readFile((await download.path())!, 'utf8')).toBe('rejected file body')
  await panel.getByRole('button', { name: 'Discard listed rejected requests', exact: true }).click()
  await expect(panel).toHaveCount(0)
  await page.reload()
  await page.evaluate(async name => {
    await (await import('/src/test-fixtures/durable-workspace.ts')).startDurableWorkspace(name, true)
    const container = document.createElement('div'); document.body.append(container)
    ;(await import('/src/test-fixtures/workspace-grid.tsx')).mountEditableWorkspaceGrid(container)
  }, name)
  await expect(panel).toHaveCount(0)
  expect(await page.evaluate(async () => (await import('/src/test-fixtures/durable-workspace.ts')).workspaceForReactFixture().getState().session!.rawInput)).toEqual({ kind: 'encoded', value: 'original' })
  expect(source.writes).toBe(0)
})

test('range gestures capture identities through sorting, filtering and inserted rows without changing editor input', async ({ page, context }) => {
  const name = `workspace-range-${crypto.randomUUID()}`
  const source = new SourceFixture({ sourceId: name, id: kernelId<'scope'>('scope'), epoch: kernelId<'scope-epoch'>('epoch') }, { b: { value: 'Beta' }, a: { value: 'Alpha' }, c: { value: 'Charlie' } })
  await context.route('**/__kernel-source/*', async route => {
    const path = new URL(route.request().url()).pathname, body = route.request().postDataJSON()
    const result = path.endsWith('/read') ? await source.readAtLeast() : path.endsWith('/lookup') ? await source.lookupOperation(body) : await source.submit(body)
    await route.fulfill({ contentType: 'application/json', body: JSON.stringify(result) })
  })
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await page.evaluate(async name => {
    await (await import('/src/test-fixtures/durable-workspace.ts')).startDurableWorkspace(name, false)
    const container = document.createElement('div'); document.body.append(container)
    ;(await import('/src/test-fixtures/workspace-grid.tsx')).mountEditableWorkspaceGrid(container, true)
  }, name)
  const grid = page.getByRole('grid', { name: 'Workspace rows' })
  const beta = grid.getByRole('gridcell', { name: 'Beta', exact: true })
  const alpha = grid.getByRole('gridcell', { name: 'Alpha', exact: true })
  const selected = grid.getByRole('gridcell', { selected: true })
  await beta.first().click()
  await page.getByRole('button', { name: 'Edit value', exact: true }).click()
  const input = page.getByRole('textbox', { name: 'Edit value', exact: true })
  await input.fill('Retained beta input')
  await expect(page.getByRole('button', { name: 'Apply value', exact: true })).toBeEnabled()
  await alpha.last().click({ modifiers: ['Shift'] })
  await expect(selected).toHaveText(['Beta', 'Beta', 'Alpha', 'Alpha'])
  await alpha.last().press('Shift+ArrowLeft')
  await expect(selected).toHaveText(['Beta', 'Alpha'])
  await alpha.first().press('Shift+ArrowRight')
  await expect(selected).toHaveCount(4)
  await page.evaluate(async () => (await import('/src/test-fixtures/workspace-grid.tsx')).filterWorkspaceGrid(null))
  await expect(selected).toHaveText(['Alpha', 'Alpha', 'Beta', 'Beta'])
  source.external({ b: { value: 'Beta' }, a: { value: 'Alpha' }, c: { value: 'Charlie' }, x: { value: 'Alpine' } })
  await page.evaluate(async () => (await import('/src/test-fixtures/workspace-grid.tsx')).refreshWorkspaceGrid())
  await expect(grid.getByRole('gridcell')).toHaveCount(8)
  await expect(grid.getByRole('gridcell')).toHaveText(['Alpha', 'Alpha', 'Alpine', 'Alpine', 'Beta', 'Beta', 'Charlie', 'Charlie'])
  await expect(selected).toHaveText(['Alpha', 'Alpha', 'Beta', 'Beta'])
  await page.evaluate(async () => (await import('/src/test-fixtures/workspace-grid.tsx')).filterWorkspaceGrid('Alpha'))
  await expect(selected).toHaveText(['Alpha', 'Alpha'])
  await page.evaluate(async () => (await import('/src/test-fixtures/workspace-grid.tsx')).filterWorkspaceGrid(null))
  await expect(selected).toHaveText(['Alpha', 'Alpha', 'Beta', 'Beta'])
  await expect(input).toHaveValue('Retained beta input')
  expect(source.writes).toBe(0)
  expect(errors).toEqual([])
})

test('bulk fill keeps the fixed deduplicated target set through new selections, filtering, save and reload', async ({ page, context }) => {
  const name = `workspace-bulk-${crypto.randomUUID()}`
  const source = new SourceFixture({ sourceId: name, id: kernelId<'scope'>('scope'), epoch: kernelId<'scope-epoch'>('epoch') }, { a: { value: 'Alpha', hidden: 1 }, b: { value: 'Beta', hidden: 2 }, c: { value: 'Charlie', hidden: 3 } })
  await context.route('**/__kernel-source/*', async route => {
    const path = new URL(route.request().url()).pathname, body = route.request().postDataJSON()
    const result = path.endsWith('/read') ? await source.readAtLeast() : path.endsWith('/lookup') ? await source.lookupOperation(body) : await source.submit(body)
    await route.fulfill({ contentType: 'application/json', body: JSON.stringify(result) })
  })
  await page.goto('/')
  await page.evaluate(async name => {
    await (await import('/src/test-fixtures/durable-workspace.ts')).startDurableWorkspace(name, false)
    const container = document.createElement('div'); document.body.append(container)
    ;(await import('/src/test-fixtures/workspace-grid.tsx')).mountEditableWorkspaceGrid(container, true)
  }, name)
  const grid = page.getByRole('grid', { name: 'Workspace rows' })
  await grid.getByRole('gridcell', { name: 'Alpha', exact: true }).first().click()
  await grid.getByRole('gridcell', { name: 'Beta', exact: true }).last().click({ modifiers: ['Shift'] })
  await page.getByRole('button', { name: 'Edit value', exact: true }).click()
  const input = page.getByRole('textbox', { name: 'Edit 2 selected fields', exact: true })
  await expect(input).toHaveValue('')
  await page.getByRole('button', { name: 'Apply value', exact: true }).click()
  await expect(page.getByRole('alert')).toHaveText('Enter a value.')
  await input.fill('Filled')
  await expect(page.getByRole('button', { name: 'Apply value', exact: true })).toBeEnabled()
  await grid.getByRole('gridcell', { name: 'Charlie', exact: true }).first().click()
  await page.evaluate(async () => (await import('/src/test-fixtures/workspace-grid.tsx')).filterWorkspaceGrid('Charlie'))
  await expect(input).toHaveValue('Filled')
  await page.getByRole('button', { name: 'Apply value', exact: true }).click()
  await expect(input).toHaveCount(0)
  await page.evaluate(async () => (await import('/src/test-fixtures/workspace-grid.tsx')).filterWorkspaceGrid(null))
  await expect(grid.getByRole('gridcell')).toHaveText(['Charlie', 'Charlie', 'Filled', 'Filled', 'Filled', 'Filled'])
  await page.getByLabel('Workspace actions').getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(grid.getByRole('gridcell')).toHaveText(['Alpha', 'Alpha', 'Beta', 'Beta', 'Charlie', 'Charlie'])
  await page.getByLabel('Workspace actions').getByRole('button', { name: 'Redo', exact: true }).click()
  await expect(grid.getByRole('gridcell', { name: 'Filled', exact: true })).toHaveCount(4)
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect.poll(() => source.writes).toBe(1)
  await expect(page.getByRole('button', { name: 'Refresh rows', exact: true })).toBeEnabled()
  await expect(page.getByRole('button', { name: 'Save changes', exact: true })).toBeDisabled()
  expect(source.writes).toBe(1)
  expect(source.snapshot().rows.map(row => row.document)).toEqual([{ value: 'Filled', hidden: 1 }, { value: 'Filled', hidden: 2 }, { value: 'Charlie', hidden: 3 }])
  await page.reload()
  await page.evaluate(async name => {
    await (await import('/src/test-fixtures/durable-workspace.ts')).startDurableWorkspace(name, true)
    const container = document.createElement('div'); document.body.append(container)
    ;(await import('/src/test-fixtures/workspace-grid.tsx')).mountEditableWorkspaceGrid(container, true)
  }, name)
  await expect(grid.getByRole('gridcell')).toHaveText(['Charlie', 'Charlie', 'Filled', 'Filled', 'Filled', 'Filled'])
  expect(source.writes).toBe(1)
})

test('bulk input reviews changed context and explicitly retargets after deletion and reload', async ({ page, context }) => {
  const name = `workspace-bulk-deleted-${crypto.randomUUID()}`
  const source = new SourceFixture({ sourceId: name, id: kernelId<'scope'>('scope'), epoch: kernelId<'scope-epoch'>('epoch') }, { a: { value: 'Alpha' }, b: { value: 'Beta' } })
  await context.route('**/__kernel-source/*', async route => {
    const path = new URL(route.request().url()).pathname, body = route.request().postDataJSON()
    const result = path.endsWith('/read') ? await source.readAtLeast() : path.endsWith('/lookup') ? await source.lookupOperation(body) : await source.submit(body)
    await route.fulfill({ contentType: 'application/json', body: JSON.stringify(result) })
  })
  await page.goto('/')
  await page.evaluate(async name => {
    await (await import('/src/test-fixtures/durable-workspace.ts')).startDurableWorkspace(name, false)
    const container = document.createElement('div'); document.body.append(container)
    ;(await import('/src/test-fixtures/workspace-grid.tsx')).mountEditableWorkspaceGrid(container)
  }, name)
  const grid = page.getByRole('grid', { name: 'Workspace rows' })
  await grid.getByRole('gridcell', { name: 'Alpha', exact: true }).click()
  await grid.getByRole('gridcell', { name: 'Beta', exact: true }).click({ modifiers: ['Shift'] })
  await page.getByRole('button', { name: 'Edit value', exact: true }).click()
  const input = page.getByRole('textbox', { name: 'Edit 2 selected fields', exact: true })
  await input.fill('Both original rows')
  await expect(page.getByRole('button', { name: 'Apply value', exact: true })).toBeEnabled()
  const original = await page.evaluate(async () => (await import('/src/test-fixtures/durable-workspace.ts')).workspaceForReactFixture().getState().session!.target)
  source.external({ a: { value: 'Alpha updated' }, b: { value: 'Beta' } })
  await page.evaluate(async () => (await import('/src/test-fixtures/workspace-grid.tsx')).refreshWorkspaceGrid())
  await expect(page.getByRole('button', { name: 'Apply value', exact: true })).toBeDisabled()
  await expect(page.getByLabel('Current field value', { exact: true })).toHaveText('Value, row 1: Alpha updated\nValue, row 2: Beta')
  await page.getByRole('button', { name: 'Use the reviewed field context', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Apply value', exact: true })).toBeEnabled()
  await expect(input).toHaveValue('Both original rows')
  source.external({ a: { value: 'Alpha' } })
  await page.evaluate(async () => (await import('/src/test-fixtures/workspace-grid.tsx')).refreshWorkspaceGrid())
  source.external({ a: { value: 'Alpha' }, b: { value: 'Replacement' } })
  await page.evaluate(async () => (await import('/src/test-fixtures/workspace-grid.tsx')).refreshWorkspaceGrid())
  await expect(page.getByRole('button', { name: 'Apply value', exact: true })).toBeDisabled()
  await expect(input).toHaveValue('Both original rows')
  await expect(grid.getByRole('gridcell')).toHaveText(['Alpha', 'Replacement'])
  await page.reload()
  await page.evaluate(async name => {
    await (await import('/src/test-fixtures/durable-workspace.ts')).startDurableWorkspace(name, true)
    const container = document.createElement('div'); document.body.append(container)
    ;(await import('/src/test-fixtures/workspace-grid.tsx')).mountEditableWorkspaceGrid(container)
  }, name)
  await page.getByRole('button', { name: 'Resume editing', exact: true }).click()
  await expect(input).toHaveValue('Both original rows')
  await expect(page.getByRole('button', { name: 'Apply value', exact: true })).toBeDisabled()
  expect(await page.evaluate(async () => {
    const state = (await import('/src/test-fixtures/durable-workspace.ts')).workspaceForReactFixture().getState()
    return { target: state.session!.target, intents: state.journal.intents.length }
  })).toEqual({ target: original, intents: 0 })
  expect(source.writes).toBe(0)
  await grid.getByRole('gridcell', { name: 'Alpha', exact: true }).click()
  await grid.getByRole('gridcell', { name: 'Replacement', exact: true }).click({ modifiers: ['Shift'] })
  await expect(page.getByRole('status', { name: 'Edit 2 selected fields', exact: true })).toHaveText('Value, row 1: Alpha\nValue, row 2: Replacement')
  await page.getByRole('button', { name: 'Move input to Edit 2 selected fields', exact: true }).click()
  await expect(input).toHaveValue('Both original rows')
  await expect(page.getByRole('button', { name: 'Apply value', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: 'Apply value', exact: true }).click()
  await expect(input).toHaveCount(0)
  await expect(grid.getByRole('gridcell')).toHaveText(['Both original rows', 'Both original rows'])
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect.poll(() => source.writes).toBe(1)
  await expect(page.getByRole('button', { name: 'Refresh rows', exact: true })).toBeEnabled()
  expect(source.snapshot().rows.map(row => row.document)).toEqual([{ value: 'Both original rows' }, { value: 'Both original rows' }])
})

test('filter input retains invalid text and competing query context across reload without data writes', async ({ page, context }) => {
  const name = `workspace-filter-${crypto.randomUUID()}`
  const source = new SourceFixture({ sourceId: name, id: kernelId<'scope'>('scope'), epoch: kernelId<'scope-epoch'>('epoch') }, { a: { value: 'Alpha', hidden: 1 }, b: { value: 'Beta', hidden: 2 } })
  await context.route('**/__kernel-source/*', async route => {
    const path = new URL(route.request().url()).pathname, body = route.request().postDataJSON()
    const result = path.endsWith('/read') ? await source.readAtLeast() : path.endsWith('/lookup') ? await source.lookupOperation(body) : await source.submit(body)
    await route.fulfill({ contentType: 'application/json', body: JSON.stringify(result) })
  })
  await page.goto('/')
  await page.evaluate(async name => {
    await (await import('/src/test-fixtures/durable-workspace.ts')).startDurableWorkspace(name, false)
    const container = document.createElement('div'); document.body.append(container)
    ;(await import('/src/test-fixtures/workspace-grid.tsx')).mountEditableWorkspaceGrid(container)
  }, name)
  const grid = page.getByRole('grid', { name: 'Workspace rows' })
  await page.getByRole('button', { name: 'Filter values', exact: true }).click()
  const input = page.getByRole('textbox', { name: 'Value filter', exact: true })
  const apply = page.getByRole('button', { name: 'Apply filter', exact: true })
  await input.fill('*')
  await apply.click()
  await expect(page.getByRole('alert')).toHaveText('Enter literal text without wildcards.')
  await input.press('Escape')
  await grid.click()
  await expect(input).toHaveValue('*')
  await input.fill('Alpha')
  await expect(apply).toBeEnabled()
  await page.evaluate(async () => (await import('/src/test-fixtures/workspace-grid.tsx')).filterWorkspaceGrid('Beta'))
  await expect(apply).toBeDisabled()
  await expect(page.getByLabel('Current filter', { exact: true })).toHaveText('Beta')
  await expect(input).toHaveValue('Alpha')
  await page.reload()
  await page.evaluate(async name => {
    await (await import('/src/test-fixtures/durable-workspace.ts')).startDurableWorkspace(name, true)
    const container = document.createElement('div'); document.body.append(container)
    ;(await import('/src/test-fixtures/workspace-grid.tsx')).mountEditableWorkspaceGrid(container)
  }, name)
  await page.getByRole('button', { name: 'Resume filter editing', exact: true }).click()
  await expect(input).toHaveValue('Alpha')
  await expect(grid.getByRole('gridcell')).toHaveText(['Beta'])
  await expect(apply).toBeDisabled()
  await page.getByRole('button', { name: 'Use the reviewed filter', exact: true }).click()
  await expect(apply).toBeEnabled()
  await input.dispatchEvent('compositionstart', { data: '' })
  await expect(apply).toBeDisabled()
  await input.dispatchEvent('compositionend', { data: '' })
  await apply.click()
  await expect(input).toHaveCount(0)
  await expect(grid.getByRole('gridcell')).toHaveText(['Alpha'])
  await page.getByRole('button', { name: 'Filter values', exact: true }).click()
  await expect(input).toHaveValue('Alpha')
  await input.fill('')
  await apply.click()
  await expect(grid.getByRole('gridcell')).toHaveText(['Alpha', 'Beta'])
  expect(await page.evaluate(async () => {
    const workspace = (await import('/src/test-fixtures/durable-workspace.ts')).workspaceForReactFixture()
    return { rows: workspace.getSnapshot().projection.rows.length, intents: workspace.getState().journal.intents.length,
      disposition: workspace.getState().inputs.at(-1)?.disposition.kind }
  })).toEqual({ rows: 2, intents: 0, disposition: 'applied-to-view' })
  expect(source.writes).toBe(0)
})

test('standard numeric authoring saves numbers and explicit null without coercing invalid text', async ({ page, context }) => {
  const name = `workspace-number-${crypto.randomUUID()}`
  const source = new SourceFixture({ sourceId: name, id: kernelId<'scope'>('scope'), epoch: kernelId<'scope-epoch'>('epoch') }, { a: { value: 12, hidden: 9 } })
  await context.route('**/__kernel-source/*', async route => {
    const path = new URL(route.request().url()).pathname, body = route.request().postDataJSON()
    const result = path.endsWith('/read') ? await source.readAtLeast() : path.endsWith('/lookup') ? await source.lookupOperation(body) : await source.submit(body)
    await route.fulfill({ contentType: 'application/json', body: JSON.stringify(result) })
  })
  await page.goto('/')
  await page.evaluate(async name => {
    await (await import('/src/test-fixtures/durable-workspace.ts')).startDurableWorkspace(name, false)
    const container = document.createElement('div'); document.body.append(container)
    ;(await import('/src/test-fixtures/workspace-grid.tsx')).mountEditableWorkspaceGrid(container, false, true)
  }, name)
  const input = page.getByRole('textbox', { name: 'Edit value', exact: true })
  await page.getByRole('button', { name: 'Edit value', exact: true }).click()
  await expect(input).toHaveValue('12')
  await input.fill('0x10')
  await page.getByRole('button', { name: 'Apply value', exact: true }).click()
  await expect(page.getByRole('alert')).toHaveText('Enter a decimal number.')
  await expect(input).toHaveValue('0x10')
  expect(source.writes).toBe(0)
  await input.fill('4.25e1')
  await page.getByRole('button', { name: 'Apply value', exact: true }).click()
  await expect(input).toHaveCount(0)
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect.poll(() => source.writes).toBe(1)
  await expect(page.getByRole('button', { name: 'Refresh rows', exact: true })).toBeEnabled()
  expect(source.snapshot().rows[0]!.document).toEqual({ value: 42.5, hidden: 9 })
  await page.reload()
  await page.evaluate(async name => {
    await (await import('/src/test-fixtures/durable-workspace.ts')).startDurableWorkspace(name, true)
    const container = document.createElement('div'); document.body.append(container)
    ;(await import('/src/test-fixtures/workspace-grid.tsx')).mountEditableWorkspaceGrid(container, false, true)
  }, name)
  await page.getByRole('button', { name: 'Edit value', exact: true }).click()
  await expect(input).toHaveValue('42.5')
  await input.fill('')
  await page.getByRole('button', { name: 'Apply value', exact: true }).click()
  await expect(input).toHaveCount(0)
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect.poll(() => source.writes).toBe(2)
  await expect(page.getByRole('button', { name: 'Refresh rows', exact: true })).toBeEnabled()
  expect(source.snapshot().rows[0]!.document).toEqual({ value: null, hidden: 9 })
  await page.getByRole('button', { name: 'Edit value', exact: true }).click()
  await expect(input).toHaveValue('')
})

test('choice editing retains typed identity across uncertain input, reload and save', async ({ page, context }) => {
  const name = `workspace-choice-${crypto.randomUUID()}`
  const source = new SourceFixture({ sourceId: name, id: kernelId<'scope'>('scope'), epoch: kernelId<'scope-epoch'>('epoch') }, { a: { value: 1, hidden: 4 } })
  await context.route('**/__kernel-source/*', async route => {
    const path = new URL(route.request().url()).pathname, body = route.request().postDataJSON()
    const result = path.endsWith('/read') ? await source.readAtLeast() : path.endsWith('/lookup') ? await source.lookupOperation(body) : await source.submit(body)
    await route.fulfill({ contentType: 'application/json', body: JSON.stringify(result) })
  })
  await page.goto('/')
  await page.evaluate(async name => {
    await (await import('/src/test-fixtures/durable-workspace.ts')).startDurableWorkspace(name, false)
    const container = document.createElement('div'); document.body.append(container)
    ;(await import('/src/test-fixtures/workspace-grid.tsx')).mountEditableWorkspaceGrid(container, false, false, true)
  }, name)
  await page.getByRole('button', { name: 'Edit value', exact: true }).click()
  const select = page.getByRole('combobox', { name: 'Edit value', exact: true })
  await expect(select).toHaveValue('1')
  await page.evaluate(async () => (await import('/src/test-fixtures/durable-workspace.ts')).loseNextWorkspaceAcknowledgement())
  await select.selectOption({ label: 'Text one' })
  await expect(select).toHaveValue('"1"')
  await expect(page.getByRole('button', { name: 'Apply value', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: 'Check pending results', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Apply value', exact: true })).toBeEnabled()
  await page.reload()
  await page.evaluate(async name => {
    await (await import('/src/test-fixtures/durable-workspace.ts')).startDurableWorkspace(name, true)
    const container = document.createElement('div'); document.body.append(container)
    ;(await import('/src/test-fixtures/workspace-grid.tsx')).mountEditableWorkspaceGrid(container, false, false, true)
  }, name)
  await page.getByRole('button', { name: 'Resume editing', exact: true }).click()
  await expect(select).toHaveValue('"1"')
  await page.getByRole('button', { name: 'Apply value', exact: true }).click()
  await expect(select).toHaveCount(0)
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect.poll(() => source.writes).toBe(1)
  await expect(page.getByRole('button', { name: 'Refresh rows', exact: true })).toBeEnabled()
  expect(source.snapshot().rows[0]!.document).toEqual({ value: '1', hidden: 4 })
  await page.getByRole('button', { name: 'Edit value', exact: true }).click()
  await select.selectOption({ label: 'Numeric one' })
  await page.getByRole('button', { name: 'Discard input', exact: true }).click()
  await expect(select).toHaveCount(0)
  expect(source.snapshot().rows[0]!.document).toEqual({ value: '1', hidden: 4 })
})

test('multi-choice preserves existing order and typed values through reload and bulk replacement', async ({ page, context }) => {
  const name = `workspace-multi-${crypto.randomUUID()}`
  const source = new SourceFixture({ sourceId: name, id: kernelId<'scope'>('scope'), epoch: kernelId<'scope-epoch'>('epoch') }, { a: { value: ['1', 1], hidden: 4 }, b: { value: [], hidden: 5 } })
  await context.route('**/__kernel-source/*', async route => {
    const path = new URL(route.request().url()).pathname, body = route.request().postDataJSON()
    const result = path.endsWith('/read') ? await source.readAtLeast() : path.endsWith('/lookup') ? await source.lookupOperation(body) : await source.submit(body)
    await route.fulfill({ contentType: 'application/json', body: JSON.stringify(result) })
  })
  await page.goto('/')
  await page.evaluate(async name => {
    await (await import('/src/test-fixtures/durable-workspace.ts')).startDurableWorkspace(name, false)
    const container = document.createElement('div'); document.body.append(container)
    ;(await import('/src/test-fixtures/workspace-grid.tsx')).mountEditableWorkspaceGrid(container, false, false, 'multiple')
  }, name)
  await page.getByRole('button', { name: 'Edit value', exact: true }).click()
  const select = page.getByRole('listbox', { name: 'Edit value', exact: true })
  await select.selectOption([{ label: 'Numeric one' }, { label: 'Text one' }, { label: 'Other value' }])
  await expect(page.getByRole('button', { name: 'Apply value', exact: true })).toBeEnabled()
  await page.reload()
  await page.evaluate(async name => {
    await (await import('/src/test-fixtures/durable-workspace.ts')).startDurableWorkspace(name, true)
    const container = document.createElement('div'); document.body.append(container)
    ;(await import('/src/test-fixtures/workspace-grid.tsx')).mountEditableWorkspaceGrid(container, false, false, 'multiple')
  }, name)
  await page.getByRole('button', { name: 'Resume editing', exact: true }).click()
  await expect(select).toHaveValues(['1', '"1"', '"other"'])
  await page.getByRole('button', { name: 'Apply value', exact: true }).click()
  await expect(select).toHaveCount(0)
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect.poll(() => source.writes).toBe(1)
  await expect(page.getByRole('button', { name: 'Refresh rows', exact: true })).toBeEnabled()
  expect(source.snapshot().rows[0]!.document).toEqual({ value: ['1', 1, 'other'], hidden: 4 })
  const cells = page.getByRole('grid', { name: 'Workspace rows' }).getByRole('gridcell')
  await cells.first().click()
  await cells.last().click({ modifiers: ['Shift'] })
  await page.getByRole('button', { name: 'Edit value', exact: true }).click()
  const bulk = page.getByRole('listbox', { name: 'Edit 2 selected fields', exact: true })
  await expect(bulk).toHaveValues([])
  await bulk.selectOption([{ label: 'Numeric one' }, { label: 'Text one' }])
  await page.getByRole('button', { name: 'Apply value', exact: true }).click()
  await expect(bulk).toHaveCount(0)
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect.poll(() => source.writes).toBe(2)
  await expect(page.getByRole('button', { name: 'Refresh rows', exact: true })).toBeEnabled()
  expect(source.snapshot().rows.map(row => row.document)).toEqual([{ value: [1, '1'], hidden: 4 }, { value: [1, '1'], hidden: 5 }])
})

test('Chinese locale covers validation, uncertain input recovery and authoritative save', async ({ page, context }) => {
  const name = `workspace-zh-${crypto.randomUUID()}`
  const source = new SourceFixture({ sourceId: name, id: kernelId<'scope'>('scope'), epoch: kernelId<'scope-epoch'>('epoch') }, { a: { value: 10, hidden: 8 } })
  await context.route('**/__kernel-source/*', async route => {
    const path = new URL(route.request().url()).pathname, body = route.request().postDataJSON()
    const result = path.endsWith('/read') ? await source.readAtLeast() : path.endsWith('/lookup') ? await source.lookupOperation(body) : await source.submit(body)
    await route.fulfill({ contentType: 'application/json', body: JSON.stringify(result) })
  })
  await page.goto('/')
  await page.evaluate(async name => {
    await (await import('/src/test-fixtures/durable-workspace.ts')).startDurableWorkspace(name, false)
    const container = document.createElement('div'); document.body.append(container)
    ;(await import('/src/test-fixtures/workspace-grid.tsx')).mountChineseWorkspaceGrid(container)
  }, name)
  const grid = page.getByRole('grid', { name: '工作区数据' })
  await expect(grid.getByRole('columnheader')).toHaveText('数量')
  await page.getByRole('button', { name: '编辑值', exact: true }).click()
  const input = page.getByRole('textbox', { name: '数量', exact: true })
  await input.fill('无效数字')
  await page.getByRole('button', { name: '应用编辑', exact: true }).click()
  await expect(page.getByRole('alert')).toHaveText('请输入有效的十进制数字。')
  await expect(input).toHaveValue('无效数字')
  await page.evaluate(async () => (await import('/src/test-fixtures/durable-workspace.ts')).loseNextWorkspaceAcknowledgement())
  await input.fill('25')
  await expect(page.getByRole('button', { name: '应用编辑', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: '查询待确认结果', exact: true }).click()
  await expect(page.getByRole('button', { name: '应用编辑', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: '应用编辑', exact: true }).click()
  await expect(input).toHaveCount(0)
  await expect(grid.getByRole('gridcell')).toHaveText('25')
  await page.getByRole('button', { name: '保存更改', exact: true }).click()
  await expect.poll(() => source.writes).toBe(1)
  await expect(page.getByRole('button', { name: '刷新数据', exact: true })).toBeEnabled()
  expect(source.snapshot().rows[0]!.document).toEqual({ value: 25, hidden: 8 })
})

test('matrix paste retains raw text and captured order through invalid dimensions, filtering and reload', async ({ page, context }) => {
  const name = `workspace-matrix-${crypto.randomUUID()}`
  const source = new SourceFixture({ sourceId: name, id: kernelId<'scope'>('scope'), epoch: kernelId<'scope-epoch'>('epoch') }, { b: { value: 'Beta', hidden: 2 }, a: { value: 'Alpha', hidden: 1 } })
  await context.route('**/__kernel-source/*', async route => {
    const path = new URL(route.request().url()).pathname, body = route.request().postDataJSON()
    const result = path.endsWith('/read') ? await source.readAtLeast() : path.endsWith('/lookup') ? await source.lookupOperation(body) : await source.submit(body)
    await route.fulfill({ contentType: 'application/json', body: JSON.stringify(result) })
  })
  await page.goto('/')
  await page.evaluate(async name => {
    await (await import('/src/test-fixtures/durable-workspace.ts')).startDurableWorkspace(name, false)
    const container = document.createElement('div'); document.body.append(container)
    ;(await import('/src/test-fixtures/workspace-grid.tsx')).mountEditableWorkspaceGrid(container)
  }, name)
  const grid = page.getByRole('grid', { name: 'Workspace rows' })
  await grid.getByRole('gridcell', { name: 'Beta', exact: true }).click()
  await grid.getByRole('gridcell', { name: 'Alpha', exact: true }).click({ modifiers: ['Shift'] })
  await page.getByRole('button', { name: 'Paste into selection', exact: true }).click()
  const input = page.getByRole('textbox', { name: 'Edit 2 selected fields', exact: true })
  await input.fill('only one row')
  await page.getByRole('button', { name: 'Apply value', exact: true }).click()
  await expect(page.getByRole('alert')).toHaveText('Could not apply the change. Your input is retained.')
  await expect(input).toHaveValue('only one row')
  await input.fill('For beta\nFor alpha')
  await expect(page.getByRole('button', { name: 'Apply value', exact: true })).toBeEnabled()
  await page.evaluate(async () => (await import('/src/test-fixtures/workspace-grid.tsx')).filterWorkspaceGrid('Alpha'))
  await expect(grid.getByRole('gridcell')).toHaveText(['Alpha'])
  await page.reload()
  await page.evaluate(async name => {
    await (await import('/src/test-fixtures/durable-workspace.ts')).startDurableWorkspace(name, true)
    const container = document.createElement('div'); document.body.append(container)
    ;(await import('/src/test-fixtures/workspace-grid.tsx')).mountEditableWorkspaceGrid(container)
  }, name)
  await page.getByRole('button', { name: 'Resume editing', exact: true }).click()
  await expect(input).toHaveValue('For beta\nFor alpha')
  await page.getByRole('button', { name: 'Apply value', exact: true }).click()
  await expect(input).toHaveCount(0)
  await page.evaluate(async () => (await import('/src/test-fixtures/workspace-grid.tsx')).filterWorkspaceGrid(null))
  await expect(grid.getByRole('gridcell')).toHaveText(['For alpha', 'For beta'])
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect.poll(() => source.writes).toBe(1)
  await expect(page.getByRole('button', { name: 'Refresh rows', exact: true })).toBeEnabled()
  expect(source.snapshot().rows.map(row => row.document)).toEqual([{ value: 'For beta', hidden: 2 }, { value: 'For alpha', hidden: 1 }])
})

test('direct grid paste retains a second rejected paste without replacing the active matrix input', async ({ page, context }) => {
  const name = `workspace-direct-paste-${crypto.randomUUID()}`
  const source = new SourceFixture({ sourceId: name, id: kernelId<'scope'>('scope'), epoch: kernelId<'scope-epoch'>('epoch') }, { a: { value: 'Alpha', hidden: 1 }, b: { value: 'Beta', hidden: 2 } })
  await context.route('**/__kernel-source/*', async route => {
    const path = new URL(route.request().url()).pathname, body = route.request().postDataJSON()
    const result = path.endsWith('/read') ? await source.readAtLeast() : path.endsWith('/lookup') ? await source.lookupOperation(body) : await source.submit(body)
    await route.fulfill({ contentType: 'application/json', body: JSON.stringify(result) })
  })
  await page.goto('/')
  await page.evaluate(async name => {
    await (await import('/src/test-fixtures/durable-workspace.ts')).startDurableWorkspace(name, false)
    const container = document.createElement('div'); document.body.append(container)
    ;(await import('/src/test-fixtures/workspace-grid.tsx')).mountEditableWorkspaceGrid(container)
  }, name)
  const cells = page.getByRole('grid', { name: 'Workspace rows' }).getByRole('gridcell')
  await cells.first().click()
  await cells.last().click({ modifiers: ['Shift'] })
  const paste = async (text: string) => cells.last().evaluate((cell, text) => {
    const data = new DataTransfer(); data.setData('text/plain', text)
    const event = new Event('paste', { bubbles: true, cancelable: true })
    Object.defineProperty(event, 'clipboardData', { value: data })
    cell.dispatchEvent(event)
    return event.defaultPrevented
  }, text)
  expect(await paste('First alpha\nFirst beta')).toBe(true)
  const input = page.getByRole('textbox', { name: 'Edit 2 selected fields', exact: true })
  await expect(input).toHaveValue('First alpha\nFirst beta')
  await expect(page.getByRole('button', { name: 'Apply value', exact: true })).toBeEnabled()
  expect(await paste('Second alpha\nSecond beta')).toBe(true)
  const retained = page.getByRole('textbox', { name: 'Retained input 1', exact: true })
  await expect(retained).toBeVisible()
  expect(JSON.parse(await retained.inputValue()).text).toBe('Second alpha\nSecond beta')
  await expect(input).toHaveValue('First alpha\nFirst beta')
  await expect(page.getByRole('button', { name: 'Apply value', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: 'Discard listed rejected requests', exact: true }).click()
  await expect(retained).toHaveCount(0)
  await expect(input).toHaveValue('First alpha\nFirst beta')
  await page.getByRole('button', { name: 'Apply value', exact: true }).click()
  await expect(input).toHaveCount(0)
  await expect(cells).toHaveText(['First alpha', 'First beta'])
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect.poll(() => source.writes).toBe(1)
  await expect(page.getByRole('button', { name: 'Refresh rows', exact: true })).toBeEnabled()
  expect(source.snapshot().rows.map(row => row.document)).toEqual([{ value: 'First alpha', hidden: 1 }, { value: 'First beta', hidden: 2 }])
})

test('file input is owned before execution and recovers a lost task result after reload without uploading twice', async ({ page, context }) => {
  const { DurableTaskFixture } = await import('../kernel/durable-task-fixture.js')
  const name = `workspace-resource-editor-${crypto.randomUUID()}`
  const source = new SourceFixture({ sourceId: name, id: kernelId<'scope'>('scope'), epoch: kernelId<'scope-epoch'>('epoch') }, { a: { value: 'Original', hidden: 6 } })
  const tasks = new DurableTaskFixture()
  tasks.result = request => {
    if (request.owner.kind !== 'session') throw new Error('Expected a session owner')
    return { kind: 'session-candidate', sessionId: request.owner.sessionId, input: { kind: 'encoded', value: 'Uploaded result' } }
  }
  let drop = true
  await context.route('**/__kernel-source/*', async route => {
    const path = new URL(route.request().url()).pathname, body = route.request().postDataJSON()
    const result = path.endsWith('/read') ? await source.readAtLeast() : path.endsWith('/lookup') ? await source.lookupOperation(body) : await source.submit(body)
    await route.fulfill({ contentType: 'application/json', body: JSON.stringify(result) })
  })
  await context.route('**/__kernel-task/*', async route => {
    const body = route.request().postDataJSON(), start = new URL(route.request().url()).pathname.endsWith('/start')
    const result = await tasks.definition[start ? 'start' : 'lookup'](body.request, { signal: new AbortController().signal,
      resource: body.resource ? new Blob([new Uint8Array(body.resource)]) : null })
    if (start && drop) { drop = false; await abortExpectedRequest(route); return }
    await route.fulfill({ contentType: 'application/json', body: JSON.stringify(result) })
  })
  await page.goto('/')
  await page.evaluate(async name => {
    await (await import('/src/test-fixtures/durable-workspace.ts')).startDurableWorkspace(name, false)
    const container = document.createElement('div'); container.id = 'resource-grid'; document.body.append(container)
    ;(await import('/src/test-fixtures/workspace-grid.tsx')).mountResourceWorkspaceGrid(container)
  }, name)
  await page.getByRole('button', { name: 'Edit value', exact: true }).click()
  await page.getByLabel('Choose a file', { exact: true }).setInputFiles({ name: '原始文件.txt', mimeType: 'text/plain', buffer: Buffer.from('original file bytes') })
  await expect.poll(() => tasks.executions).toBe(1)
  await expect(page.getByRole('button', { name: 'Check pending results', exact: true })).toBeVisible()
  await expect(page.getByRole('textbox', { name: 'Edit value', exact: true })).toHaveValue('Original')
  expect(tasks.requests[0]!.resource!.descriptor).toMatchObject({ name: '原始文件.txt', size: 19 })
  await interruptResourceWork(page, () => page.reload())
  await page.evaluate(async name => {
    await (await import('/src/test-fixtures/durable-workspace.ts')).startDurableWorkspace(name, true)
    const container = document.createElement('div'); container.id = 'resource-grid'; document.body.append(container)
    ;(await import('/src/test-fixtures/workspace-grid.tsx')).mountResourceWorkspaceGrid(container)
  }, name)
  await page.getByRole('button', { name: 'Check pending results', exact: true }).click()
  await page.getByRole('button', { name: 'Resume editing', exact: true }).click()
  const input = page.getByRole('textbox', { name: 'Edit value', exact: true })
  await expect(input).toHaveValue('Uploaded result')
  await page.getByRole('button', { name: 'Apply value', exact: true }).click()
  await expect(input).toHaveCount(0)
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect.poll(() => source.writes).toBe(1)
  await expect(page.getByRole('button', { name: 'Refresh rows', exact: true })).toBeEnabled()
  expect(source.snapshot().rows[0]!.document).toEqual({ value: 'Uploaded result', hidden: 6 })
  expect(tasks.executions).toBe(1)
  expect(tasks.requests).toHaveLength(1)
  expect(tasks.lookups).toHaveLength(1)
  let release!: () => void
  tasks.beforeStart = () => new Promise<void>(resolve => { release = resolve })
  await page.getByRole('button', { name: 'Edit value', exact: true }).click()
  await page.getByLabel('Choose a file', { exact: true }).setInputFiles({ name: 'second.txt', mimeType: 'text/plain', buffer: Buffer.from('second file') })
  await expect.poll(() => tasks.requests.length).toBe(2)
  await input.fill('Newer manual input')
  await expect(page.getByRole('button', { name: 'Apply value', exact: true })).toBeEnabled()
  release()
  await expect.poll(() => tasks.executions).toBe(2)
  await page.getByRole('button', { name: 'Check pending results', exact: true }).click()
  await expect(input).toHaveValue('Newer manual input')
  await expect.poll(() => page.evaluate(async () => {
    const task = (await import('/src/test-fixtures/durable-workspace.ts')).workspaceForReactFixture().getState().tasks.at(-1)!
    return { kind: task.kind, result: 'result' in task ? task.result : null }
  })).toMatchObject({ kind: 'superseded', result: { kind: 'session-candidate', input: { value: 'Uploaded result' } } })
  expect(source.writes).toBe(1)
  await page.evaluate(async () => (await import('/src/test-fixtures/workspace-grid.tsx')).mountEditableWorkspaceGrid(document.getElementById('resource-grid')!))
  await expect(page.getByLabel('Choose a file', { exact: true })).toHaveCount(0)
  const downloaded = page.waitForEvent('download')
  await page.getByRole('link', { name: 'Download second.txt', exact: true }).click()
  const download = await downloaded
  expect(download.suggestedFilename()).toBe('second.txt')
  expect(await readFile((await download.path())!, 'utf8')).toBe('second file')
  await expect(page.getByRole('textbox', { name: 'Retained file result', exact: true })).toHaveValue('Uploaded result')
  await expect(page.getByRole('textbox', { name: 'Current input to replace', exact: true })).toHaveValue('Newer manual input')
  await page.evaluate(async () => (await import('/src/test-fixtures/durable-workspace.ts')).loseNextWorkspaceAcknowledgement())
  await page.getByRole('button', { name: 'Use result in this edit', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Use result in this edit', exact: true })).toBeDisabled()
  await expect(input).toHaveValue('Newer manual input')
  await page.getByRole('button', { name: 'Check pending results', exact: true }).click()
  await expect(input).toHaveValue('Uploaded result')
  await expect(page.getByRole('textbox', { name: 'Retained file result', exact: true })).toHaveCount(0)
  expect(tasks.executions).toBe(2)
  expect(tasks.requests).toHaveLength(2)
  expect(await page.evaluate(async () => {
    const state = (await import('/src/test-fixtures/durable-workspace.ts')).workspaceForReactFixture().getState()
    return state.inputs.some(record => record.input.kind === 'encoded' && record.input.value === 'Newer manual input' && record.disposition.kind === 'superseded')
  })).toBe(true)
  await page.evaluate(async () => (await import('/src/test-fixtures/workspace-grid.tsx')).mountResourceWorkspaceGrid(document.getElementById('resource-grid')!))
  await page.getByLabel('Choose a file', { exact: true }).setInputFiles({ name: 'cancelled.txt', mimeType: 'text/plain', buffer: Buffer.from('cancelled file bytes') })
  await expect.poll(() => tasks.requests.length).toBe(3)
  await page.evaluate(async () => (await import('/src/test-fixtures/durable-workspace.ts')).loseNextWorkspaceAcknowledgement())
  await page.getByRole('button', { name: 'Cancel task', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Cancel task', exact: true })).toBeDisabled()
  await expect(input).toHaveValue('Uploaded result')
  await page.getByRole('button', { name: 'Check pending results', exact: true }).click()
  await expect(page.getByText('Task will not update your edit. Its material is retained.', { exact: true })).toBeVisible()
  await expect(page.getByRole('toolbar', { name: 'Workspace actions' }).getByRole('status')).toHaveCount(0)
  release()
  await expect.poll(() => tasks.executions).toBe(3)
  await page.getByRole('button', { name: 'Check pending results', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Retained file result', exact: true })).toHaveValue('Uploaded result')
  await expect(page.getByRole('button', { name: 'Use result in this edit', exact: true })).toHaveCount(0)
  await expect(input).toHaveValue('Uploaded result')
  const cancelledDownload = page.waitForEvent('download')
  await page.getByRole('link', { name: 'Download cancelled.txt', exact: true }).click()
  expect(await readFile((await (await cancelledDownload).path())!, 'utf8')).toBe('cancelled file bytes')
  expect(source.writes).toBe(1)
  await page.reload()
  await page.evaluate(async name => {
    await (await import('/src/test-fixtures/durable-workspace.ts')).startDurableWorkspace(name, true)
    const container = document.createElement('div'); document.body.append(container)
    ;(await import('/src/test-fixtures/workspace-grid.tsx')).mountEditableWorkspaceGrid(container)
  }, name)
  await expect(page.getByText('Task will not update your edit. Its material is retained.', { exact: true })).toBeVisible()
  await expect(page.getByRole('textbox', { name: 'Retained file result', exact: true })).toHaveValue('Uploaded result')
  await expect(page.getByRole('button', { name: 'Use result in this edit', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Resume editing', exact: true }).click()
  await expect(input).toHaveValue('Uploaded result')
  const restoredDownload = page.waitForEvent('download')
  await page.getByRole('link', { name: 'Download cancelled.txt', exact: true }).click()
  expect(await readFile((await (await restoredDownload).path())!, 'utf8')).toBe('cancelled file bytes')
  expect(tasks.executions).toBe(3)
  expect(source.writes).toBe(1)
})
