import { expect, test } from './test.js'

test('clear keeps typed empty input for review and reopening, saves exactly, and supports saved undo', async ({ page }) => {
  await page.goto('/#/playground')
  const grid = page.getByRole('grid', { name: 'Inventory items' }), row = grid.getByRole('row').nth(1)
  await expect(grid.getByRole('row')).toHaveCount(37)
  const automatic = page.getByRole('switch', { name: 'Auto-save', exact: true })
  await automatic.click(); await expect(automatic).not.toBeChecked()
  const clear = page.getByRole('button', { name: 'Clear selection…', exact: true })
  await row.getByRole('gridcell').nth(2).click()
  await expect(clear).toBeDisabled()
  await row.getByRole('gridcell').nth(0).click()
  await row.getByRole('gridcell').nth(2).click({ modifiers: ['Shift'] })
  await expect(clear).toBeDisabled()
  await row.getByRole('gridcell').nth(5).click()
  await clear.click()
  const tags = page.getByRole('group', { name: 'Choose values', exact: true })
  await expect(tags.getByRole('checkbox', { checked: true })).toHaveCount(0)
  await expect(row.getByRole('gridcell').nth(5)).toHaveAccessibleName('Featured, Seasonal, Wholesale')
  await expect(page.getByRole('button', { name: 'Apply', exact: true })).toBeEnabled()
  await page.reload()
  await page.getByRole('button', { name: 'Resume editing', exact: true }).click()
  await expect(tags.getByRole('checkbox', { checked: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Apply', exact: true }).click()
  await expect(row.getByRole('gridcell').nth(5)).toHaveAccessibleName('No tags')
  async function save(count: number) {
    await page.getByRole('button', { name: 'Save changes', exact: true }).click()
    await expect(page.getByText(`${count} saves`, { exact: true })).toBeVisible()
    await expect(page.getByRole('button', { name: 'Refresh rows', exact: true })).toBeEnabled()
  }
  await save(1)
  await page.reload()
  await expect(row.getByRole('gridcell').nth(5)).toHaveAccessibleName('No tags')
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(row.getByRole('gridcell').nth(5)).toHaveAccessibleName('Featured, Seasonal, Wholesale')
  await save(2)
  await row.getByRole('gridcell').nth(1).click()
  await clear.click()
  await expect(page.getByRole('textbox', { name: 'Name', exact: true })).toHaveValue('')
  await expect(row.getByRole('gridcell').nth(1)).toHaveText('Amber poster')
  await page.getByRole('button', { name: 'Apply value', exact: true }).click()
  await expect(row.getByRole('gridcell').nth(1)).toHaveText('')
  await save(3)
  await page.reload()
  await expect(row.getByRole('gridcell').nth(1)).toHaveText('')
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await save(4)
  await page.reload()
  await expect(row.getByRole('gridcell').nth(1)).toHaveText('Amber poster')
  await expect(row.getByRole('gridcell').nth(2)).toHaveText('12')
  await expect(row.getByRole('gridcell').nth(5)).toHaveAccessibleName('Featured, Seasonal, Wholesale')
})

for (const trigger of ['button', 'Delete', 'Backspace']) test(`bulk clear via ${trigger} retains the original two names while display sorting changes`, async ({ page }) => {
  await page.goto('/#/playground')
  const grid = page.getByRole('grid', { name: 'Inventory items' })
  await expect(grid.getByRole('row')).toHaveCount(37)
  const automatic = page.getByRole('switch', { name: 'Auto-save', exact: true })
  await automatic.click(); await expect(automatic).not.toBeChecked()
  await grid.getByRole('gridcell', { name: 'Amber poster', exact: true }).click()
  await grid.getByRole('gridcell', { name: 'Blue card', exact: true }).click({ modifiers: ['Shift'] })
  if (trigger === 'button') await page.getByRole('button', { name: 'Clear selection…', exact: true }).click()
  else await grid.getByRole('gridcell', { name: 'Blue card', exact: true }).press(trigger)
  const input = page.getByRole('textbox', { name: 'Edit 2 selected fields', exact: true })
  await expect(input).toHaveValue('""\n""')
  await expect(page.getByRole('button', { name: 'Apply value', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: 'Sort Name', exact: true }).click()
  await expect(grid.getByRole('row').nth(1)).not.toContainText('Amber poster')
  await page.getByRole('button', { name: 'Apply value', exact: true }).click()
  const amber = grid.getByRole('row').filter({ has: page.getByRole('gridcell', { name: '12', exact: true }) })
  const blue = grid.getByRole('row').filter({ has: page.getByRole('gridcell', { name: '14', exact: true }) })
  await expect(amber.getByRole('gridcell').nth(1)).toHaveText('')
  await expect(blue.getByRole('gridcell').nth(1)).toHaveText('')
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(page.getByText('1 saves', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Refresh rows', exact: true })).toBeEnabled()
  await page.reload()
  await expect(amber.getByRole('gridcell').nth(1)).toHaveText('')
  await expect(blue.getByRole('gridcell').nth(1)).toHaveText('')
  await expect(grid.getByRole('gridcell', { name: 'Alpine ticket', exact: true })).toBeVisible()
})

test('keyboard clear respects focused identity, disabled fields, native text deletion and existing input', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message))
  await page.goto('/#/playground')
  const grid = page.getByRole('grid', { name: 'Inventory items' })
  await expect(grid.getByRole('row')).toHaveCount(37)
  const automatic = page.getByRole('switch', { name: 'Auto-save', exact: true })
  await automatic.click(); await expect(automatic).not.toBeChecked()
  const amber = grid.getByRole('gridcell', { name: 'Amber poster', exact: true })
  const blue = grid.getByRole('gridcell', { name: 'Blue card', exact: true })
  const apply = page.getByRole('button', { name: 'Apply value', exact: true })
  await grid.getByRole('row').nth(1).getByRole('gridcell').nth(2).press('Delete')
  await expect(apply).toHaveCount(0)
  await amber.click()
  await amber.press('Control+Delete')
  await amber.press('Shift+Backspace')
  await amber.dispatchEvent('keydown', { key: 'Delete', isComposing: true })
  await amber.dispatchEvent('keydown', { key: 'Delete', repeat: true })
  await expect(apply).toHaveCount(0)
  // Focus alone does not update the selected range. Clear must target Blue.
  await blue.press('Backspace')
  const input = page.getByRole('textbox', { name: 'Name', exact: true })
  await expect(input).toHaveValue('')
  await expect(amber).toBeVisible(); await expect(blue).toBeVisible()
  await input.fill('retained value')
  await expect(apply).toBeEnabled()
  await input.press('End'); await input.press('Backspace')
  await expect(input).toHaveValue('retained valu')
  await expect(apply).toBeEnabled()
  await amber.press('Delete')
  await expect(input).toHaveValue('retained valu')
  await page.reload()
  await page.getByRole('button', { name: 'Resume editing', exact: true }).click()
  await expect(input).toHaveValue('retained valu')
  await apply.click()
  await expect(amber).toBeVisible()
  await expect(grid.getByRole('gridcell', { name: 'retained valu', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Fail next save', exact: true }).click()
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Changes were not saved.')
  await expect(page.getByText('0 saves', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Refresh rows', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(page.getByText('1 saves', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Refresh rows', exact: true })).toBeEnabled()
  await page.reload()
  await expect(amber).toBeVisible()
  await expect(grid.getByRole('gridcell', { name: 'retained valu', exact: true })).toBeVisible()
  for (const width of [1440, 1920, 2560, 3840]) {
    await page.setViewportSize({ width, height: 1000 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  }
  expect(errors).toEqual([])
})
